import { S, type FinancialTemplate } from "./types.ts";

const COL = (i: number) => String.fromCharCode(66 + i);
const YRS = ["FY2026", "FY2027", "FY2028", "FY2029", "FY2030"];
const cols = YRS.map((_, i) => COL(i));

export const ADVANCED_TEMPLATES: FinancialTemplate[] = [
  {
    id: "dcf",
    name: "Discounted Cash Flow (DCF) Valuation",
    tier: "Advanced",
    blurb:
      "5-year FCFF engine with a CAPM/WACC calculator, Gordon Growth and exit-multiple terminal value plus sensitivity tables.",
    features: ["FCFF & FCFE", "CAPM WACC", "Dual terminal value", "Sensitivity matrices"],
    prompt: "Extend this DCF to 10 years and add a football-field valuation summary.",
    build: () => [
      S("WACC", [
        ["WACC CALCULATOR (CAPM)"],
        [],
        ["Risk-free rate", 0.042],
        ["Equity risk premium", 0.055],
        ["Beta (levered)", 1.25],
        ["Size / country premium", 0.01],
        ["Cost of equity", "=B3+B5*B4+B6"],
        [],
        ["Pre-tax cost of debt", 0.068],
        ["Tax rate", 0.25],
        ["After-tax cost of debt", "=B9*(1-B10)"],
        [],
        ["Market value of equity", 180000],
        ["Market value of debt", 60000],
        ["Total capital", "=B13+B14"],
        ["Weight of equity", "=B13/B15"],
        ["Weight of debt", "=B14/B15"],
        [],
        ["WACC", "=B16*B7+B17*B11"],
      ]),
      S("DCF", [
        ["DCF VALUATION ($000s)", ...YRS, "Terminal"],
        ["Revenue", 42000, ...cols.slice(1).map((c, i) => `=${cols[i]}2*(1+$B$29)`)],
        ["EBITDA", ...cols.map((c) => `=${c}2*$B$30`)],
        ["Depreciation & amortisation", ...cols.map((c) => `=-${c}2*$B$31`)],
        ["EBIT", ...cols.map((c) => `=${c}3+${c}4`)],
        ["Taxes on EBIT", ...cols.map((c) => `=-${c}5*WACC!$B$10`)],
        ["NOPAT", ...cols.map((c) => `=${c}5+${c}6`)],
        ["Add back D&A", ...cols.map((c) => `=-${c}4`)],
        ["Capital expenditure", ...cols.map((c) => `=-${c}2*$B$32`)],
        ["Change in net working capital", ...cols.map((c) => `=-${c}2*$B$33`)],
        ["Free cash flow to firm (FCFF)", ...cols.map((c) => `=SUM(${c}7:${c}10)`)],
        ["Interest expense (after tax)", ...cols.map(() => "=-WACC!$B$14*WACC!$B$11")],
        ["Free cash flow to equity (FCFE)", ...cols.map((c) => `=${c}11+${c}12`)],
        [],
        ["Discount period", ...cols.map((_, i) => i + 1)],
        ["Discount factor", ...cols.map((c) => `=1/(1+WACC!$B$19)^${c}15`)],
        ["PV of FCFF", ...cols.map((c) => `=${c}11*${c}16`)],
        [],
        ["Sum of PV (explicit period)", "=SUM(B17:F17)"],
        ["Terminal value — Gordon Growth", "=IFERROR(F11*(1+$B$34)/(WACC!$B$19-$B$34),0)"],
        ["Terminal value — exit multiple", "=F3*$B$35"],
        ["Selected terminal value", '=IF($B$36="Gordon",B20,B21)'],
        ["PV of terminal value", "=B22*F16"],
        ["Enterprise value", "=B19+B23"],
        ["Less: net debt", "=-(WACC!$B$14-2500)"],
        ["Equity value", "=B24+B25"],
        [],
        ["ASSUMPTIONS", ""],
        ["Revenue growth", 0.11],
        ["EBITDA margin", 0.26],
        ["D&A % of revenue", 0.05],
        ["CapEx % of revenue", 0.055],
        ["Change in NWC % of revenue", 0.015],
        ["Terminal growth rate", 0.025],
        ["Exit EV/EBITDA multiple", 9.5],
        ["Terminal method (Gordon / Exit)", "Gordon"],
        ["Diluted shares (000s)", 12500],
        ["Implied value per share", "=IFERROR(B26/B37,0)"],
      ]),
      S("Sensitivity", [
        ["SENSITIVITY — ENTERPRISE VALUE"],
        ["Rows: WACC   Columns: terminal growth"],
        [],
        ["EV", 0.015, 0.02, 0.025, 0.03, 0.035],
        ...[0.08, 0.09, 0.1, 0.11, 0.12].map((w, i) => {
          const row = 5 + i;
          return [
            w,
            ...[1, 2, 3, 4, 5].map(
              (c) =>
                `=DCF!$B$18+(DCF!$F$11*(1+${String.fromCharCode(65 + c)}$4)/($A${row}-${String.fromCharCode(
                  65 + c,
                )}$4))/(1+$A${row})^5`,
            ),
          ];
        }),
        [],
        ["SENSITIVITY — VALUE PER SHARE"],
        ["Rows: WACC   Columns: exit EV/EBITDA multiple"],
        [],
        ["Per share", 7.5, 8.5, 9.5, 10.5, 11.5],
        ...[0.08, 0.09, 0.1, 0.11, 0.12].map((w, i) => {
          const row = 15 + i;
          return [
            w,
            ...[1, 2, 3, 4, 5].map(
              (c) =>
                `=(DCF!$B$18+(DCF!$F$3*${String.fromCharCode(65 + c)}$14)/(1+$A${row})^5+DCF!$B$24)/DCF!$B$35`,
            ),
          ];
        }),
      ]),
    ],
  },
  {
    id: "ma-accretion",
    name: "M&A Accretion / Dilution Model",
    tier: "Advanced",
    blurb:
      "Purchase price allocation, goodwill, synergy realisation, pro-forma combination and EPS impact.",
    features: ["PPA & goodwill", "Synergies", "Pro-forma EPS", "Accretion / dilution"],
    prompt: "Add a contribution analysis and a break-even synergy calculation.",
    build: () => [
      S("Deal Assumptions", [
        ["M&A DEAL ASSUMPTIONS"],
        [],
        ["Acquirer share price", 48.5],
        ["Acquirer diluted shares (mm)", 120],
        ["Acquirer market cap", "=B3*B4"],
        ["Acquirer net income", 310],
        ["Acquirer EPS", "=B6/B4"],
        [],
        ["Target share price (unaffected)", 22.4],
        ["Target diluted shares (mm)", 55],
        ["Offer premium", 0.28],
        ["Offer price per share", "=B9*(1+B11)"],
        ["Equity purchase price", "=B12*B10"],
        ["Target net debt assumed", 340],
        ["Enterprise value of deal", "=B13+B14"],
        ["Target net income", 96],
        ["Target EBITDA", 210],
        ["Implied EV/EBITDA", "=B15/B17"],
        [],
        ["% cash consideration", 0.6],
        ["% stock consideration", "=1-B20"],
        ["Interest rate on new debt", 0.065],
        ["Tax rate", 0.25],
        ["Foregone interest on cash", 0.02],
        [],
        ["Revenue synergies (run-rate)", 85],
        ["Synergy margin", 0.45],
        ["Cost synergies (run-rate)", 60],
        ["Synergy phase-in year 1", 0.5],
        ["Integration costs (one-time)", 45],
      ]),
      S("PPA & Goodwill", [
        ["PURCHASE PRICE ALLOCATION"],
        [],
        ["Equity purchase price", "='Deal Assumptions'!B13"],
        ["Target book value of equity", 410],
        ["Excess purchase price", "=B3-B4"],
        [],
        ["Write-up of PP&E", 120],
        ["Identified intangibles (customer, brand)", 260],
        ["Deferred tax liability on write-ups", "=-(B7+B8)*'Deal Assumptions'!B23"],
        ["Total allocated to assets", "=SUM(B7:B9)"],
        ["Goodwill created", "=B5-B10"],
        [],
        ["Intangible amortisation life (yrs)", 10],
        ["Annual intangible amortisation", "=B8/B13"],
        ["Incremental depreciation on write-up (yrs)", 15],
        ["Annual incremental depreciation", "=B7/B15"],
        [],
        ["Cash used", "='Deal Assumptions'!B13*'Deal Assumptions'!B20"],
        ["New debt raised", "=B18"],
        ["Stock issued ($)", "='Deal Assumptions'!B13*'Deal Assumptions'!B21"],
        ["New shares issued (mm)", "=B20/'Deal Assumptions'!B3"],
      ]),
      S("Accretion-Dilution", [
        ["PRO-FORMA EPS IMPACT ($mm except per share)"],
        [],
        ["Acquirer net income", "='Deal Assumptions'!B6"],
        ["Target net income", "='Deal Assumptions'!B16"],
        ["Cost synergies (phased)", "='Deal Assumptions'!B28*'Deal Assumptions'!B29"],
        [
          "Revenue synergy profit (phased)",
          "='Deal Assumptions'!B26*'Deal Assumptions'!B27*'Deal Assumptions'!B29",
        ],
        ["Interest on new debt", "=-'PPA & Goodwill'!B19*'Deal Assumptions'!B22"],
        ["Foregone interest on cash", "=-'PPA & Goodwill'!B18*'Deal Assumptions'!B24"],
        ["Incremental D&A", "=-('PPA & Goodwill'!B14+'PPA & Goodwill'!B16)"],
        ["Pre-tax adjustments", "=SUM(B5:B9)"],
        ["Tax on adjustments", "=-B10*'Deal Assumptions'!B23"],
        ["Pro-forma net income", "=B3+B4+B10+B11"],
        [],
        ["Acquirer shares", "='Deal Assumptions'!B4"],
        ["New shares issued", "='PPA & Goodwill'!B21"],
        ["Pro-forma shares", "=B14+B15"],
        [],
        ["Standalone acquirer EPS", "='Deal Assumptions'!B7"],
        ["Pro-forma EPS", "=B12/B16"],
        ["Accretion / (dilution) $", "=B19-B18"],
        ["Accretion / (dilution) %", "=B20/B18"],
        ["Verdict", '=IF(B20>0,"ACCRETIVE","DILUTIVE")'],
        [],
        ["Break-even synergies required", "=MAX(0,-B20*B16/(1-'Deal Assumptions'!B23))"],
      ]),
      S("Pro-Forma BS", [
        [
          "PRO-FORMA COMBINED BALANCE SHEET ($mm)",
          "Acquirer",
          "Target",
          "Adjustments",
          "Pro-forma",
        ],
        ["Cash", 620, 95, "=-'PPA & Goodwill'!B18", "=SUM(B2:D2)"],
        ["Accounts receivable", 480, 130, 0, "=SUM(B3:D3)"],
        ["Inventory", 310, 88, 0, "=SUM(B4:D4)"],
        ["Net PP&E", 1450, 390, "='PPA & Goodwill'!B7", "=SUM(B5:D5)"],
        ["Intangibles", 210, 40, "='PPA & Goodwill'!B8", "=SUM(B6:D6)"],
        ["Goodwill", 380, 60, "='PPA & Goodwill'!B11-C7", "=SUM(B7:D7)"],
        ["Total assets", "=SUM(B2:B7)", "=SUM(C2:C7)", "=SUM(D2:D7)", "=SUM(E2:E7)"],
        [],
        ["Accounts payable", 360, 105, 0, "=SUM(B10:D10)"],
        ["Debt", 900, 435, "='PPA & Goodwill'!B19", "=SUM(B11:D11)"],
        ["Deferred tax liability", 90, 25, "=-'PPA & Goodwill'!B9", "=SUM(B12:D12)"],
        ["Total liabilities", "=SUM(B10:B12)", "=SUM(C10:C12)", "=SUM(D10:D12)", "=SUM(E10:E12)"],
        ["Equity", "=B8-B13", "=C8-C13", "='PPA & Goodwill'!B20-C14", "=E8-E13"],
        ["Total liabilities & equity", "=B13+B14", "=C13+C14", "=D13+D14", "=E13+E14"],
        [],
        [
          "BALANCE CHECK (must be 0)",
          "=ROUND(B8-B15,2)",
          "=ROUND(C8-C15,2)",
          "",
          "=ROUND(E8-E15,2)",
        ],
        ["Status", '=IF(ABS(E17)<0.01,"BALANCED","ERROR")'],
      ]),
    ],
  },
  {
    id: "lbo",
    name: "Leveraged Buyout (LBO) Model",
    tier: "Advanced",
    blurb:
      "Deal structuring with multi-tranche debt waterfall (senior, mezzanine, high yield), IRR and MoIC sensitivity matrices.",
    features: ["Sources & uses", "Debt waterfall", "IRR & MoIC", "Return sensitivities"],
    prompt: "Add a management rollover, PIK toggle and dividend recap scenario to this LBO.",
    build: () => [
      S("Sources & Uses", [
        ["LBO — SOURCES & USES ($mm)"],
        [],
        ["Entry assumptions"],
        ["LTM EBITDA", 120],
        ["Entry multiple (EV/EBITDA)", 9],
        ["Enterprise value", "=B4*B5"],
        ["Transaction fees %", 0.025],
        ["Transaction fees", "=B6*B7"],
        ["Total uses", "=B6+B8"],
        [],
        ["Sources", "Turns of EBITDA", "Amount", "Rate", "% of total"],
        ["Senior term loan A", 2.5, "=$B$4*B12", 0.065, "=C12/$C$17"],
        ["Senior term loan B", 1.5, "=$B$4*B13", 0.075, "=C13/$C$17"],
        ["Mezzanine", 1, "=$B$4*B14", 0.11, "=C14/$C$17"],
        ["High yield notes", 0.75, "=$B$4*B15", 0.095, "=C15/$C$17"],
        ["Sponsor equity", "=(B9-SUM(C12:C15))/$B$4", "=B9-SUM(C12:C15)", "", "=C16/$C$17"],
        ["Total sources", "=SUM(B12:B16)", "=SUM(C12:C16)", "", "=SUM(E12:E16)"],
        [],
        ["Check: sources = uses", "=ROUND(C17-B9,2)"],
        ["Total leverage (turns)", "=SUM(B12:B15)"],
        ["Exit multiple", 9.5],
        ["Holding period (yrs)", 5],
        ["Cash sweep %", 1],
        ["Minimum cash", 15],
      ]),
      S("Operating Model", [
        ["LBO OPERATING MODEL ($mm)", ...YRS],
        ["Revenue", 420, ...cols.slice(1).map((_, i) => `=${cols[i]}2*(1+$B$18)`)],
        ["EBITDA", ...cols.map((c) => `=${c}2*$B$19`)],
        ["Depreciation & amortisation", ...cols.map((c) => `=-${c}2*0.045`)],
        ["EBIT", ...cols.map((c) => `=${c}3+${c}4`)],
        ["Cash interest", ...cols.map((c) => `=-'Debt Schedule'!${c}25`)],
        ["Pre-tax income", ...cols.map((c) => `=${c}5+${c}6`)],
        ["Taxes", ...cols.map((c) => `=-MAX(0,${c}7)*$B$20`)],
        ["Net income", ...cols.map((c) => `=${c}7+${c}8`)],
        ["Add back D&A", ...cols.map((c) => `=-${c}4`)],
        ["CapEx", ...cols.map((c) => `=-${c}2*0.035`)],
        ["Change in working capital", ...cols.map((c) => `=-${c}2*0.01`)],
        ["Free cash flow before debt service", ...cols.map((c) => `=SUM(${c}9:${c}12)`)],
        ["Mandatory amortisation", ...cols.map((c) => `=-'Debt Schedule'!${c}26`)],
        ["Cash available for sweep", ...cols.map((c) => `=${c}13+${c}14`)],
        [],
        ["ASSUMPTIONS"],
        ["Revenue growth", 0.07],
        ["EBITDA margin", "=('Sources & Uses'!B4/420)"],
        ["Tax rate", 0.25],
      ]),
      S("Debt Schedule", [
        ["DEBT WATERFALL ($mm)", ...YRS],
        ["SENIOR TERM LOAN A"],
        ["Opening", ...cols.map((c, i) => (i === 0 ? "='Sources & Uses'!C12" : `=${COL(i - 1)}6`))],
        [
          "Mandatory amortisation (10%)",
          ...cols.map((c) => `=-MIN(${c}3,'Sources & Uses'!$C$12*0.1)`),
        ],
        [
          "Cash sweep",
          ...cols.map(
            (c) => `=-MIN(${c}3+${c}4,MAX(0,'Operating Model'!${c}15*'Sources & Uses'!$B$23))`,
          ),
        ],
        ["Closing", ...cols.map((c) => `=${c}3+${c}4+${c}5`)],
        ["Interest", ...cols.map((c) => `=${c}3*'Sources & Uses'!$D$12`)],
        [],
        ["SENIOR TERM LOAN B"],
        [
          "Opening",
          ...cols.map((c, i) => (i === 0 ? "='Sources & Uses'!C13" : `=${COL(i - 1)}13`)),
        ],
        [
          "Mandatory amortisation (1%)",
          ...cols.map((c) => `=-MIN(${c}10,'Sources & Uses'!$C$13*0.01)`),
        ],
        [
          "Cash sweep",
          ...cols.map(
            (c) =>
              `=-MIN(${c}10+${c}11,MAX(0,'Operating Model'!${c}15*'Sources & Uses'!$B$23+${c}5))`,
          ),
        ],
        ["Closing", ...cols.map((c) => `=${c}10+${c}11+${c}12`)],
        ["Interest", ...cols.map((c) => `=${c}10*'Sources & Uses'!$D$13`)],
        [],
        ["MEZZANINE"],
        [
          "Opening",
          ...cols.map((c, i) => (i === 0 ? "='Sources & Uses'!C14" : `=${COL(i - 1)}18`)),
        ],
        ["Repayment", ...cols.map(() => 0)],
        ["Closing", ...cols.map((c) => `=${c}17+${c}18`)],
        ["Interest", ...cols.map((c) => `=${c}17*'Sources & Uses'!$D$14`)],
        [],
        ["HIGH YIELD NOTES"],
        [
          "Opening",
          ...cols.map((c, i) => (i === 0 ? "='Sources & Uses'!C15" : `=${COL(i - 1)}23`)),
        ],
        ["Closing", ...cols.map((c) => `=${c}23`)],
        [
          "Total cash interest",
          ...cols.map((c) => `=${c}7+${c}14+${c}20+${c}23*'Sources & Uses'!$D$15`),
        ],
        ["Total mandatory amortisation", ...cols.map((c) => `=-(${c}4+${c}11)`)],
        ["Total debt outstanding", ...cols.map((c) => `=${c}6+${c}13+${c}19+${c}24`)],
        ["Net debt / EBITDA", ...cols.map((c) => `=IFERROR(${c}27/'Operating Model'!${c}3,0)`)],
        [
          "Interest coverage (EBITDA / interest)",
          ...cols.map((c) => `=IFERROR('Operating Model'!${c}3/${c}25,0)`),
        ],
        ["Covenant check (leverage < 6.0x)", ...cols.map((c) => `=IF(${c}28<6,"PASS","BREACH")`)],
      ]),
      S("Returns", [
        ["LBO RETURNS"],
        [],
        ["Exit EBITDA (final year)", "='Operating Model'!F3"],
        ["Exit multiple", "='Sources & Uses'!B21"],
        ["Exit enterprise value", "=B3*B4"],
        ["Less: net debt at exit", "=-'Debt Schedule'!F27"],
        ["Exit equity value", "=B5+B6"],
        ["Sponsor equity invested", "='Sources & Uses'!C16"],
        ["MoIC (x)", "=IFERROR(B7/B8,0)"],
        ["Holding period (yrs)", "='Sources & Uses'!B22"],
        ["IRR", "=IFERROR(B9^(1/B10)-1,0)"],
        [],
        ["Cash flows", "=-'Sources & Uses'!C16", 0, 0, 0, 0, "=B7"],
        ["IRR (check on cash flows)", "=IFERROR(IRR(B13:G13),0)"],
        [],
        ["SENSITIVITY — IRR"],
        ["Rows: exit multiple   Columns: entry multiple"],
        ["IRR", 8, 8.5, 9, 9.5, 10],
        ...[8.5, 9, 9.5, 10, 10.5].map((ex, i) => {
          const row = 19 + i;
          return [
            ex,
            ...[1, 2, 3, 4, 5].map(
              (c) =>
                `=IFERROR((($A${row}*'Operating Model'!$F$3-'Debt Schedule'!$F$27)/(${String.fromCharCode(
                  65 + c,
                )}$18*'Sources & Uses'!$B$4+'Sources & Uses'!$B$8-SUM('Sources & Uses'!$C$12:$C$15)))^(1/$B$10)-1,0)`,
            ),
          ];
        }),
        [],
        ["SENSITIVITY — MoIC"],
        ["MoIC", 8, 8.5, 9, 9.5, 10],
        ...[8.5, 9, 9.5, 10, 10.5].map((ex, i) => {
          const row = 27 + i;
          return [
            ex,
            ...[1, 2, 3, 4, 5].map(
              (c) =>
                `=IFERROR(($A${row}*'Operating Model'!$F$3-'Debt Schedule'!$F$27)/(${String.fromCharCode(
                  65 + c,
                )}$26*'Sources & Uses'!$B$4+'Sources & Uses'!$B$8-SUM('Sources & Uses'!$C$12:$C$15)),0)`,
            ),
          ];
        }),
      ]),
    ],
  },
  {
    id: "saas-metrics",
    name: "SaaS & Subscription Analytics Engine",
    tier: "Advanced",
    blurb:
      "Cohort-based recurring revenue drivers with ARR/MRR, expansion, contraction, churn, LTV, CAC and the Magic Number.",
    features: ["MRR waterfall", "Cohort retention", "LTV / CAC", "Magic Number & NRR"],
    prompt: "Add a monthly logo vs revenue churn breakdown and a payback-period cohort chart.",
    build: () => {
      const months = ["M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9", "M10", "M11", "M12"];
      const mc = months.map((_, i) => String.fromCharCode(66 + i));
      return [
        S("MRR Waterfall", [
          ["MRR WATERFALL ($)", ...months],
          ["Opening MRR", 180000, ...mc.slice(1).map((_, i) => `=${mc[i]}8`)],
          ["New business MRR", ...mc.map((c, i) => (i === 0 ? 24000 : `=${mc[i - 1]}3*(1+$B$18)`))],
          ["Expansion MRR", ...mc.map((c) => `=${c}2*$B$19`)],
          ["Contraction MRR", ...mc.map((c) => `=-${c}2*$B$20`)],
          ["Churned MRR", ...mc.map((c) => `=-${c}2*$B$21`)],
          ["Net new MRR", ...mc.map((c) => `=SUM(${c}3:${c}6)`)],
          ["Closing MRR", ...mc.map((c) => `=${c}2+${c}7`)],
          ["ARR", ...mc.map((c) => `=${c}8*12`)],
          ["MoM growth %", ...mc.map((c, i) => (i === 0 ? "" : `=${c}8/${mc[i - 1]}8-1`))],
          ["Gross revenue retention", ...mc.map((c) => `=(${c}2+${c}5+${c}6)/${c}2`)],
          ["Net revenue retention", ...mc.map((c) => `=(${c}2+${c}4+${c}5+${c}6)/${c}2`)],
          [
            "Customers",
            ...mc.map((c, i) => (i === 0 ? 420 : `=${mc[i - 1]}13*(1-$B$21)+${c}3/$B$22`)),
          ],
          ["ARPA", ...mc.map((c) => `=${c}8/${c}13`)],
          [],
          [],
          ["ASSUMPTIONS"],
          ["New MRR growth per month", 0.06],
          ["Expansion rate", 0.021],
          ["Contraction rate", 0.008],
          ["Monthly gross churn rate", 0.014],
          ["ACV of a new customer (monthly)", 640],
        ]),
        S("Unit Economics", [
          ["SAAS UNIT ECONOMICS"],
          [],
          ["Closing ARR", "='MRR Waterfall'!M9"],
          ["Customers", "='MRR Waterfall'!M13"],
          ["ARPA (annual)", "=B3/B4"],
          ["Gross margin %", 0.82],
          ["Monthly gross churn", "='MRR Waterfall'!B21"],
          ["Annual logo churn", "=1-(1-B7)^12"],
          ["Average customer lifetime (months)", "=1/B7"],
          ["LTV", "=B5/12*B6*B9"],
          [],
          ["Sales & marketing spend (quarter)", 640000],
          ["New customers added (quarter)", "=SUM('MRR Waterfall'!K3:M3)/'MRR Waterfall'!B22"],
          ["CAC", "=B12/B13"],
          ["LTV / CAC", "=B10/B14"],
          ["CAC payback (months)", "=B14/(B5/12*B6)"],
          [],
          ["Net new ARR (quarter)", "=('MRR Waterfall'!M8-'MRR Waterfall'!J8)*12"],
          ["Magic Number", "=B18/B12"],
          ["Rule of 40", "='MRR Waterfall'!M10*12+0.12"],
          [],
          ["Health check — LTV/CAC > 3", '=IF(B15>3,"HEALTHY","REVIEW")'],
          ["Health check — Magic Number > 0.75", '=IF(B19>0.75,"EFFICIENT","INEFFICIENT")'],
        ]),
        S("Cohorts", [
          ["COHORT RETENTION (revenue retained %)"],
          [],
          ["Cohort", "Starting MRR", ...months.slice(0, 6)],
          ...["Jan-26", "Feb-26", "Mar-26", "Apr-26", "May-26", "Jun-26"].map((cohort, i) => {
            const row = 4 + i;
            const start = 24000 + i * 1600;
            return [
              cohort,
              start,
              ...Array.from({ length: 6 }, (_, m) =>
                m + i > 5
                  ? ""
                  : `=IF(${m}>=0,(1-'MRR Waterfall'!$B$21+'MRR Waterfall'!$B$19)^${m},"")`,
              ),
            ];
          }),
          [
            "Blended retention",
            "=SUM(B4:B9)",
            ...["C", "D", "E", "F", "G", "H"].map((c) => `=AVERAGE(${c}4:${c}9)`),
          ],
        ]),
      ];
    },
  },
  {
    id: "scenario-engine",
    name: "What-If & Sensitivity Scenario Engine",
    tier: "Advanced",
    blurb:
      "Base / Best / Bear scenario manager with native data-table logic to stress-test key drivers.",
    features: ["Scenario switch", "CHOOSE-driven drivers", "2-way data tables", "Goal-seek helper"],
    prompt: "Add a Monte-Carlo style ranked outcome table across 20 driver combinations.",
    build: () => [
      S("Scenario Manager", [
        ["SCENARIO MANAGER"],
        [],
        ["Active scenario (1 = Base, 2 = Best, 3 = Bear)", 1],
        ["Active scenario name", '=CHOOSE(B3,"Base","Best","Bear")'],
        [],
        ["Driver", "Base", "Best", "Bear", "Active"],
        ["Revenue growth", 0.1, 0.18, 0.02, "=CHOOSE($B$3,B7,C7,D7)"],
        ["Gross margin", 0.58, 0.62, 0.52, "=CHOOSE($B$3,B8,C8,D8)"],
        ["OpEx growth", 0.08, 0.06, 0.12, "=CHOOSE($B$3,B9,C9,D9)"],
        ["Price change", 0.03, 0.06, -0.02, "=CHOOSE($B$3,B10,C10,D10)"],
        ["Churn / attrition", 0.09, 0.06, 0.15, "=CHOOSE($B$3,B11,C11,D11)"],
        ["Discount rate (WACC)", 0.1, 0.09, 0.12, "=CHOOSE($B$3,B12,C12,D12)"],
        [],
        ["MODEL OUTPUT", "FY2026", "FY2027", "FY2028", "FY2029", "FY2030"],
        [
          "Revenue",
          24000,
          ...["C", "D", "E", "F"].map(
            (c, i) => `=${["B", "C", "D", "E"][i]}15*(1+$E$7+$E$10-$E$11)`,
          ),
        ],
        ["Gross profit", ...["B", "C", "D", "E", "F"].map((c) => `=${c}15*$E$8`)],
        [
          "Operating expenses",
          ...["B", "C", "D", "E", "F"].map((c, i) =>
            i === 0 ? `=-${c}15*0.34` : `=${["B", "C", "D", "E"][i - 1]}17*(1+$E$9)`,
          ),
        ],
        ["EBIT", ...["B", "C", "D", "E", "F"].map((c) => `=${c}16+${c}17`)],
        ["Free cash flow", ...["B", "C", "D", "E", "F"].map((c) => `=${c}18*0.75`)],
        ["Discount factor", ...["B", "C", "D", "E", "F"].map((c, i) => `=1/(1+$E$12)^${i + 1}`)],
        ["PV of FCF", ...["B", "C", "D", "E", "F"].map((c) => `=${c}19*${c}20`)],
        ["NPV", "=SUM(B21:F21)"],
        ["Terminal FCF multiple", 10],
        ["Total value", "=B22+F19*B23*F20"],
      ]),
      S("Data Tables", [
        ["TWO-WAY DATA TABLE — NPV"],
        ["Rows: revenue growth   Columns: gross margin"],
        [],
        ["NPV", 0.5, 0.54, 0.58, 0.62, 0.66],
        ...[0.02, 0.06, 0.1, 0.14, 0.18].map((g, i) => {
          const row = 5 + i;
          return [
            g,
            ...[1, 2, 3, 4, 5].map(
              (c) =>
                `=24000*(1+$A${row})*${String.fromCharCode(65 + c)}$4*0.75/(1+'Scenario Manager'!$E$12)*5`,
            ),
          ];
        }),
        [],
        ["ONE-WAY DATA TABLE — NPV vs WACC"],
        ["WACC", "NPV"],
        ...[0.08, 0.09, 0.1, 0.11, 0.12, 0.13].map((w, i) => [
          w,
          `=SUM('Scenario Manager'!$B$19:$F$19)/(1+A${13 + i})^3`,
        ]),
        [],
        ["GOAL SEEK HELPER"],
        ["Target NPV", 90000],
        ["Current NPV", "='Scenario Manager'!B22"],
        ["Gap", "=B21-B22"],
        ["Required extra growth (approx.)", "=B23/B22*'Scenario Manager'!E7"],
        ["Scenario verdict", '=IF(B22>=B21,"TARGET MET","SHORTFALL")'],
      ]),
    ],
  },
  {
    id: "etl-pipeline",
    name: "PowerPivot Data Pipeline & ETL Engine",
    tier: "Advanced",
    blurb:
      "Ingest raw csv / pdf / xml / dbf bank exports, normalise them and map into multi-dimensional pivot summaries.",
    features: [
      "Staging & mapping",
      "Normalised fact table",
      "Pivot summaries",
      "Data quality checks",
    ],
    prompt:
      "Map my uploaded raw transaction sheet into this ETL pipeline, normalise the columns and build the pivot summaries.",
    build: () => [
      S("01 Staging Raw", [
        ["RAW IMPORT (paste or upload csv / pdf / xml / dbf export here)"],
        [],
        ["raw_date", "raw_desc", "raw_amount", "raw_type", "source_file"],
        ["03/02/2026", "EFT CREDIT NORTHWIND LTD", "12,690.00", "CR", "bank_march.csv"],
        ["03/05/2026", "CHQ 4410 SUPPLIER A", "-67,300.00", "DR", "bank_march.csv"],
        ["03/11/2026", "EFT CREDIT ACME RETAIL", "8,450.00", "CR", "bank_march.csv"],
        ["03/15/2026", "DD PAYROLL RUN 03", "-47,950.00", "DR", "bank_march.csv"],
        ["03/19/2026", "SERVICE FEE", "-185.00", "DR", "bank_march.pdf"],
        ["03/23/2026", "EFT CREDIT GLOBEX", "15,200.00", "CR", "bank_march.xml"],
        ["03/28/2026", "INTEREST CREDIT", "96.00", "CR", "bank_march.dbf"],
        ["03/30/2026", "CHQ 4415 LANDLORD LLC", "-8,000.00", "DR", "bank_march.csv"],
      ]),
      S("02 Mapping Rules", [
        ["MAPPING RULES"],
        [],
        ["Keyword", "Category", "GL account", "Dimension"],
        ["NORTHWIND", "Receipts", "1100 Cash", "Customer"],
        ["ACME", "Receipts", "1100 Cash", "Customer"],
        ["GLOBEX", "Receipts", "1100 Cash", "Customer"],
        ["SUPPLIER", "Payables", "2000 AP", "Vendor"],
        ["PAYROLL", "Payroll", "6000 Salaries", "Internal"],
        ["FEE", "Bank charges", "6500 Fees", "Bank"],
        ["INTEREST", "Interest income", "4900 Interest", "Bank"],
        ["LANDLORD", "Facilities", "6200 Rent", "Vendor"],
      ]),
      S("03 Normalised Fact", [
        ["NORMALISED FACT TABLE"],
        [],
        [
          "txn_id",
          "date",
          "month",
          "description",
          "amount",
          "direction",
          "category",
          "gl_account",
          "source",
          "quality",
        ],
        ...Array.from({ length: 8 }, (_, i) => {
          const src = 4 + i;
          const r = 4 + i;
          return [
            `=TEXT(ROW()-3,"TXN-0000")`,
            `=DATEVALUE('01 Staging Raw'!A${src})`,
            `=TEXT(B${r},"YYYY-MM")`,
            `=PROPER('01 Staging Raw'!B${src})`,
            `=VALUE(SUBSTITUTE('01 Staging Raw'!C${src},",",""))`,
            `=IF(E${r}>=0,"Inflow","Outflow")`,
            `=IFERROR(INDEX('02 Mapping Rules'!$B$4:$B$11,MATCH(TRUE,ISNUMBER(SEARCH('02 Mapping Rules'!$A$4:$A$11,'01 Staging Raw'!B${src})),0)),"Unmapped")`,
            `=IFERROR(INDEX('02 Mapping Rules'!$C$4:$C$11,MATCH(TRUE,ISNUMBER(SEARCH('02 Mapping Rules'!$A$4:$A$11,'01 Staging Raw'!B${src})),0)),"9999 Suspense")`,
            `='01 Staging Raw'!E${src}`,
            `=IF(OR(G${r}="Unmapped",E${r}=0),"REVIEW","OK")`,
          ];
        }),
        ["Total", "", "", "", "=SUM(E4:E11)", "", "", "", "", ""],
      ]),
      S("04 Pivot Summaries", [
        ["PIVOT — AMOUNT BY CATEGORY"],
        [],
        ["Category", "Inflow", "Outflow", "Net", "% of gross"],
        ...[
          "Receipts",
          "Payables",
          "Payroll",
          "Bank charges",
          "Interest income",
          "Facilities",
          "Unmapped",
        ].map((cat, i) => {
          const r = 4 + i;
          return [
            cat,
            `=SUMIFS('03 Normalised Fact'!$E$4:$E$11,'03 Normalised Fact'!$G$4:$G$11,A${r},'03 Normalised Fact'!$F$4:$F$11,"Inflow")`,
            `=SUMIFS('03 Normalised Fact'!$E$4:$E$11,'03 Normalised Fact'!$G$4:$G$11,A${r},'03 Normalised Fact'!$F$4:$F$11,"Outflow")`,
            `=B${r}+C${r}`,
            `=IFERROR(ABS(D${r})/SUM(ABS($D$4:$D$10)),0)`,
          ];
        }),
        ["Total", "=SUM(B4:B10)", "=SUM(C4:C10)", "=SUM(D4:D10)", "=SUM(E4:E10)"],
        [],
        ["PIVOT — BY SOURCE FILE"],
        ["Source", "Transactions", "Net amount"],
        ...["bank_march.csv", "bank_march.pdf", "bank_march.xml", "bank_march.dbf"].map((s, i) => {
          const r = 15 + i;
          return [
            s,
            `=COUNTIF('03 Normalised Fact'!$I$4:$I$11,A${r})`,
            `=SUMIF('03 Normalised Fact'!$I$4:$I$11,A${r},'03 Normalised Fact'!$E$4:$E$11)`,
          ];
        }),
        ["Total", "=SUM(B15:B18)", "=SUM(C15:C18)"],
        [],
        ["DATA QUALITY"],
        ["Rows ingested", "=COUNTA('01 Staging Raw'!A4:A11)"],
        ["Rows normalised", "=COUNTA('03 Normalised Fact'!A4:A11)"],
        ["Rows needing review", "=COUNTIF('03 Normalised Fact'!$J$4:$J$11,\"REVIEW\")"],
        [
          "Load status",
          '=IF(B22=B23,IF(B24=0,"CLEAN LOAD","LOADED WITH EXCEPTIONS"),"ROW COUNT MISMATCH")',
        ],
      ]),
    ],
  },
];
