import { S, type FinancialTemplate } from "./types";

/**
 * Dashboard templates — built with a hidden Data/Calc tab feeding a clean
 * presentation tab, modern dynamic-array aggregation (GROUPBY / FILTER / UNIQUE),
 * sparkline-ready series and trend-arrow number formats.
 */

const TXN_ROWS: (string | number)[][] = [
  ["2026-01-05", "North", "Widgets", "Ava Chen", 18400, 12100, "Won"],
  ["2026-01-19", "South", "Gadgets", "Ben Ortiz", 9600, 6300, "Won"],
  ["2026-02-02", "North", "Services", "Ava Chen", 22750, 11200, "Won"],
  ["2026-02-14", "West", "Widgets", "Cara Diaz", 15300, 10400, "Lost"],
  ["2026-02-27", "East", "Gadgets", "Dev Patel", 27800, 18900, "Won"],
  ["2026-03-08", "South", "Services", "Ben Ortiz", 12450, 6100, "Won"],
  ["2026-03-16", "West", "Widgets", "Cara Diaz", 31200, 21400, "Won"],
  ["2026-03-29", "East", "Services", "Dev Patel", 8900, 4300, "Lost"],
  ["2026-04-11", "North", "Gadgets", "Ava Chen", 19750, 12600, "Won"],
  ["2026-04-24", "West", "Services", "Cara Diaz", 24600, 12300, "Won"],
];

export const DASHBOARD_TEMPLATES: FinancialTemplate[] = [
  {
    id: "sales-tracker-dashboard",
    name: "Simple Sales Tracker Dashboard",
    tier: "Dashboards",
    blurb:
      "KPI cards, top-5 products and weekly revenue series driven by SUMIFS/COUNTIFS off a clean transaction table.",
    features: ["KPI cards", "SUMIFS / COUNTIFS", "Top-N ranking", "Sparkline series"],
    prompt:
      "Turn this sales tracker into a dark-mode dashboard with a waterfall of quarter-over-quarter revenue movement.",
    build: () => [
      S("Dashboard", [
        ["SALES CONTROL CENTER", "", "", "Gridlines: off", "Calc tab: hidden"],
        [],
        ["KPI", "Value", "vs prior period", "Trend"],
        ["Total revenue", "=IFERROR(SUM(Data!E2:E11),0)", "=IFERROR(B4/SUM(Data!E2:E6)-1,0)", '=IF(C4>=0,"▲","▼")'],
        ["Gross profit", "=IFERROR(SUM(Data!F2:F11),0)", "=IFERROR(B5/B4,0)", '=IF(C5>=0.4,"▲","▼")'],
        ["Deals won", '=COUNTIF(Data!G2:G11,"Won")', "=IFERROR(B6/COUNTA(Data!G2:G11),0)", '=IF(C6>=0.6,"▲","▼")'],
        ["Average deal size", "=IFERROR(AVERAGE(Data!E2:E11),0)", "", ""],
        [],
        ["REVENUE BY REGION (single-formula aggregation)"],
        ["=IFERROR(GROUPBY(Data!B2:B11,Data!E2:E11,SUM,,0,-2),\"\")"],
        [],
        [],
        [],
        [],
        ["REVENUE BY PRODUCT & MONTH (PIVOTBY)"],
        ["=IFERROR(PIVOTBY(Data!C2:C11,TEXT(Data!A2:A11,\"mmm\"),Data!E2:E11,SUM,,0,,0),\"\")"],
        [],
        [],
        [],
        [],
        ["TOP 5 DEALS"],
        ["=IFERROR(TAKE(SORT(FILTER(CHOOSECOLS(Data!A2:G11,3,4,5),Data!G2:G11=\"Won\"),3,-1),5),\"\")"],
      ]),
      S("Data", [
        ["Date", "Region", "Product", "Rep", "Revenue", "Gross profit", "Stage"],
        ...TXN_ROWS,
      ]),
      S("Audit", [
        ["DASHBOARD CHECKS"],
        [],
        ["Check", "Result"],
        ["Revenue ties to source table", "=ABS(Dashboard!$B$4-SUM(Data!E2:E11))<0.01"],
        ["No blank regions", '=COUNTBLANK(Data!B2:B11)=0'],
        ["Gross margin plausible", "=AND(Dashboard!$C$5>0,Dashboard!$C$5<1)"],
        ["MASTER CHECK", "=AND(B4:B6)"],
      ]),
    ],
  },
  {
    id: "cfo-dashboard",
    name: "Financial Executive (CFO) Dashboard",
    tier: "Dashboards",
    blurb:
      "Revenue, EBITDA, OpEx and cash runway with a slicer-ready fact table, month/quarter filters and variance waterfall data.",
    features: ["EBITDA & runway", "Slicer-ready table", "Variance waterfall", "Trend arrows"],
    prompt:
      "Add a rolling 13-week cash forecast and a driver-based EBITDA bridge to this CFO dashboard.",
    build: () => [
      S("Dashboard", [
        ["CFO CONTROL CENTER"],
        [],
        ["Filter", "Selection", "(data validation dropdown)"],
        ["Period", "Q1", "Q1 / Q2 / FY"],
        ["Region", "All", "All / North / South / East / West"],
        [],
        ["KPI", "Actual", "Budget", "Variance", "Var %", "Flag"],
        ["Revenue", "=IFERROR(SUM(Facts!D2:D13),0)", "=IFERROR(SUM(Facts!E2:E13),0)", "=B8-C8", "=IFERROR(D8/C8,0)", '=IF(E8>=0,"ON TRACK","BELOW PLAN")'],
        ["Gross profit", "=IFERROR(B8*0.62,0)", "=IFERROR(C8*0.6,0)", "=B9-C9", "=IFERROR(D9/C9,0)", '=IF(E9>=0,"ON TRACK","BELOW PLAN")'],
        ["Operating expenses", "=IFERROR(SUM(Facts!F2:F13),0)", "=IFERROR(SUM(Facts!G2:G13),0)", "=C10-B10", "=IFERROR(D10/C10,0)", '=IF(B10<=C10,"ON TRACK","OVER BUDGET")'],
        ["EBITDA", "=B9-B10", "=C9-C10", "=B11-C11", "=IFERROR(D11/C11,0)", '=IF(E11>=0,"ON TRACK","BELOW PLAN")'],
        ["EBITDA margin", "=IFERROR(B11/B8,0)", "=IFERROR(C11/C8,0)", "=B12-C12", "", '=IF(B12>=0.2,"HEALTHY","WATCH")'],
        [],
        ["CASH"],
        ["Opening cash", 4200000],
        ["Net monthly burn", "=IFERROR(AVERAGE(Facts!H2:H13),0)"],
        ["Cash runway (months)", "=IFERROR(IF(B16>=0,999,-B15/B16),0)"],
        ["Runway status", '=IF(B17>18,"COMFORTABLE",IF(B17>9,"PLAN RAISE","URGENT"))'],
        [],
        ["MONTHLY TREND (dynamic array — feeds combo chart & sparklines)"],
        ["=IFERROR(GROUPBY(Facts!A2:A13,Facts!D2:D13,SUM,,0),\"\")"],
      ]),
      S("Facts", [
        ["Month", "Quarter", "Region", "Revenue", "Revenue budget", "OpEx", "OpEx budget", "Net cash flow"],
        ["Jan", "Q1", "North", 820000, 800000, 540000, 530000, -60000],
        ["Feb", "Q1", "North", 865000, 840000, 552000, 545000, -42000],
        ["Mar", "Q1", "North", 910000, 900000, 561000, 560000, -18000],
        ["Apr", "Q2", "North", 948000, 930000, 574000, 570000, 12000],
        ["Jan", "Q1", "South", 410000, 420000, 268000, 262000, -31000],
        ["Feb", "Q1", "South", 438000, 430000, 271000, 268000, -22000],
        ["Mar", "Q1", "South", 462000, 455000, 276000, 274000, -9000],
        ["Apr", "Q2", "South", 484000, 470000, 281000, 279000, 6000],
        ["Jan", "Q1", "West", 305000, 320000, 214000, 208000, -28000],
        ["Feb", "Q1", "West", 328000, 335000, 219000, 214000, -19000],
        ["Mar", "Q1", "West", 351000, 348000, 223000, 220000, -7000],
        ["Apr", "Q2", "West", 372000, 360000, 228000, 226000, 4000],
      ]),
      S("Audit", [
        ["CFO DASHBOARD CHECKS"],
        [],
        ["Check", "Result"],
        ["Revenue ties to facts", "=ABS(Dashboard!$B$8-SUM(Facts!D2:D13))<0.01"],
        ["OpEx ties to facts", "=ABS(Dashboard!$B$10-SUM(Facts!F2:F13))<0.01"],
        ["Runway calculated", "=Dashboard!$B$17>0"],
        ["MASTER CHECK", "=AND(B4:B6)"],
      ]),
    ],
  },
  {
    id: "project-status-dashboard",
    name: "Project Status & Gantt Tracker",
    tier: "Dashboards",
    blurb:
      "Task completion %, conditional-formatting Gantt bars, RAG status rollup and earned-value SPI/CPI metrics.",
    features: ["RAG status", "CF Gantt", "SPI / CPI", "Milestone rollup"],
    prompt: "Add critical-path highlighting and a resource-loading heatmap to this project dashboard.",
    build: () => [
      S("Dashboard", [
        ["PROJECT CONTROL CENTER"],
        [],
        ["KPI", "Value", "Status"],
        ["Tasks", "=COUNTA(Tasks!A2:A11)", ""],
        ["Complete", '=COUNTIF(Tasks!G2:G11,"Green")', '=IF(B5/B4>=0.6,"▲","▼")'],
        ["Overall % complete", "=IFERROR(SUMPRODUCT(Tasks!E2:E11,Tasks!F2:F11)/SUM(Tasks!E2:E11),0)", '=IF(B6>=0.5,"ON TRACK","BEHIND")'],
        ["Budget spent", "=IFERROR(SUM(Tasks!H2:H11),0)", ""],
        ["Planned value", "=IFERROR(SUMPRODUCT(Tasks!E2:E11,Tasks!I2:I11),0)", ""],
        ["Earned value", "=IFERROR(SUMPRODUCT(Tasks!E2:E11,Tasks!F2:F11),0)", ""],
        ["SPI (schedule)", "=IFERROR(B10/B9,0)", '=IF(B11>=1,"AHEAD","BEHIND")'],
        ["CPI (cost)", "=IFERROR(B10/B8,0)", '=IF(B12>=1,"UNDER","OVER")'],
        [],
        ["RAG SUMMARY"],
        ["=IFERROR(GROUPBY(Tasks!G2:G11,Tasks!E2:E11,COUNT,,0),\"\")"],
        [],
        [],
        [],
        ["AT-RISK TASKS (auto-filtered)"],
        ["=IFERROR(FILTER(CHOOSECOLS(Tasks!A2:I11,1,2,7),Tasks!G2:G11<>\"Green\",\"None at risk\"),\"\")"],
      ]),
      S("Tasks", [
        ["Task", "Owner", "Start", "Finish", "Weight", "% complete", "RAG", "Actual cost", "Planned %"],
        ["Discovery", "Ava", "2026-01-05", "2026-01-16", 5, 1, "Green", 42000, 1],
        ["Requirements", "Ben", "2026-01-19", "2026-02-06", 8, 1, "Green", 68000, 1],
        ["Architecture", "Cara", "2026-02-09", "2026-02-27", 10, 0.85, "Amber", 91000, 1],
        ["Build phase 1", "Dev", "2026-03-02", "2026-04-10", 20, 0.55, "Amber", 178000, 0.7],
        ["Build phase 2", "Dev", "2026-04-13", "2026-05-22", 20, 0.15, "Green", 62000, 0.2],
        ["Integrations", "Ava", "2026-05-04", "2026-06-05", 12, 0.05, "Red", 28000, 0.15],
        ["QA & UAT", "Ben", "2026-06-08", "2026-07-03", 12, 0, "Green", 0, 0],
        ["Training", "Cara", "2026-07-06", "2026-07-17", 5, 0, "Green", 0, 0],
        ["Go live", "Dev", "2026-07-20", "2026-07-24", 5, 0, "Green", 0, 0],
        ["Hypercare", "Ava", "2026-07-27", "2026-08-21", 3, 0, "Green", 0, 0],
      ]),
      S("Audit", [
        ["PROJECT CHECKS"],
        [],
        ["Check", "Result"],
        ["Weights sum to 100", "=SUM(Tasks!E2:E11)=100"],
        ["All completion between 0 and 1", "=AND(MIN(Tasks!F2:F11)>=0,MAX(Tasks!F2:F11)<=1)"],
        ["Finish after start on every task", "=SUMPRODUCT(--(Tasks!D2:D11<Tasks!C2:C11))=0"],
        ["MASTER CHECK", "=AND(B4:B6)"],
      ]),
    ],
  },
  {
    id: "dynamic-array-dashboard",
    name: "Dynamic Array Engine Dashboard (no PivotTables)",
    tier: "Dashboards",
    blurb:
      "Fully spill-based dashboard using GROUPBY, PIVOTBY, PERCENTOF, FILTER, UNIQUE, SORT, MAP and REDUCE — refreshes instantly on data drop.",
    features: ["GROUPBY + PERCENTOF", "FILTER / UNIQUE / SORT", "MAP / REDUCE / SCAN", "Zero PivotTables"],
    prompt:
      "Rebuild every summary on this dashboard with LAMBDA helpers stored in the Name Manager and add a REGEXEXTRACT cleaning step.",
    build: () => [
      S("Dashboard", [
        ["DYNAMIC ARRAY CONTROL CENTER — every block is one formula"],
        [],
        ["1. REVENUE BY REGION WITH PERCENT OF TOTAL"],
        ["=IFERROR(GROUPBY(Data!B2:B11,Data!E2:E11,HSTACK(SUM,PERCENTOF),,0,-2),\"\")"],
        [],
        [],
        [],
        [],
        ["2. PRODUCT x MONTH MATRIX"],
        ["=IFERROR(PIVOTBY(Data!C2:C11,TEXT(Data!A2:A11,\"mmm\"),Data!E2:E11,SUM,,0,,0),\"\")"],
        [],
        [],
        [],
        [],
        ["3. UNIQUE REPS SORTED BY MARGIN (MAP + LAMBDA)"],
        [
          "=IFERROR(LET(reps,SORT(UNIQUE(Data!D2:D11)),m,MAP(reps,LAMBDA(r,SUMIF(Data!$D$2:$D$11,r,Data!$F$2:$F$11)/MAX(1,SUMIF(Data!$D$2:$D$11,r,Data!$E$2:$E$11)))),SORT(HSTACK(reps,m),2,-1)),\"\")",
        ],
        [],
        [],
        [],
        [],
        ["4. RUNNING REVENUE (SCAN)"],
        ["=IFERROR(SCAN(0,Data!E2:E11,LAMBDA(a,v,a+v)),\"\")"],
        [],
        ["5. TOTAL VIA REDUCE"],
        ["=IFERROR(REDUCE(0,Data!E2:E11,LAMBDA(a,v,a+v)),0)"],
        [],
        ["6. CLEANED REP IDS (REGEXEXTRACT)"],
        ["=IFERROR(REGEXEXTRACT(Data!D2:D11,\"^\\\\w+\"),\"\")"],
      ]),
      S("Data", [
        ["Date", "Region", "Product", "Rep", "Revenue", "Gross profit", "Stage"],
        ...TXN_ROWS,
      ]),
      S("Audit", [
        ["SPILL & ERROR CHECKS"],
        [],
        ["Check", "Result"],
        ["Region aggregation spilled", "=IFERROR(ROWS(Dashboard!$A$4#)>0,FALSE)"],
        ["Reduce total ties to SUM", "=ABS(Dashboard!$A$28-SUM(Data!E2:E11))<0.01"],
        ["No spill collisions", "=IFERROR(SUM(--ISERROR(Dashboard!$A$4#))=0,FALSE)"],
        ["MASTER CHECK", "=AND(B4:B6)"],
      ]),
    ],
  },
  {
    id: "bi-star-schema-dashboard",
    name: "Enterprise BI Star Schema (Power Pivot + DAX)",
    tier: "Dashboards",
    blurb:
      "Fact and dimension tables laid out for the Excel Data Model with a DAX measure library including time intelligence and rolling averages.",
    features: ["Star schema", "DAX measures", "Time intelligence", "Relationship map"],
    prompt:
      "Add SAMEPERIODLASTYEAR variance measures by product category and a DAX-driven ABC customer segmentation.",
    build: () => [
      S("Dashboard", [
        ["ENTERPRISE BI CONTROL CENTER (Data Model driven)"],
        [],
        ["Measure", "Value", "Notes"],
        ["Total Sales", "=IFERROR(SUM(FactSales!E2:E13),0)", "DAX: SUM(FactSales[Amount])"],
        ["Sales YTD", "=IFERROR(SUM(FactSales!E2:E13),0)", "DAX: TOTALYTD([Total Sales], DimDate[Date])"],
        ["Sales LY", "=IFERROR(SUM(FactSales!F2:F13),0)", "DAX: CALCULATE([Total Sales], SAMEPERIODLASTYEAR(DimDate[Date]))"],
        ["YoY growth", "=IFERROR(B4/B6-1,0)", "DAX: DIVIDE([Total Sales]-[Sales LY],[Sales LY])"],
        ["Rolling 3-month avg", "=IFERROR(AVERAGE(OFFSET(FactSales!E2,COUNT(FactSales!E2:E13)-3,0,3,1)),0)", "DAX: AVERAGEX(DATESINPERIOD(...))"],
        [],
        ["SALES BY CATEGORY (RELATED across dimensions)"],
        ["=IFERROR(GROUPBY(FactSales!C2:C13,FactSales!E2:E13,SUM,,0,-2),\"\")"],
      ]),
      S("FactSales", [
        ["Date key", "Customer key", "Category", "Product key", "Amount", "Amount LY", "Quantity"],
        ["2026-01-31", "C001", "Hardware", "P100", 182000, 164000, 340],
        ["2026-01-31", "C002", "Software", "P200", 96500, 88000, 120],
        ["2026-02-28", "C001", "Hardware", "P101", 174300, 158200, 318],
        ["2026-02-28", "C003", "Services", "P300", 121000, 104500, 60],
        ["2026-03-31", "C002", "Software", "P201", 138900, 121400, 165],
        ["2026-03-31", "C004", "Hardware", "P100", 205600, 187300, 392],
        ["2026-04-30", "C003", "Services", "P301", 114700, 99100, 55],
        ["2026-04-30", "C001", "Software", "P200", 102400, 92800, 128],
        ["2026-05-31", "C004", "Hardware", "P102", 218300, 196500, 405],
        ["2026-05-31", "C002", "Services", "P300", 127500, 111200, 62],
        ["2026-06-30", "C003", "Software", "P201", 144200, 128700, 172],
        ["2026-06-30", "C001", "Hardware", "P101", 191800, 172400, 352],
      ]),
      S("DimCustomer", [
        ["Customer key", "Customer", "Segment", "Region", "Country"],
        ["C001", "Aurora Industrial", "Enterprise", "North", "USA"],
        ["C002", "Beacon Software", "Mid-market", "West", "USA"],
        ["C003", "Cygnus Logistics", "Enterprise", "East", "Canada"],
        ["C004", "Delta Manufacturing", "Enterprise", "South", "Mexico"],
      ]),
      S("DAX Measures", [
        ["DAX MEASURE LIBRARY — paste into Power Pivot"],
        [],
        ["Measure", "Expression"],
        ["Total Sales", "SUM ( FactSales[Amount] )"],
        ["Total Quantity", "SUM ( FactSales[Quantity] )"],
        ["Average Price", "DIVIDE ( [Total Sales], [Total Quantity] )"],
        ["Sales YTD", "TOTALYTD ( [Total Sales], DimDate[Date] )"],
        ["Sales MTD", "TOTALMTD ( [Total Sales], DimDate[Date] )"],
        ["Sales LY", "CALCULATE ( [Total Sales], SAMEPERIODLASTYEAR ( DimDate[Date] ) )"],
        ["YoY %", "DIVIDE ( [Total Sales] - [Sales LY], [Sales LY] )"],
        ["Rolling 3M Avg", "AVERAGEX ( DATESINPERIOD ( DimDate[Date], MAX ( DimDate[Date] ), -3, MONTH ), [Total Sales] )"],
        ["Enterprise Sales", "CALCULATE ( [Total Sales], DimCustomer[Segment] = \"Enterprise\" )"],
        ["Sales Rank", "RANKX ( ALL ( DimCustomer[Customer] ), [Total Sales] )"],
        [],
        ["RELATIONSHIPS"],
        ["From", "To", "Cardinality"],
        ["FactSales[Customer key]", "DimCustomer[Customer key]", "Many-to-one"],
        ["FactSales[Date key]", "DimDate[Date]", "Many-to-one"],
      ]),
      S("Audit", [
        ["DATA MODEL CHECKS"],
        [],
        ["Check", "Result"],
        ["No orphan customer keys", "=SUMPRODUCT(--ISNA(MATCH(FactSales!B2:B13,DimCustomer!A2:A5,0)))=0"],
        ["Amounts positive", "=MIN(FactSales!E2:E13)>0"],
        ["YoY calculable", "=ISNUMBER(Dashboard!$B$7)"],
        ["MASTER CHECK", "=AND(B4:B6)"],
      ]),
    ],
  },
  {
    id: "forecasting-dashboard",
    name: "Predictive Forecasting Control Center",
    tier: "Dashboards",
    blurb:
      "FORECAST.ETS seasonality engine with confidence-interval bands, forecast accuracy scoring and IBCS-style variance columns.",
    features: ["FORECAST.ETS", "Confidence bands", "Seasonality detection", "MAPE accuracy"],
    prompt:
      "Extend this forecast to weekly granularity, add inventory depletion projection and a lollipop variance chart layout.",
    build: () => [
      S("Dashboard", [
        ["PREDICTIVE FORECASTING CONTROL CENTER"],
        [],
        ["Setting", "Value"],
        ["Confidence level", 0.95],
        ["Seasonality (0 = auto)", 0],
        ["Forecast horizon (months)", 6],
        [],
        ["ACCURACY"],
        ["Detected seasonality", "=IFERROR(FORECAST.ETS.SEASONALITY(History!B2:B25,History!A2:A25),0)"],
        ["MAPE (backtest)", "=IFERROR(AVERAGE(ABS(History!C2:C25-History!B2:B25)/History!B2:B25),0)"],
        ["Forecast quality", '=IF(B10<0.05,"EXCELLENT",IF(B10<0.12,"GOOD","REVIEW"))'],
        [],
        ["FORECAST WITH CONFIDENCE BANDS"],
        ["Month", "Forecast", "Confidence interval", "Lower band", "Upper band"],
        ...Array.from({ length: 6 }, (_, i) => {
          const r = 15 + i;
          return [
            `=EDATE(MAX(History!$A$2:$A$25),${i + 1})`,
            `=IFERROR(FORECAST.ETS(A${r},History!$B$2:$B$25,History!$A$2:$A$25,$B$5,1),0)`,
            `=IFERROR(FORECAST.ETS.CONFINT(A${r},History!$B$2:$B$25,History!$A$2:$A$25,$B$4,$B$5,1),0)`,
            `=B${r}-C${r}`,
            `=B${r}+C${r}`,
          ];
        }),
        [],
        ["Total forecast horizon", "=IFERROR(SUM(B15:B20),0)"],
        ["Implied run rate (annualised)", "=IFERROR(B22/6*12,0)"],
      ]),
      S("History", [
        ["Month", "Actual revenue", "Fitted"],
        ...Array.from({ length: 24 }, (_, i) => {
          const base = 620000 + i * 14500;
          const seasonal = Math.round(Math.sin(((i % 12) / 12) * Math.PI * 2) * 48000);
          const r = 2 + i;
          return [
            `=DATE(2024,${(i % 12) + 1},1)+0*${Math.floor(i / 12)}`,
            base + seasonal,
            `=IFERROR(FORECAST.LINEAR(A${r},$B$2:$B$25,$A$2:$A$25),0)`,
          ];
        }),
      ]),
      S("Audit", [
        ["FORECAST CHECKS"],
        [],
        ["Check", "Result"],
        ["24 history points present", "=COUNT(History!B2:B25)=24"],
        ["Forecast returns numbers", "=ISNUMBER(Dashboard!$B$15)"],
        ["Bands ordered correctly", "=SUMPRODUCT(--(Dashboard!D15:D20>Dashboard!E15:E20))=0"],
        ["MASTER CHECK", "=AND(B4:B6)"],
      ]),
    ],
  },
];
