import { budgetTracker, kpiDashboard, projectionModel, type DashSpec, type ProjSpec, type BudgetSpec } from "./kits.ts";
import type { FinancialTemplate } from "./types.ts";

/** Ratio helper: safe division of two measures. */
const div = (a: string, b: string, label: string, lowerBetter = false) => ({
  label,
  f: (m: Record<string, string>) => `${m[a]}/${m[b]}`,
  lowerBetter,
});
const margin = (rev: string, cost: string, label = "Gross margin %") => ({
  label,
  f: (m: Record<string, string>) => `(${m[rev]}-${m[cost]})/${m[rev]}`,
});

const DASHBOARDS: DashSpec[] = [
  {
    id: "retail-store-dashboard", name: "Retail Store Performance Dashboard", industry: "Retail",
    dimA: ["Store", ["Downtown", "Mall", "Airport", "Suburb"]], dimB: ["Category", ["Apparel", "Footwear", "Accessories"]],
    measures: [{ name: "Net sales", base: 42000 }, { name: "Cost of goods", of: "Net sales", frac: [0.5, 0.6] }, { name: "Transactions", base: 950, int: true }, { name: "Units sold", base: 2100, int: true }],
    ratios: [margin("Net sales", "Cost of goods"), div("Net sales", "Transactions", "Average basket"), div("Units sold", "Transactions", "Units per transaction")],
    lowerBetter: ["Cost of goods"],
  },
  {
    id: "ecommerce-dashboard", name: "E-commerce Funnel & Revenue Dashboard", industry: "E-commerce",
    dimA: ["Channel", ["Organic", "Paid search", "Social", "Email"]], dimB: ["Device", ["Mobile", "Desktop", "Tablet"]],
    measures: [{ name: "Sessions", base: 48000, int: true }, { name: "Orders", of: "Sessions", frac: [0.018, 0.034], int: true }, { name: "Revenue", base: 61000 }, { name: "Ad spend", of: "Revenue", frac: [0.08, 0.2] }],
    ratios: [div("Orders", "Sessions", "Conversion rate"), div("Revenue", "Orders", "Average order value"), div("Revenue", "Ad spend", "ROAS (x)")],
    lowerBetter: ["Ad spend"],
  },
  {
    id: "restaurant-dashboard", name: "Restaurant Operations Dashboard", industry: "Restaurant",
    dimA: ["Location", ["Main St", "Harbor", "Uptown"]], dimB: ["Daypart", ["Lunch", "Dinner", "Brunch"]],
    measures: [{ name: "Food & beverage sales", base: 78000 }, { name: "Food cost", of: "Food & beverage sales", frac: [0.27, 0.34] }, { name: "Labor cost", of: "Food & beverage sales", frac: [0.26, 0.33] }, { name: "Covers", base: 3600, int: true }],
    ratios: [div("Food cost", "Food & beverage sales", "Food cost %", true), div("Labor cost", "Food & beverage sales", "Labor cost %", true), div("Food & beverage sales", "Covers", "Average check")],
    lowerBetter: ["Food cost", "Labor cost"],
  },
  {
    id: "hotel-dashboard", name: "Hotel Revenue Management Dashboard", industry: "Hospitality",
    dimA: ["Property", ["City Center", "Beach Resort", "Airport Inn"]], dimB: ["Segment", ["Leisure", "Corporate", "Group"]],
    measures: [{ name: "Rooms available", base: 4500, int: true }, { name: "Rooms sold", of: "Rooms available", frac: [0.62, 0.88], int: true }, { name: "Room revenue", base: 520000 }, { name: "Other revenue", of: "Room revenue", frac: [0.15, 0.3] }],
    ratios: [div("Rooms sold", "Rooms available", "Occupancy %"), div("Room revenue", "Rooms sold", "ADR"), div("Room revenue", "Rooms available", "RevPAR")],
  },
  {
    id: "hospital-dashboard", name: "Hospital Operations Dashboard", industry: "Healthcare",
    dimA: ["Department", ["Emergency", "Surgery", "Cardiology", "Pediatrics"]], dimB: ["Payer", ["Medicare", "Commercial", "Medicaid"]],
    measures: [{ name: "Patient revenue", base: 1250000 }, { name: "Operating cost", of: "Patient revenue", frac: [0.78, 0.94] }, { name: "Admissions", base: 420, int: true }, { name: "Patient days", of: "Admissions", frac: [3.6, 5.2], int: true }],
    ratios: [margin("Patient revenue", "Operating cost", "Operating margin %"), div("Patient days", "Admissions", "Average length of stay", true), div("Patient revenue", "Admissions", "Revenue per admission")],
    lowerBetter: ["Operating cost"],
  },
  {
    id: "clinic-dashboard", name: "Medical Clinic Practice Dashboard", industry: "Outpatient care",
    dimA: ["Provider", ["Dr. Patel", "Dr. Kim", "Dr. Alvarez", "NP Jones"]], dimB: ["Visit type", ["New patient", "Follow-up", "Telehealth"]],
    measures: [{ name: "Visits", base: 380, int: true }, { name: "Collections", base: 52000 }, { name: "Charges", of: "Collections", frac: [1.25, 1.55] }, { name: "No-shows", of: "Visits", frac: [0.04, 0.11], int: true }],
    ratios: [div("Collections", "Charges", "Collection rate"), div("Collections", "Visits", "Revenue per visit"), div("No-shows", "Visits", "No-show rate", true)],
    lowerBetter: ["No-shows"],
  },
  {
    id: "saas-metrics-dashboard", name: "SaaS Growth Metrics Dashboard", industry: "SaaS",
    dimA: ["Plan", ["Starter", "Growth", "Enterprise"]], dimB: ["Region", ["NA", "EMEA", "APAC"]],
    measures: [{ name: "New MRR", base: 38000 }, { name: "Churned MRR", of: "New MRR", frac: [0.12, 0.35] }, { name: "New customers", base: 140, int: true }, { name: "Sales & marketing spend", of: "New MRR", frac: [1.8, 3.2] }],
    ratios: [margin("New MRR", "Churned MRR", "Net new MRR ratio"), div("Sales & marketing spend", "New customers", "CAC", true), div("New MRR", "New customers", "New MRR per customer")],
    lowerBetter: ["Churned MRR", "Sales & marketing spend"],
  },
  {
    id: "telecom-dashboard", name: "Telecom Subscriber Dashboard", industry: "Telecom",
    dimA: ["Market", ["Metro", "Suburban", "Rural"]], dimB: ["Product", ["Mobile", "Broadband", "TV"]],
    measures: [{ name: "Subscribers", base: 185000, int: true }, { name: "Service revenue", base: 9200000 }, { name: "Disconnects", of: "Subscribers", frac: [0.008, 0.02], int: true }, { name: "Network cost", of: "Service revenue", frac: [0.22, 0.31] }],
    ratios: [div("Service revenue", "Subscribers", "ARPU"), div("Disconnects", "Subscribers", "Monthly churn", true), div("Network cost", "Service revenue", "Network cost %", true)],
    lowerBetter: ["Disconnects", "Network cost"],
  },
  {
    id: "airline-dashboard", name: "Airline Route Performance Dashboard", industry: "Aviation",
    dimA: ["Route", ["NYC-LAX", "CHI-MIA", "SEA-DEN", "BOS-ATL"]], dimB: ["Cabin", ["Economy", "Premium", "Business"]],
    measures: [{ name: "Seat miles available", base: 42000000, int: true }, { name: "Revenue passenger miles", of: "Seat miles available", frac: [0.74, 0.9], int: true }, { name: "Passenger revenue", base: 7400000 }, { name: "Operating cost", of: "Passenger revenue", frac: [0.82, 0.97] }],
    ratios: [div("Revenue passenger miles", "Seat miles available", "Load factor"), div("Passenger revenue", "Seat miles available", "RASM"), div("Operating cost", "Seat miles available", "CASM", true)],
    lowerBetter: ["Operating cost"],
  },
  {
    id: "fleet-logistics-dashboard", name: "Fleet & Logistics Dashboard", industry: "Logistics",
    dimA: ["Depot", ["Chicago", "Dallas", "Atlanta", "Phoenix"]], dimB: ["Service", ["Same-day", "Next-day", "Freight"]],
    measures: [{ name: "Shipments", base: 5200, int: true }, { name: "On-time deliveries", of: "Shipments", frac: [0.88, 0.98], int: true }, { name: "Freight revenue", base: 410000 }, { name: "Fuel cost", of: "Freight revenue", frac: [0.14, 0.22] }],
    ratios: [div("On-time deliveries", "Shipments", "On-time %"), div("Freight revenue", "Shipments", "Revenue per shipment"), div("Fuel cost", "Freight revenue", "Fuel cost %", true)],
    lowerBetter: ["Fuel cost"],
  },
  {
    id: "manufacturing-oee-dashboard", name: "Manufacturing Plant OEE Dashboard", industry: "Manufacturing",
    dimA: ["Line", ["Line 1", "Line 2", "Line 3", "Line 4"]], dimB: ["Shift", ["Day", "Swing", "Night"]],
    measures: [{ name: "Planned hours", base: 620, int: true }, { name: "Run hours", of: "Planned hours", frac: [0.78, 0.93] }, { name: "Units produced", base: 48000, int: true }, { name: "Defective units", of: "Units produced", frac: [0.006, 0.03], int: true }],
    ratios: [div("Run hours", "Planned hours", "Availability"), { label: "First-pass yield", f: (m) => `(${m["Units produced"]}-${m["Defective units"]})/${m["Units produced"]}` }, div("Units produced", "Run hours", "Units per run hour")],
    lowerBetter: ["Defective units"],
  },
  {
    id: "construction-projects-dashboard", name: "Construction Project Portfolio Dashboard", industry: "Construction",
    dimA: ["Project", ["Riverside Tower", "Oak Mall", "Hwy 9 Bridge", "Civic Center"]], dimB: ["Phase", ["Foundation", "Structure", "Fit-out"]],
    measures: [{ name: "Earned value", base: 860000 }, { name: "Actual cost", of: "Earned value", frac: [0.9, 1.12] }, { name: "Planned value", of: "Earned value", frac: [0.95, 1.1] }, { name: "Safety incidents", base: 1.4, int: true }],
    ratios: [div("Earned value", "Actual cost", "Cost performance index"), div("Earned value", "Planned value", "Schedule performance index"), { label: "Cost variance", f: (m) => `${m["Earned value"]}-${m["Actual cost"]}` }],
    lowerBetter: ["Actual cost", "Safety incidents"],
  },
  {
    id: "property-leasing-dashboard", name: "Commercial Property Leasing Dashboard", industry: "Real estate",
    dimA: ["Building", ["One Market", "Park Plaza", "Tech Hub"]], dimB: ["Use", ["Office", "Retail", "Lab"]],
    measures: [{ name: "Leasable sq ft", base: 210000, int: true }, { name: "Leased sq ft", of: "Leasable sq ft", frac: [0.78, 0.96], int: true }, { name: "Rental income", base: 690000 }, { name: "Operating expenses", of: "Rental income", frac: [0.28, 0.38] }],
    ratios: [div("Leased sq ft", "Leasable sq ft", "Occupancy %"), margin("Rental income", "Operating expenses", "NOI margin %"), div("Rental income", "Leased sq ft", "Rent per leased sq ft")],
    lowerBetter: ["Operating expenses"],
  },
  {
    id: "bank-branch-dashboard", name: "Bank Branch Performance Dashboard", industry: "Retail banking",
    dimA: ["Branch", ["Central", "Westside", "Harbor", "Airport"]], dimB: ["Product", ["Deposits", "Mortgages", "Cards"]],
    measures: [{ name: "Net interest income", base: 340000 }, { name: "Fee income", of: "Net interest income", frac: [0.2, 0.4] }, { name: "Operating expense", of: "Net interest income", frac: [0.55, 0.75] }, { name: "New accounts", base: 260, int: true }],
    ratios: [{ label: "Efficiency ratio", f: (m) => `${m["Operating expense"]}/(${m["Net interest income"]}+${m["Fee income"]})`, lowerBetter: true }, { label: "Fee share of income", f: (m) => `${m["Fee income"]}/(${m["Net interest income"]}+${m["Fee income"]})` }, div("Operating expense", "New accounts", "Cost per new account", true)],
    lowerBetter: ["Operating expense"],
  },
  {
    id: "insurance-claims-dashboard", name: "Insurance Claims & Loss Ratio Dashboard", industry: "Insurance",
    dimA: ["Line of business", ["Auto", "Home", "Commercial", "Life"]], dimB: ["Region", ["North", "South", "West"]],
    measures: [{ name: "Earned premium", base: 2400000 }, { name: "Incurred losses", of: "Earned premium", frac: [0.55, 0.75] }, { name: "Expenses", of: "Earned premium", frac: [0.22, 0.31] }, { name: "Claims reported", base: 820, int: true }],
    ratios: [div("Incurred losses", "Earned premium", "Loss ratio", true), { label: "Combined ratio", f: (m) => `(${m["Incurred losses"]}+${m["Expenses"]})/${m["Earned premium"]}`, lowerBetter: true }, div("Incurred losses", "Claims reported", "Average claim severity", true)],
    lowerBetter: ["Incurred losses", "Expenses", "Claims reported"],
  },
  {
    id: "marketing-campaign-dashboard", name: "Marketing Campaign ROI Dashboard", industry: "Marketing",
    dimA: ["Campaign", ["Spring launch", "Webinar series", "Retargeting", "Partner co-op"]], dimB: ["Channel", ["Paid social", "Search", "Display"]],
    measures: [{ name: "Spend", base: 24000 }, { name: "Impressions", base: 1600000, int: true }, { name: "Leads", base: 640, int: true }, { name: "Pipeline", of: "Spend", frac: [3, 7] }],
    ratios: [div("Spend", "Leads", "Cost per lead", true), div("Pipeline", "Spend", "Pipeline ROI (x)"), { label: "CPM", f: (m) => `${m["Spend"]}/${m["Impressions"]}*1000`, lowerBetter: true }],
    lowerBetter: ["Spend"],
  },
  {
    id: "hr-headcount-dashboard", name: "HR Headcount & Attrition Dashboard", industry: "Human resources",
    dimA: ["Department", ["Engineering", "Sales", "Operations", "Finance"]], dimB: ["Location", ["HQ", "Remote", "Regional"]],
    measures: [{ name: "Headcount", base: 120, int: true }, { name: "Hires", of: "Headcount", frac: [0.01, 0.05], int: true }, { name: "Leavers", of: "Headcount", frac: [0.005, 0.03], int: true }, { name: "Payroll cost", base: 980000 }],
    ratios: [div("Leavers", "Headcount", "Monthly attrition", true), div("Payroll cost", "Headcount", "Cost per employee"), div("Hires", "Leavers", "Hire-to-leaver ratio")],
    lowerBetter: ["Leavers"],
  },
  {
    id: "call-center-dashboard", name: "Contact Center Service Dashboard", industry: "Customer service",
    dimA: ["Team", ["Billing", "Tech support", "Sales", "Retention"]], dimB: ["Channel", ["Phone", "Chat", "Email"]],
    measures: [{ name: "Contacts handled", base: 7400, int: true }, { name: "Answered in SLA", of: "Contacts handled", frac: [0.72, 0.93], int: true }, { name: "Handle minutes", of: "Contacts handled", frac: [5.5, 8.5], int: true }, { name: "Escalations", of: "Contacts handled", frac: [0.02, 0.07], int: true }],
    ratios: [div("Answered in SLA", "Contacts handled", "Service level %"), div("Handle minutes", "Contacts handled", "Average handle time (min)", true), div("Escalations", "Contacts handled", "Escalation rate", true)],
    lowerBetter: ["Escalations"],
  },
  {
    id: "it-helpdesk-dashboard", name: "IT Service Desk Dashboard", industry: "IT operations",
    dimA: ["Queue", ["Hardware", "Access", "Network", "Applications"]], dimB: ["Priority", ["P1", "P2", "P3"]],
    measures: [{ name: "Tickets opened", base: 560, int: true }, { name: "Tickets resolved", of: "Tickets opened", frac: [0.86, 1.02], int: true }, { name: "Resolved first contact", of: "Tickets resolved", frac: [0.55, 0.78], int: true }, { name: "SLA breaches", of: "Tickets opened", frac: [0.02, 0.08], int: true }],
    ratios: [div("Tickets resolved", "Tickets opened", "Resolution rate"), div("Resolved first contact", "Tickets resolved", "First-contact resolution"), div("SLA breaches", "Tickets opened", "SLA breach rate", true)],
    lowerBetter: ["SLA breaches"],
  },
  {
    id: "university-dashboard", name: "University Enrollment & Finance Dashboard", industry: "Higher education",
    dimA: ["College", ["Business", "Engineering", "Arts", "Sciences"]], dimB: ["Level", ["Undergraduate", "Graduate", "Online"]],
    measures: [{ name: "Applications", base: 1300, int: true }, { name: "Enrolled students", of: "Applications", frac: [0.18, 0.32], int: true }, { name: "Tuition revenue", base: 2900000 }, { name: "Financial aid", of: "Tuition revenue", frac: [0.25, 0.42] }],
    ratios: [div("Enrolled students", "Applications", "Yield rate"), div("Financial aid", "Tuition revenue", "Discount rate", true), { label: "Net tuition per student", f: (m) => `(${m["Tuition revenue"]}-${m["Financial aid"]})/${m["Enrolled students"]}` }],
    lowerBetter: ["Financial aid"],
  },
  {
    id: "nonprofit-fundraising-dashboard", name: "Nonprofit Fundraising Dashboard", industry: "Nonprofit",
    dimA: ["Appeal", ["Annual fund", "Gala", "Major gifts", "Online"]], dimB: ["Donor type", ["Individual", "Foundation", "Corporate"]],
    measures: [{ name: "Funds raised", base: 88000 }, { name: "Fundraising cost", of: "Funds raised", frac: [0.1, 0.28] }, { name: "Donors", base: 410, int: true }, { name: "Gifts", of: "Donors", frac: [1.1, 1.6], int: true }],
    ratios: [div("Fundraising cost", "Funds raised", "Cost to raise $1", true), div("Funds raised", "Gifts", "Average gift"), div("Gifts", "Donors", "Gifts per donor")],
    lowerBetter: ["Fundraising cost"],
  },
  {
    id: "utility-energy-dashboard", name: "Utility Energy Sales Dashboard", industry: "Utilities",
    dimA: ["Service area", ["North grid", "South grid", "Coastal", "Valley"]], dimB: ["Customer class", ["Residential", "Commercial", "Industrial"]],
    measures: [{ name: "Energy sold (MWh)", base: 92000, int: true }, { name: "Energy revenue", base: 11800000 }, { name: "Fuel & purchased power", of: "Energy revenue", frac: [0.38, 0.52] }, { name: "Outage minutes", base: 1900, int: true }],
    ratios: [div("Energy revenue", "Energy sold (MWh)", "Revenue per MWh"), margin("Energy revenue", "Fuel & purchased power", "Gross margin %"), div("Fuel & purchased power", "Energy sold (MWh)", "Power cost per MWh", true)],
    lowerBetter: ["Fuel & purchased power", "Outage minutes"],
  },
  {
    id: "farm-operations-dashboard", name: "Farm Operations & Yield Dashboard", industry: "Agriculture",
    dimA: ["Field", ["North 40", "River bottom", "East ridge", "Home farm"]], dimB: ["Crop", ["Corn", "Soybeans", "Wheat"]],
    measures: [{ name: "Acres harvested", base: 160, int: true }, { name: "Bushels", of: "Acres harvested", frac: [48, 190], int: true }, { name: "Crop revenue", base: 92000 }, { name: "Input costs", of: "Crop revenue", frac: [0.42, 0.62] }],
    ratios: [div("Bushels", "Acres harvested", "Yield per acre"), margin("Crop revenue", "Input costs", "Margin over inputs %"), div("Input costs", "Acres harvested", "Input cost per acre", true)],
    lowerBetter: ["Input costs"],
  },
  {
    id: "mining-operations-dashboard", name: "Mining Production Dashboard", industry: "Mining",
    dimA: ["Mine", ["Pit A", "Pit B", "Underground C"]], dimB: ["Ore type", ["Oxide", "Sulfide", "Transitional"]],
    measures: [{ name: "Ore milled (t)", base: 220000, int: true }, { name: "Metal recovered (oz)", of: "Ore milled (t)", frac: [0.018, 0.031], int: true }, { name: "Metal revenue", base: 9800000 }, { name: "Mining cost", of: "Metal revenue", frac: [0.45, 0.66] }],
    ratios: [div("Metal recovered (oz)", "Ore milled (t)", "Recovered grade (oz/t)"), div("Mining cost", "Metal recovered (oz)", "Cash cost per oz", true), margin("Metal revenue", "Mining cost", "Mine margin %")],
    lowerBetter: ["Mining cost"],
  },
  {
    id: "gym-fitness-dashboard", name: "Fitness Club Membership Dashboard", industry: "Fitness",
    dimA: ["Club", ["Downtown", "Lakeside", "Northgate"]], dimB: ["Membership", ["Basic", "Premium", "Family"]],
    measures: [{ name: "Active members", base: 2400, int: true }, { name: "New joins", of: "Active members", frac: [0.03, 0.07], int: true }, { name: "Cancellations", of: "Active members", frac: [0.015, 0.045], int: true }, { name: "Membership revenue", base: 128000 }],
    ratios: [div("Cancellations", "Active members", "Monthly churn", true), div("Membership revenue", "Active members", "Revenue per member"), div("New joins", "Cancellations", "Join-to-cancel ratio")],
    lowerBetter: ["Cancellations"],
  },
  {
    id: "auto-dealership-dashboard", name: "Auto Dealership Sales Dashboard", industry: "Automotive retail",
    dimA: ["Department", ["New vehicles", "Used vehicles", "Service", "Parts"]], dimB: ["Brand", ["Toyota", "Ford", "Honda"]],
    measures: [{ name: "Gross sales", base: 1150000 }, { name: "Cost of sales", of: "Gross sales", frac: [0.78, 0.9] }, { name: "Deals / repair orders", base: 210, int: true }, { name: "F&I income", of: "Gross sales", frac: [0.01, 0.03] }],
    ratios: [margin("Gross sales", "Cost of sales", "Front-end gross %"), { label: "Gross profit per deal", f: (m) => `(${m["Gross sales"]}-${m["Cost of sales"]})/${m["Deals / repair orders"]}` }, div("F&I income", "Deals / repair orders", "F&I per deal")],
    lowerBetter: ["Cost of sales"],
  },
  {
    id: "law-firm-dashboard", name: "Law Firm Billing & Realization Dashboard", industry: "Legal services",
    dimA: ["Practice", ["Corporate", "Litigation", "Real estate", "IP"]], dimB: ["Level", ["Partner", "Associate", "Paralegal"]],
    measures: [{ name: "Hours worked", base: 2600, int: true }, { name: "Hours billed", of: "Hours worked", frac: [0.78, 0.93], int: true }, { name: "Fees billed", base: 980000 }, { name: "Fees collected", of: "Fees billed", frac: [0.84, 0.98] }],
    ratios: [div("Hours billed", "Hours worked", "Utilization"), div("Fees collected", "Fees billed", "Realization rate"), div("Fees billed", "Hours billed", "Effective bill rate")],
  },
  {
    id: "consulting-utilization-dashboard", name: "Consulting Utilization Dashboard", industry: "Professional services",
    dimA: ["Practice", ["Strategy", "Technology", "Operations", "Risk"]], dimB: ["Grade", ["Partner", "Manager", "Consultant"]],
    measures: [{ name: "Available hours", base: 3400, int: true }, { name: "Billable hours", of: "Available hours", frac: [0.62, 0.84], int: true }, { name: "Revenue", base: 690000 }, { name: "Delivery cost", of: "Revenue", frac: [0.48, 0.64] }],
    ratios: [div("Billable hours", "Available hours", "Utilization"), div("Revenue", "Billable hours", "Revenue per billable hour"), margin("Revenue", "Delivery cost", "Contribution margin %")],
    lowerBetter: ["Delivery cost"],
  },
  {
    id: "events-dashboard", name: "Events & Ticketing Dashboard", industry: "Live events",
    dimA: ["Venue", ["Arena", "Theater", "Amphitheater"]], dimB: ["Genre", ["Concert", "Comedy", "Sports"]],
    measures: [{ name: "Capacity", base: 46000, int: true }, { name: "Tickets sold", of: "Capacity", frac: [0.62, 0.95], int: true }, { name: "Ticket revenue", base: 2600000 }, { name: "Event costs", of: "Ticket revenue", frac: [0.55, 0.75] }],
    ratios: [div("Tickets sold", "Capacity", "Sell-through %"), div("Ticket revenue", "Tickets sold", "Average ticket price"), margin("Ticket revenue", "Event costs", "Event margin %")],
    lowerBetter: ["Event costs"],
  },
  {
    id: "pharmacy-dashboard", name: "Pharmacy Chain Dashboard", industry: "Pharmacy",
    dimA: ["Store", ["Elm St", "Medical Plaza", "Northside", "Mall"]], dimB: ["Line", ["Prescriptions", "OTC", "Front store"]],
    measures: [{ name: "Scripts filled", base: 6100, int: true }, { name: "Pharmacy sales", base: 410000 }, { name: "Drug cost", of: "Pharmacy sales", frac: [0.72, 0.82] }, { name: "Front-store sales", base: 88000 }],
    ratios: [margin("Pharmacy sales", "Drug cost", "Pharmacy gross margin %"), div("Pharmacy sales", "Scripts filled", "Revenue per script"), { label: "Front-store share", f: (m) => `${m["Front-store sales"]}/(${m["Pharmacy sales"]}+${m["Front-store sales"]})` }],
    lowerBetter: ["Drug cost"],
  },
];

const PROJECTIONS: ProjSpec[] = [
  { id: "coffee-shop-model", name: "Coffee Shop Chain 5-Year Model", industry: "Food service", units: ["Cups sold", 420000, 0.12], price: ["Average ticket", 5.4, 0.03], cogsPct: 0.3, opex: [["Store labor", 0.28], ["Marketing", 0.03]], fixedCost: ["Rent & occupancy", 360000, 0.03], daPct: 0.04, capexPct: 0.06, nwcPct: 0.02, taxRate: 0.25, wacc: 0.11, termGrowth: 0.025 },
  { id: "saas-startup-model", name: "SaaS Startup 5-Year Model", industry: "Software", units: ["Paying customers", 1200, 0.45], price: ["Annual contract value", 6000, 0.04], cogsPct: 0.22, opex: [["Sales & marketing", 0.38], ["Research & development", 0.24]], fixedCost: ["General & administrative", 1400000, 0.08], daPct: 0.02, capexPct: 0.02, nwcPct: -0.05, taxRate: 0.21, wacc: 0.14, termGrowth: 0.03 },
  { id: "manufacturing-plant-model", name: "Manufacturing Plant 5-Year Model", industry: "Industrial manufacturing", units: ["Units shipped", 180000, 0.06], price: ["Selling price per unit", 145, 0.025], cogsPct: 0.64, opex: [["Selling & distribution", 0.07]], fixedCost: ["Plant overhead", 2600000, 0.03], daPct: 0.05, capexPct: 0.07, nwcPct: 0.15, taxRate: 0.25, wacc: 0.095, termGrowth: 0.02 },
  { id: "hotel-development-model", name: "Hotel Property 5-Year Model", industry: "Hospitality", units: ["Room nights sold", 58000, 0.04], price: ["Average daily rate", 189, 0.035], cogsPct: 0.26, opex: [["Sales & marketing", 0.06], ["Franchise fees", 0.05]], fixedCost: ["Property operations", 1900000, 0.03], daPct: 0.06, capexPct: 0.04, nwcPct: 0.03, taxRate: 0.25, wacc: 0.09, termGrowth: 0.02 },
  { id: "solar-farm-model", name: "Solar Farm 5-Year Model", industry: "Renewable energy", units: ["MWh generated", 210000, 0.0], price: ["Power price per MWh", 48, 0.02], cogsPct: 0.08, opex: [["Land lease", 0.04]], fixedCost: ["O&M contract", 1100000, 0.025], daPct: 0.22, capexPct: 0.01, nwcPct: 0.02, taxRate: 0.21, wacc: 0.075, termGrowth: 0.01 },
  { id: "dental-practice-model", name: "Dental Practice 5-Year Model", industry: "Healthcare services", units: ["Patient visits", 9800, 0.07], price: ["Revenue per visit", 285, 0.03], cogsPct: 0.08, opex: [["Clinical staff", 0.3], ["Marketing", 0.03]], fixedCost: ["Office & equipment leases", 240000, 0.03], daPct: 0.03, capexPct: 0.04, nwcPct: 0.06, taxRate: 0.24, wacc: 0.12, termGrowth: 0.025 },
  { id: "ecommerce-brand-model", name: "D2C E-commerce Brand 5-Year Model", industry: "Direct-to-consumer retail", units: ["Orders", 95000, 0.28], price: ["Average order value", 72, 0.02], cogsPct: 0.42, opex: [["Paid acquisition", 0.18], ["Fulfillment & shipping", 0.11]], fixedCost: ["Team & overhead", 1300000, 0.1], daPct: 0.01, capexPct: 0.01, nwcPct: 0.1, taxRate: 0.25, wacc: 0.13, termGrowth: 0.03 },
  { id: "logistics-company-model", name: "Trucking & Logistics 5-Year Model", industry: "Transportation", units: ["Loads delivered", 46000, 0.08], price: ["Revenue per load", 1850, 0.025], cogsPct: 0.58, opex: [["Fuel surcharge pass-through", 0.04], ["Insurance & claims", 0.05]], fixedCost: ["Terminal & admin", 4200000, 0.03], daPct: 0.07, capexPct: 0.09, nwcPct: 0.08, taxRate: 0.25, wacc: 0.1, termGrowth: 0.02 },
  { id: "gym-chain-model", name: "Fitness Club Chain 5-Year Model", industry: "Fitness", units: ["Average members", 14500, 0.1], price: ["Annual dues per member", 540, 0.03], cogsPct: 0.1, opex: [["Club staff", 0.26], ["Marketing", 0.06]], fixedCost: ["Rent & utilities", 2200000, 0.03], daPct: 0.07, capexPct: 0.06, nwcPct: -0.02, taxRate: 0.25, wacc: 0.11, termGrowth: 0.025 },
  { id: "craft-brewery-model", name: "Craft Brewery 5-Year Model", industry: "Beverage manufacturing", units: ["Barrels sold", 24000, 0.11], price: ["Net price per barrel", 265, 0.03], cogsPct: 0.48, opex: [["Distribution & excise", 0.12], ["Brand marketing", 0.06]], fixedCost: ["Brewery overhead", 820000, 0.03], daPct: 0.06, capexPct: 0.08, nwcPct: 0.09, taxRate: 0.25, wacc: 0.115, termGrowth: 0.02 },
  { id: "senior-living-model", name: "Senior Living Community 5-Year Model", industry: "Senior care", units: ["Occupied unit-months", 2350, 0.03], price: ["Monthly fee per unit", 5600, 0.035], cogsPct: 0.18, opex: [["Care staff", 0.36], ["Dining & activities", 0.08]], fixedCost: ["Facility operations", 1500000, 0.03], daPct: 0.05, capexPct: 0.04, nwcPct: 0.02, taxRate: 0.25, wacc: 0.085, termGrowth: 0.02 },
  { id: "marketing-agency-model", name: "Marketing Agency 5-Year Model", industry: "Agency services", units: ["Retainer clients", 38, 0.15], price: ["Annual fees per client", 145000, 0.04], cogsPct: 0.46, opex: [["Business development", 0.06]], fixedCost: ["Office & admin", 950000, 0.04], daPct: 0.015, capexPct: 0.015, nwcPct: 0.12, taxRate: 0.25, wacc: 0.13, termGrowth: 0.025 },
  { id: "car-wash-model", name: "Express Car Wash 5-Year Model", industry: "Consumer services", units: ["Cars washed", 210000, 0.08], price: ["Revenue per wash", 14.5, 0.03], cogsPct: 0.12, opex: [["Site labor", 0.2], ["Marketing", 0.04]], fixedCost: ["Site leases & utilities", 620000, 0.03], daPct: 0.09, capexPct: 0.07, nwcPct: 0.01, taxRate: 0.25, wacc: 0.105, termGrowth: 0.02 },
  { id: "data-center-model", name: "Data Center Colocation 5-Year Model", industry: "Digital infrastructure", units: ["Contracted MW-months", 420, 0.18], price: ["Revenue per MW-month", 165000, 0.02], cogsPct: 0.34, opex: [["Sales & solutions", 0.05]], fixedCost: ["Site operations", 6800000, 0.03], daPct: 0.18, capexPct: 0.2, nwcPct: 0.03, taxRate: 0.21, wacc: 0.08, termGrowth: 0.03 },
  { id: "vineyard-winery-model", name: "Vineyard & Winery 5-Year Model", industry: "Wine production", units: ["Cases sold", 32000, 0.06], price: ["Net price per case", 168, 0.035], cogsPct: 0.38, opex: [["Tasting room & DTC", 0.1], ["Distribution", 0.08]], fixedCost: ["Vineyard operations", 1250000, 0.03], daPct: 0.07, capexPct: 0.06, nwcPct: 0.25, taxRate: 0.25, wacc: 0.1, termGrowth: 0.02 },
];

const BUDGETS: BudgetSpec[] = [
  { id: "household-annual-budget", name: "Household Annual Budget Tracker", scope: "Household", lines: [["Housing", "Mortgage / rent", 26400], ["Housing", "Utilities", 4200], ["Transport", "Car payment", 5400], ["Transport", "Fuel & transit", 2400], ["Living", "Groceries", 9000], ["Living", "Dining out", 3000], ["Living", "Healthcare", 2400], ["Savings", "Retirement", 7200], ["Savings", "Emergency fund", 3600], ["Lifestyle", "Travel", 4000], ["Lifestyle", "Subscriptions", 900]] },
  { id: "wedding-budget", name: "Wedding Budget Planner", scope: "Wedding", lines: [["Ceremony", "Venue", 12000], ["Ceremony", "Officiant", 800], ["Reception", "Catering", 15000], ["Reception", "Bar", 4500], ["Reception", "Music / DJ", 2200], ["Style", "Attire", 3500], ["Style", "Flowers & decor", 3800], ["Media", "Photography", 4200], ["Media", "Videography", 2600], ["Other", "Invitations", 900], ["Other", "Rings", 5000]] },
  { id: "marketing-department-budget", name: "Marketing Department Budget", scope: "Marketing", lines: [["Paid media", "Search ads", 240000], ["Paid media", "Social ads", 180000], ["Paid media", "Display", 60000], ["Content", "Agency retainer", 96000], ["Content", "Video production", 54000], ["Events", "Trade shows", 120000], ["Events", "Customer summit", 85000], ["Tools", "Marketing software", 48000], ["People", "Contractors", 72000]] },
  { id: "it-department-budget", name: "IT Department Budget", scope: "IT", lines: [["Infrastructure", "Cloud hosting", 420000], ["Infrastructure", "Network & telecom", 96000], ["Software", "SaaS licenses", 310000], ["Software", "Security tools", 140000], ["Hardware", "Laptops & devices", 180000], ["Services", "Managed services", 120000], ["Services", "Consulting", 90000], ["People", "Training", 36000]] },
  { id: "event-budget", name: "Corporate Event Budget", scope: "Event", lines: [["Venue", "Venue hire", 45000], ["Venue", "AV & staging", 28000], ["Catering", "Meals", 36000], ["Catering", "Beverages", 12000], ["Program", "Speakers", 30000], ["Program", "Entertainment", 9000], ["Marketing", "Promotion", 15000], ["Logistics", "Travel & lodging", 40000], ["Logistics", "Swag & printing", 8000]] },
  { id: "startup-operating-budget", name: "Startup Operating Budget", scope: "Startup", lines: [["People", "Salaries", 1450000], ["People", "Benefits & payroll tax", 290000], ["Go-to-market", "Paid acquisition", 360000], ["Go-to-market", "Events & content", 90000], ["Product", "Cloud & tooling", 160000], ["Product", "Design contractors", 70000], ["G&A", "Rent", 144000], ["G&A", "Legal & accounting", 85000], ["G&A", "Insurance", 30000]] },
  { id: "school-budget", name: "School Operating Budget", scope: "School", lines: [["Instruction", "Teacher salaries", 2800000], ["Instruction", "Classroom supplies", 140000], ["Support", "Counseling & special ed", 620000], ["Support", "Technology", 210000], ["Facilities", "Maintenance", 340000], ["Facilities", "Utilities", 260000], ["Operations", "Transportation", 390000], ["Operations", "Food service", 300000], ["Admin", "Administration", 480000]] },
  { id: "construction-project-budget", name: "Construction Project Cost Budget", scope: "Construction project", lines: [["Site", "Site prep & excavation", 380000], ["Structure", "Concrete & foundations", 920000], ["Structure", "Steel framing", 1250000], ["Envelope", "Roofing", 410000], ["Envelope", "Glazing & facade", 760000], ["MEP", "Mechanical & HVAC", 880000], ["MEP", "Electrical", 690000], ["Finishes", "Interior fit-out", 840000], ["Soft costs", "Design & permits", 520000], ["Soft costs", "Contingency", 450000]] },
  { id: "nonprofit-program-budget", name: "Nonprofit Program Budget", scope: "Program", lines: [["Program", "Program staff", 420000], ["Program", "Participant support", 160000], ["Program", "Materials", 45000], ["Outreach", "Community events", 38000], ["Outreach", "Communications", 30000], ["Operations", "Rent & utilities", 72000], ["Operations", "Evaluation", 40000], ["Fundraising", "Grant writing", 36000]] },
  { id: "restaurant-opex-budget", name: "Restaurant Operating Budget", scope: "Restaurant", lines: [["Prime cost", "Food purchases", 420000], ["Prime cost", "Beverage purchases", 110000], ["Prime cost", "Kitchen labor", 300000], ["Prime cost", "Front-of-house labor", 260000], ["Occupancy", "Rent", 144000], ["Occupancy", "Utilities", 48000], ["Operations", "Repairs & maintenance", 30000], ["Operations", "Marketing", 36000], ["Operations", "Smallwares & linen", 22000]] },
];

export const INDUSTRY_TEMPLATES: FinancialTemplate[] = [
  ...DASHBOARDS.map(kpiDashboard),
  ...PROJECTIONS.map(projectionModel),
  ...BUDGETS.map(budgetTracker),
];
