import { kpiDashboard, type DashSpec, type Measure, type Ratio } from "./kits.ts";
import type { FinancialTemplate } from "./types.ts";

/* Compact spec helpers ------------------------------------------------ */
const m = (name: string, base: number, int = false): Measure => ({ name, base, int });
const of = (name: string, src: string, lo: number, hi: number, int = false): Measure => ({
  name,
  of: src,
  frac: [lo, hi],
  int,
});
const div = (a: string, b: string, label: string, lowerBetter = false): Ratio => ({
  label,
  f: (r) => `${r[a]}/${r[b]}`,
  lowerBetter,
});
const mg = (rev: string, cost: string, label: string): Ratio => ({
  label,
  f: (r) => `(${r[rev]}-${r[cost]})/${r[rev]}`,
});
const per1k = (a: string, b: string, label: string, lowerBetter = false): Ratio => ({
  label,
  f: (r) => `${r[a]}/${r[b]}*1000`,
  lowerBetter,
});
const d = (
  id: string,
  name: string,
  industry: string,
  dimA: [string, string[]],
  dimB: [string, string[]],
  measures: Measure[],
  ratios: Ratio[],
  lowerBetter: string[] = [],
): DashSpec => ({ id, name, industry, dimA, dimB, measures, ratios, lowerBetter });

/* Specs ---------------------------------------------------------------- */
const SPECS: DashSpec[] = [
  // ---------- Retail & consumer ----------
  d(
    "grocery-supermarket-dashboard",
    "Supermarket Category Dashboard",
    "Grocery retail",
    ["Department", ["Produce", "Dairy", "Meat & seafood", "Center store"]],
    ["Store", ["Store 101", "Store 204", "Store 318"]],
    [
      m("Sales", 186000),
      of("Cost of sales", "Sales", 0.68, 0.76),
      of("Shrink", "Sales", 0.01, 0.04),
      m("Baskets", 21000, true),
    ],
    [
      mg("Sales", "Cost of sales", "Gross margin %"),
      div("Shrink", "Sales", "Shrink % of sales", true),
      div("Sales", "Baskets", "Average basket"),
    ],
    ["Cost of sales", "Shrink"],
  ),
  d(
    "convenience-fuel-dashboard",
    "Convenience Store & Fuel Dashboard",
    "Fuel retail",
    ["Site", ["I-80 Exit 12", "Main & 5th", "Lakeshore", "Airport Rd"]],
    ["Format", ["Fuel", "In-store", "Car wash"]],
    [
      m("Fuel gallons", 98000, true),
      m("Fuel revenue", 342000),
      of("Fuel cost", "Fuel revenue", 0.86, 0.92),
      m("Inside sales", 118000),
    ],
    [
      {
        label: "Fuel margin per gallon",
        f: (r) => `(${r["Fuel revenue"]}-${r["Fuel cost"]})/${r["Fuel gallons"]}`,
      },
      mg("Fuel revenue", "Fuel cost", "Fuel margin %"),
      {
        label: "Inside sales share",
        f: (r) => `${r["Inside sales"]}/(${r["Fuel revenue"]}+${r["Inside sales"]})`,
      },
    ],
    ["Fuel cost"],
  ),
  d(
    "fashion-returns-dashboard",
    "Fashion E-commerce Returns Dashboard",
    "Online apparel",
    ["Category", ["Dresses", "Denim", "Shoes", "Outerwear"]],
    ["Market", ["US", "UK", "EU"]],
    [
      m("Units shipped", 6400, true),
      of("Units returned", "Units shipped", 0.18, 0.38, true),
      m("Gross sales", 410000),
      of("Refunds", "Gross sales", 0.16, 0.34),
    ],
    [
      div("Units returned", "Units shipped", "Return rate", true),
      mg("Gross sales", "Refunds", "Net sales retention %"),
      div("Refunds", "Units returned", "Average refund", true),
    ],
    ["Units returned", "Refunds"],
  ),
  d(
    "marketplace-gmv-dashboard",
    "Online Marketplace GMV Dashboard",
    "Two-sided marketplace",
    ["Category", ["Electronics", "Home", "Collectibles", "Fashion"]],
    ["Seller tier", ["Top rated", "Standard", "New"]],
    [
      m("GMV", 2200000),
      of("Take revenue", "GMV", 0.09, 0.14),
      m("Orders", 31000, true),
      m("Active buyers", 18500, true),
    ],
    [
      div("Take revenue", "GMV", "Take rate"),
      div("GMV", "Orders", "Average order value"),
      div("Orders", "Active buyers", "Orders per buyer"),
    ],
  ),
  d(
    "subscription-box-dashboard",
    "Subscription Box Dashboard",
    "Subscription commerce",
    ["Plan", ["Monthly", "Quarterly", "Annual"]],
    ["Acquisition", ["Paid social", "Referral", "Influencer"]],
    [
      m("Active subscribers", 14200, true),
      of("Cancellations", "Active subscribers", 0.04, 0.11, true),
      m("Subscription revenue", 512000),
      of("Box cost", "Subscription revenue", 0.38, 0.5),
    ],
    [
      div("Cancellations", "Active subscribers", "Monthly churn", true),
      div("Subscription revenue", "Active subscribers", "Revenue per subscriber"),
      mg("Subscription revenue", "Box cost", "Contribution margin %"),
    ],
    ["Cancellations", "Box cost"],
  ),
  d(
    "furniture-retail-dashboard",
    "Furniture & Home Retail Dashboard",
    "Home furnishings",
    ["Showroom", ["Flagship", "Outlet", "Online"]],
    ["Category", ["Sofas", "Bedroom", "Dining", "Decor"]],
    [
      m("Written sales", 520000),
      of("Delivered sales", "Written sales", 0.78, 0.96),
      m("Showroom visits", 4200, true),
      m("Orders written", 610, true),
    ],
    [
      div("Orders written", "Showroom visits", "Close rate"),
      div("Written sales", "Orders written", "Average ticket"),
      div("Delivered sales", "Written sales", "Delivered-to-written %"),
    ],
  ),
  d(
    "franchise-system-dashboard",
    "Franchise System Royalty Dashboard",
    "Franchising",
    ["Region", ["Northeast", "Southeast", "Midwest", "West"]],
    ["Unit type", ["Franchised", "Company-owned", "Kiosk"]],
    [
      m("System sales", 4100000),
      of("Royalty income", "System sales", 0.05, 0.065),
      of("Ad fund contributions", "System sales", 0.018, 0.025),
      m("Open units", 46, true),
    ],
    [
      div("Royalty income", "System sales", "Effective royalty rate"),
      div("System sales", "Open units", "Average unit volume"),
      div("Ad fund contributions", "System sales", "Ad fund rate"),
    ],
  ),
  d(
    "salon-spa-dashboard",
    "Salon & Spa Dashboard",
    "Personal care",
    ["Location", ["Midtown", "Westfield", "Harbor"]],
    ["Service", ["Hair", "Nails", "Massage", "Skin"]],
    [
      m("Service revenue", 68000),
      m("Retail revenue", 9400),
      m("Appointments", 1150, true),
      of("Stylist commissions", "Service revenue", 0.38, 0.48),
    ],
    [
      div("Service revenue", "Appointments", "Average service ticket"),
      {
        label: "Retail attach %",
        f: (r) => `${r["Retail revenue"]}/(${r["Service revenue"]}+${r["Retail revenue"]})`,
      },
      div("Stylist commissions", "Service revenue", "Commission %", true),
    ],
    ["Stylist commissions"],
  ),
  d(
    "coffee-shop-dashboard",
    "Coffee Shop Store Dashboard",
    "Coffee & cafés",
    ["Store", ["Station", "Campus", "Riverside", "Old Town"]],
    ["Daypart", ["Morning", "Midday", "Afternoon"]],
    [
      m("Net sales", 61000),
      m("Transactions", 10400, true),
      of("Cost of goods", "Net sales", 0.27, 0.33),
      of("Labor cost", "Net sales", 0.26, 0.34),
    ],
    [
      div("Net sales", "Transactions", "Average ticket"),
      {
        label: "Prime cost %",
        f: (r) => `(${r["Cost of goods"]}+${r["Labor cost"]})/${r["Net sales"]}`,
        lowerBetter: true,
      },
      div("Labor cost", "Transactions", "Labor cost per transaction", true),
    ],
    ["Cost of goods", "Labor cost"],
  ),
  d(
    "bakery-production-dashboard",
    "Bakery Production & Waste Dashboard",
    "Bakery",
    ["Product line", ["Bread", "Pastry", "Cakes", "Wholesale"]],
    ["Outlet", ["Retail shop", "Café", "Wholesale"]],
    [
      m("Units baked", 18500, true),
      of("Units sold", "Units baked", 0.82, 0.96, true),
      m("Revenue", 74000),
      of("Ingredient cost", "Revenue", 0.24, 0.34),
    ],
    [
      div("Units sold", "Units baked", "Sell-through %"),
      {
        label: "Waste rate",
        f: (r) => `(${r["Units baked"]}-${r["Units sold"]})/${r["Units baked"]}`,
        lowerBetter: true,
      },
      mg("Revenue", "Ingredient cost", "Margin over ingredients %"),
    ],
    ["Ingredient cost"],
  ),
  d(
    "catering-dashboard",
    "Catering & Events Kitchen Dashboard",
    "Catering",
    ["Event type", ["Corporate", "Wedding", "Social", "Nonprofit"]],
    ["Service style", ["Buffet", "Plated", "Drop-off"]],
    [
      m("Guests served", 2600, true),
      m("Catering revenue", 148000),
      of("Food cost", "Catering revenue", 0.28, 0.36),
      of("Event labor", "Catering revenue", 0.22, 0.3),
    ],
    [
      div("Catering revenue", "Guests served", "Revenue per guest"),
      div("Food cost", "Catering revenue", "Food cost %", true),
      {
        label: "Event margin %",
        f: (r) =>
          `(${r["Catering revenue"]}-${r["Food cost"]}-${r["Event labor"]})/${r["Catering revenue"]}`,
      },
    ],
    ["Food cost", "Event labor"],
  ),
  d(
    "brewery-taproom-dashboard",
    "Brewery Taproom & Distribution Dashboard",
    "Craft beverage",
    ["Brand", ["IPA", "Lager", "Stout", "Seasonal"]],
    ["Channel", ["Taproom", "Distributor", "Retail cans"]],
    [
      m("Barrels sold", 420, true),
      m("Net revenue", 118000),
      of("Cost of goods", "Net revenue", 0.38, 0.5),
      of("Excise taxes", "Net revenue", 0.03, 0.06),
    ],
    [
      div("Net revenue", "Barrels sold", "Revenue per barrel"),
      mg("Net revenue", "Cost of goods", "Gross margin %"),
      div("Cost of goods", "Barrels sold", "Cost per barrel", true),
    ],
    ["Cost of goods", "Excise taxes"],
  ),

  // ---------- Mobility & travel ----------
  d(
    "food-delivery-dashboard",
    "Food Delivery Platform Dashboard",
    "On-demand delivery",
    ["City", ["Austin", "Denver", "Portland", "Nashville"]],
    ["Order type", ["Restaurant", "Grocery", "Convenience"]],
    [
      m("Orders", 84000, true),
      m("Gross order value", 2350000),
      of("Platform revenue", "Gross order value", 0.14, 0.2),
      of("Courier pay", "Platform revenue", 0.55, 0.72),
    ],
    [
      div("Gross order value", "Orders", "Average order value"),
      div("Platform revenue", "Gross order value", "Take rate"),
      {
        label: "Contribution per order",
        f: (r) => `(${r["Platform revenue"]}-${r["Courier pay"]})/${r["Orders"]}`,
      },
    ],
    ["Courier pay"],
  ),
  d(
    "ride-hailing-dashboard",
    "Ride-hailing Operations Dashboard",
    "Mobility",
    ["City", ["Chicago", "Miami", "Seattle", "Phoenix"]],
    ["Product", ["Standard", "XL", "Premium"]],
    [
      m("Trips", 210000, true),
      m("Gross bookings", 3900000),
      of("Driver earnings", "Gross bookings", 0.68, 0.76),
      m("Active drivers", 6200, true),
    ],
    [
      div("Gross bookings", "Trips", "Average fare"),
      mg("Gross bookings", "Driver earnings", "Net revenue margin %"),
      div("Trips", "Active drivers", "Trips per driver"),
    ],
    ["Driver earnings"],
  ),
  d(
    "vacation-rental-dashboard",
    "Vacation Rental Portfolio Dashboard",
    "Short-term rentals",
    ["Market", ["Mountain", "Beach", "City", "Lake"]],
    ["Property size", ["Studio", "2-bed", "4-bed+"]],
    [
      m("Available nights", 1800, true),
      of("Booked nights", "Available nights", 0.55, 0.86, true),
      m("Rental revenue", 312000),
      of("Cleaning & ops cost", "Rental revenue", 0.16, 0.26),
    ],
    [
      div("Booked nights", "Available nights", "Occupancy %"),
      div("Rental revenue", "Booked nights", "Average nightly rate"),
      div("Rental revenue", "Available nights", "RevPAN"),
    ],
    ["Cleaning & ops cost"],
  ),
  d(
    "cruise-line-dashboard",
    "Cruise Line Yield Dashboard",
    "Cruise",
    ["Ship", ["Aurora", "Meridian", "Solstice"]],
    ["Itinerary", ["Caribbean", "Alaska", "Mediterranean"]],
    [
      m("Passenger cruise days", 128000, true),
      m("Ticket revenue", 24500000),
      m("Onboard revenue", 7600000),
      of("Ship operating cost", "Ticket revenue", 0.62, 0.78),
    ],
    [
      div("Ticket revenue", "Passenger cruise days", "Ticket yield per day"),
      div("Onboard revenue", "Passenger cruise days", "Onboard spend per day"),
      div("Ship operating cost", "Passenger cruise days", "Cost per passenger day", true),
    ],
    ["Ship operating cost"],
  ),
  d(
    "travel-agency-dashboard",
    "Travel Agency Bookings Dashboard",
    "Travel services",
    ["Product", ["Flights", "Hotels", "Packages", "Cruises"]],
    ["Client", ["Leisure", "Corporate", "Groups"]],
    [
      m("Bookings", 1900, true),
      m("Gross travel value", 2850000),
      of("Commission income", "Gross travel value", 0.06, 0.12),
      of("Cancellations", "Bookings", 0.03, 0.09, true),
    ],
    [
      div("Commission income", "Gross travel value", "Commission rate"),
      div("Gross travel value", "Bookings", "Value per booking"),
      div("Cancellations", "Bookings", "Cancellation rate", true),
    ],
    ["Cancellations"],
  ),
  d(
    "car-rental-dashboard",
    "Car Rental Fleet Utilization Dashboard",
    "Vehicle rental",
    ["Branch", ["Airport", "Downtown", "Suburban", "Resort"]],
    ["Car class", ["Economy", "SUV", "Luxury"]],
    [
      m("Fleet days available", 14500, true),
      of("Rental days", "Fleet days available", 0.66, 0.88, true),
      m("Rental revenue", 780000),
      of("Fleet cost", "Rental revenue", 0.42, 0.56),
    ],
    [
      div("Rental days", "Fleet days available", "Utilization"),
      div("Rental revenue", "Rental days", "Revenue per rental day"),
      mg("Rental revenue", "Fleet cost", "Fleet margin %"),
    ],
    ["Fleet cost"],
  ),
  d(
    "airport-operations-dashboard",
    "Airport Operations Dashboard",
    "Airports",
    ["Terminal", ["Terminal A", "Terminal B", "Terminal C"]],
    ["Traffic", ["Domestic", "International", "Cargo"]],
    [
      m("Passengers", 1150000, true),
      m("Aeronautical revenue", 11800000),
      m("Concession revenue", 6200000),
      of("Delayed departures", "Passengers", 0.0006, 0.0014, true),
    ],
    [
      div("Aeronautical revenue", "Passengers", "Aero revenue per passenger"),
      div("Concession revenue", "Passengers", "Concession spend per passenger"),
      per1k("Delayed departures", "Passengers", "Delays per 1,000 passengers", true),
    ],
    ["Delayed departures"],
  ),

  // ---------- Healthcare & life sciences ----------
  d(
    "dental-practice-dashboard",
    "Dental Practice Dashboard",
    "Dental care",
    ["Provider", ["Dr. Reyes", "Dr. Okafor", "Hygiene team"]],
    ["Procedure", ["Preventive", "Restorative", "Cosmetic"]],
    [
      m("Patient visits", 640, true),
      m("Production", 182000),
      of("Collections", "Production", 0.88, 0.98),
      m("New patients", 72, true),
    ],
    [
      div("Collections", "Production", "Collection rate"),
      div("Production", "Patient visits", "Production per visit"),
      div("New patients", "Patient visits", "New patient share"),
    ],
  ),
  d(
    "veterinary-clinic-dashboard",
    "Veterinary Clinic Dashboard",
    "Animal health",
    ["Clinic", ["Northside", "Eastgate", "Country"]],
    ["Species", ["Dogs", "Cats", "Exotics"]],
    [
      m("Appointments", 1450, true),
      m("Revenue", 214000),
      of("Pharmacy & supplies cost", "Revenue", 0.18, 0.26),
      m("Active patients", 5200, true),
    ],
    [
      div("Revenue", "Appointments", "Average invoice"),
      mg("Revenue", "Pharmacy & supplies cost", "Margin over supplies %"),
      per1k("Appointments", "Active patients", "Visits per 1,000 patients"),
    ],
    ["Pharmacy & supplies cost"],
  ),
  d(
    "physical-therapy-dashboard",
    "Physical Therapy Clinic Dashboard",
    "Rehabilitation",
    ["Therapist", ["T. Nguyen", "R. Silva", "A. Brooks", "J. Park"]],
    ["Payer", ["Commercial", "Medicare", "Workers comp"]],
    [
      m("Scheduled visits", 520, true),
      of("Completed visits", "Scheduled visits", 0.84, 0.95, true),
      m("Net revenue", 58000),
      m("Plan-of-care completions", 46, true),
    ],
    [
      div("Completed visits", "Scheduled visits", "Arrival rate"),
      div("Net revenue", "Completed visits", "Revenue per visit"),
      div("Completed visits", "Plan-of-care completions", "Visits per episode"),
    ],
  ),
  d(
    "home-health-dashboard",
    "Home Health Agency Dashboard",
    "Home care",
    ["Branch", ["Metro", "County", "Coastal"]],
    ["Discipline", ["Nursing", "Therapy", "Aide"]],
    [
      m("Visits completed", 4200, true),
      m("Revenue", 610000),
      of("Clinician pay", "Revenue", 0.48, 0.6),
      of("Missed visits", "Visits completed", 0.02, 0.06, true),
    ],
    [
      div("Revenue", "Visits completed", "Revenue per visit"),
      div("Clinician pay", "Revenue", "Direct labor %", true),
      div("Missed visits", "Visits completed", "Missed visit rate", true),
    ],
    ["Clinician pay", "Missed visits"],
  ),
  d(
    "senior-living-dashboard",
    "Senior Living Community Dashboard",
    "Senior care",
    ["Community", ["Oak Grove", "Willow Creek", "Bayview"]],
    ["Care level", ["Independent", "Assisted", "Memory care"]],
    [
      m("Available units", 410, true),
      of("Occupied units", "Available units", 0.8, 0.95, true),
      m("Resident revenue", 1980000),
      of("Operating expenses", "Resident revenue", 0.62, 0.76),
    ],
    [
      div("Occupied units", "Available units", "Occupancy %"),
      div("Resident revenue", "Occupied units", "Revenue per occupied unit"),
      mg("Resident revenue", "Operating expenses", "Operating margin %"),
    ],
    ["Operating expenses"],
  ),
  d(
    "lab-diagnostics-dashboard",
    "Diagnostic Laboratory Dashboard",
    "Clinical labs",
    ["Test menu", ["Chemistry", "Hematology", "Molecular", "Pathology"]],
    ["Client", ["Hospitals", "Physician offices", "Direct"]],
    [
      m("Tests performed", 48000, true),
      m("Net revenue", 1250000),
      of("Reagent cost", "Net revenue", 0.16, 0.26),
      of("Results past TAT", "Tests performed", 0.02, 0.07, true),
    ],
    [
      div("Net revenue", "Tests performed", "Revenue per test"),
      div("Reagent cost", "Tests performed", "Reagent cost per test", true),
      div("Results past TAT", "Tests performed", "Turnaround breach rate", true),
    ],
    ["Reagent cost", "Results past TAT"],
  ),
  d(
    "pharma-field-sales-dashboard",
    "Pharma Field Sales Dashboard",
    "Pharmaceuticals",
    ["Territory", ["Northeast", "Southeast", "Central", "Pacific"]],
    ["Brand", ["Cardiora", "Neurex", "Immuvia"]],
    [
      m("Prescriptions (TRx)", 18200, true),
      of("New prescriptions (NRx)", "Prescriptions (TRx)", 0.22, 0.36, true),
      m("Net sales", 6300000),
      m("Rep calls", 2400, true),
    ],
    [
      div("New prescriptions (NRx)", "Prescriptions (TRx)", "NRx share of TRx"),
      div("Net sales", "Prescriptions (TRx)", "Net price per script"),
      div("Prescriptions (TRx)", "Rep calls", "Scripts per call"),
    ],
  ),
  d(
    "clinical-trials-dashboard",
    "Clinical Trial Portfolio Dashboard",
    "Clinical research",
    ["Study", ["ONC-201", "CARD-114", "NEU-309", "IMM-077"]],
    ["Region", ["North America", "Europe", "Asia-Pacific"]],
    [
      m("Patients screened", 420, true),
      of("Patients enrolled", "Patients screened", 0.3, 0.55, true),
      m("Study spend", 1850000),
      of("Protocol deviations", "Patients enrolled", 0.02, 0.09, true),
    ],
    [
      div("Patients enrolled", "Patients screened", "Screen-to-enroll rate"),
      div("Study spend", "Patients enrolled", "Cost per enrolled patient", true),
      div("Protocol deviations", "Patients enrolled", "Deviation rate", true),
    ],
    ["Study spend", "Protocol deviations"],
  ),
  d(
    "medical-device-dashboard",
    "Medical Device Sales & Quality Dashboard",
    "Medical devices",
    ["Product family", ["Orthopedic", "Cardio", "Surgical", "Imaging"]],
    ["Channel", ["Direct", "Distributor", "GPO"]],
    [
      m("Units sold", 3400, true),
      m("Revenue", 5200000),
      of("Cost of goods", "Revenue", 0.3, 0.42),
      of("Complaints", "Units sold", 0.001, 0.006, true),
    ],
    [
      mg("Revenue", "Cost of goods", "Gross margin %"),
      div("Revenue", "Units sold", "Average selling price"),
      per1k("Complaints", "Units sold", "Complaints per 1,000 units", true),
    ],
    ["Cost of goods", "Complaints"],
  ),
  d(
    "health-plan-dashboard",
    "Health Plan Medical Cost Dashboard",
    "Health insurance",
    ["Product", ["Commercial", "Medicare Advantage", "Medicaid"]],
    ["Region", ["North", "Central", "South"]],
    [
      m("Member months", 86000, true),
      m("Premium revenue", 41000000),
      of("Medical claims", "Premium revenue", 0.8, 0.9),
      of("Admin expense", "Premium revenue", 0.07, 0.11),
    ],
    [
      div("Medical claims", "Premium revenue", "Medical loss ratio", true),
      div("Medical claims", "Member months", "Claims PMPM", true),
      div("Premium revenue", "Member months", "Premium PMPM"),
    ],
    ["Medical claims", "Admin expense"],
  ),

  // ---------- Financial services ----------
  d(
    "payments-fintech-dashboard",
    "Payments Processor Dashboard",
    "Fintech payments",
    ["Merchant segment", ["SMB", "Mid-market", "Enterprise", "Platforms"]],
    ["Method", ["Card", "ACH", "Wallet"]],
    [
      m("Total payment volume", 48000000),
      of("Net revenue", "Total payment volume", 0.006, 0.012),
      m("Transactions", 1050000, true),
      of("Fraud losses", "Total payment volume", 0.0003, 0.0011),
    ],
    [
      div("Net revenue", "Total payment volume", "Net take rate"),
      div("Total payment volume", "Transactions", "Average ticket"),
      per1k("Fraud losses", "Total payment volume", "Fraud loss per $1,000 TPV", true),
    ],
    ["Fraud losses"],
  ),
  d(
    "credit-card-portfolio-dashboard",
    "Credit Card Portfolio Dashboard",
    "Consumer lending",
    ["Product", ["Rewards", "Cash back", "Secured", "Co-brand"]],
    ["FICO band", ["720+", "660-719", "<660"]],
    [
      m("Average balances", 92000000),
      of("Interest & fee income", "Average balances", 0.014, 0.022),
      of("Net charge-offs", "Average balances", 0.002, 0.006),
      m("Active accounts", 61000, true),
    ],
    [
      div("Net charge-offs", "Average balances", "Monthly charge-off rate", true),
      {
        label: "Risk-adjusted yield",
        f: (r) =>
          `(${r["Interest & fee income"]}-${r["Net charge-offs"]})/${r["Average balances"]}`,
      },
      div("Average balances", "Active accounts", "Balance per account"),
    ],
    ["Net charge-offs"],
  ),
  d(
    "mortgage-lending-dashboard",
    "Mortgage Origination Dashboard",
    "Mortgage lending",
    ["Loan officer", ["K. Ruiz", "D. Hall", "M. Chen", "S. Ward"]],
    ["Loan type", ["Conventional", "FHA", "Jumbo"]],
    [
      m("Applications", 64, true),
      of("Loans funded", "Applications", 0.55, 0.78, true),
      m("Funded volume", 18500000),
      of("Origination revenue", "Funded volume", 0.018, 0.03),
    ],
    [
      div("Loans funded", "Applications", "Pull-through rate"),
      div("Funded volume", "Loans funded", "Average loan size"),
      div("Origination revenue", "Funded volume", "Gain on sale (bps of volume)"),
    ],
  ),
  d(
    "wealth-management-dashboard",
    "Wealth Management Advisor Dashboard",
    "Wealth management",
    ["Advisor team", ["Private client", "Retirement", "Family office", "Digital"]],
    ["Account type", ["Taxable", "IRA", "Trust"]],
    [
      m("Assets under management", 210000000),
      m("Net new assets", 2400000),
      of("Advisory fees", "Assets under management", 0.0007, 0.0009),
      m("Households", 420, true),
    ],
    [
      div("Advisory fees", "Assets under management", "Monthly fee yield"),
      div("Assets under management", "Households", "AUM per household"),
      div("Net new assets", "Assets under management", "Organic growth rate"),
    ],
  ),
  d(
    "pe-portfolio-dashboard",
    "Private Equity Portfolio Monitor",
    "Private equity",
    ["Portfolio company", ["Apex Foods", "Nimbus Software", "Keystone Health", "Atlas Logistics"]],
    ["Fund", ["Fund III", "Fund IV", "Co-invest"]],
    [
      m("Revenue", 9200000),
      of("EBITDA", "Revenue", 0.12, 0.26),
      of("Interest expense", "EBITDA", 0.12, 0.3),
      of("Capex", "Revenue", 0.02, 0.06),
    ],
    [
      div("EBITDA", "Revenue", "EBITDA margin %"),
      div("EBITDA", "Interest expense", "Interest coverage (x)"),
      { label: "Cash conversion %", f: (r) => `(${r["EBITDA"]}-${r["Capex"]})/${r["EBITDA"]}` },
    ],
    ["Interest expense", "Capex"],
  ),
  d(
    "ar-collections-dashboard",
    "Accounts Receivable Collections Dashboard",
    "Credit & collections",
    ["Collector", ["Team A", "Team B", "Team C", "Agency"]],
    ["Customer tier", ["Strategic", "Mid-market", "Small business"]],
    [
      m("Invoiced", 2900000),
      of("Collected", "Invoiced", 0.82, 0.97),
      of("Past-due over 60 days", "Invoiced", 0.03, 0.1),
      of("Write-offs", "Invoiced", 0.002, 0.008),
    ],
    [
      div("Collected", "Invoiced", "Collection effectiveness"),
      div("Past-due over 60 days", "Invoiced", "60+ day past-due %", true),
      div("Write-offs", "Invoiced", "Write-off rate", true),
    ],
    ["Past-due over 60 days", "Write-offs"],
  ),
  d(
    "procurement-dashboard",
    "Procurement Spend Dashboard",
    "Procurement",
    ["Category", ["IT & software", "Facilities", "Logistics", "Professional services"]],
    ["Buying channel", ["Contracted", "Catalog", "Spot buy"]],
    [
      m("Addressable spend", 3800000),
      of("Spend under contract", "Addressable spend", 0.62, 0.88),
      of("Negotiated savings", "Addressable spend", 0.02, 0.06),
      m("Purchase orders", 1450, true),
    ],
    [
      div("Spend under contract", "Addressable spend", "Contract compliance"),
      div("Negotiated savings", "Addressable spend", "Savings rate"),
      div("Addressable spend", "Purchase orders", "Average PO value"),
    ],
  ),

  // ---------- Professional & business services ----------
  d(
    "accounting-firm-dashboard",
    "Accounting Firm Practice Dashboard",
    "Accounting services",
    ["Service line", ["Audit", "Tax", "Advisory", "Bookkeeping"]],
    ["Client size", ["Enterprise", "Mid-market", "Small business"]],
    [
      m("Hours charged", 3900, true),
      m("Standard fees", 760000),
      of("Fees billed", "Standard fees", 0.82, 0.96),
      of("Fees collected", "Fees billed", 0.88, 0.99),
    ],
    [
      div("Fees billed", "Standard fees", "Billing realization"),
      div("Fees collected", "Fees billed", "Collection realization"),
      div("Fees billed", "Hours charged", "Effective hourly rate"),
    ],
  ),
  d(
    "staffing-agency-dashboard",
    "Staffing Agency Dashboard",
    "Staffing",
    ["Division", ["Light industrial", "Healthcare", "IT", "Office"]],
    ["Client", ["Key accounts", "Mid-size", "Local"]],
    [
      m("Billable hours", 42000, true),
      m("Bill revenue", 1950000),
      of("Pay & burden cost", "Bill revenue", 0.72, 0.82),
      m("Contractors on assignment", 280, true),
    ],
    [
      mg("Bill revenue", "Pay & burden cost", "Gross margin %"),
      div("Bill revenue", "Billable hours", "Average bill rate"),
      div("Billable hours", "Contractors on assignment", "Hours per contractor"),
    ],
    ["Pay & burden cost"],
  ),
  d(
    "recruiting-pipeline-dashboard",
    "Recruiting Pipeline Dashboard",
    "Talent acquisition",
    ["Job family", ["Engineering", "Sales", "Customer success", "G&A"]],
    ["Source", ["Referral", "Job board", "Agency"]],
    [
      m("Applicants", 860, true),
      of("Interviews", "Applicants", 0.1, 0.2, true),
      of("Offers accepted", "Interviews", 0.12, 0.28, true),
      m("Recruiting spend", 42000),
    ],
    [
      div("Interviews", "Applicants", "Applicant-to-interview rate"),
      div("Offers accepted", "Interviews", "Interview-to-hire rate"),
      div("Recruiting spend", "Offers accepted", "Cost per hire", true),
    ],
    ["Recruiting spend"],
  ),
  d(
    "architecture-firm-dashboard",
    "Architecture Firm Project Dashboard",
    "Architecture & design",
    ["Studio", ["Residential", "Commercial", "Civic"]],
    ["Phase", ["Schematic", "Design development", "Construction docs"]],
    [
      m("Fees earned", 340000),
      of("Labor cost", "Fees earned", 0.36, 0.5),
      m("Hours worked", 2600, true),
      of("Hours over budget", "Hours worked", 0.02, 0.12, true),
    ],
    [
      div("Fees earned", "Labor cost", "Net multiplier (x)"),
      div("Fees earned", "Hours worked", "Fee per hour"),
      div("Hours over budget", "Hours worked", "Budget overrun rate", true),
    ],
    ["Labor cost", "Hours over budget"],
  ),
  d(
    "engineering-services-dashboard",
    "Engineering Services Backlog Dashboard",
    "Engineering consultancy",
    ["Sector", ["Transportation", "Water", "Energy", "Buildings"]],
    ["Contract type", ["Fixed fee", "Time & materials", "Cost plus"]],
    [
      m("New awards", 1450000),
      m("Revenue burned", 1180000),
      of("Direct labor", "Revenue burned", 0.32, 0.42),
      m("Billable FTEs", 64, true),
    ],
    [
      div("New awards", "Revenue burned", "Book-to-bill (x)"),
      div("Revenue burned", "Direct labor", "Labor multiplier (x)"),
      div("Revenue burned", "Billable FTEs", "Revenue per FTE"),
    ],
    ["Direct labor"],
  ),
  d(
    "advertising-agency-dashboard",
    "Advertising Agency Media Dashboard",
    "Advertising",
    ["Client", ["Northwind", "Globex", "Initech", "Umbrella"]],
    ["Media", ["TV", "Digital", "Out-of-home"]],
    [
      m("Media billings", 1650000),
      of("Agency revenue", "Media billings", 0.08, 0.15),
      of("Staff cost", "Agency revenue", 0.55, 0.7),
      m("Campaigns live", 18, true),
    ],
    [
      div("Agency revenue", "Media billings", "Revenue as % of billings"),
      mg("Agency revenue", "Staff cost", "Operating margin %"),
      div("Agency revenue", "Campaigns live", "Revenue per campaign"),
    ],
    ["Staff cost"],
  ),
  d(
    "cleaning-services-dashboard",
    "Commercial Cleaning Services Dashboard",
    "Facility services",
    ["Route", ["Downtown", "Industrial park", "Medical row", "Schools"]],
    ["Contract", ["Nightly", "Weekly", "Specialty"]],
    [
      m("Sites serviced", 140, true),
      m("Contract revenue", 186000),
      of("Crew labor", "Contract revenue", 0.48, 0.6),
      of("Quality complaints", "Sites serviced", 0.02, 0.09, true),
    ],
    [
      div("Contract revenue", "Sites serviced", "Revenue per site"),
      div("Crew labor", "Contract revenue", "Labor cost %", true),
      div("Quality complaints", "Sites serviced", "Complaints per site", true),
    ],
    ["Crew labor", "Quality complaints"],
  ),
  d(
    "landscaping-dashboard",
    "Landscaping Business Dashboard",
    "Landscaping",
    ["Crew", ["Crew 1", "Crew 2", "Crew 3", "Design-build"]],
    ["Service", ["Maintenance", "Installs", "Snow & ice"]],
    [
      m("Jobs completed", 210, true),
      m("Revenue", 132000),
      of("Crew labor", "Revenue", 0.3, 0.42),
      of("Materials", "Revenue", 0.12, 0.22),
    ],
    [
      div("Revenue", "Jobs completed", "Revenue per job"),
      {
        label: "Job margin %",
        f: (r) => `(${r["Revenue"]}-${r["Crew labor"]}-${r["Materials"]})/${r["Revenue"]}`,
      },
      div("Crew labor", "Revenue", "Labor %", true),
    ],
    ["Crew labor", "Materials"],
  ),
  d(
    "hvac-plumbing-dashboard",
    "HVAC & Plumbing Contractor Dashboard",
    "Home services",
    ["Technician", ["L. Ortiz", "B. Grant", "C. Wu", "F. Adams"]],
    ["Job type", ["Service call", "Replacement", "Maintenance plan"]],
    [
      m("Calls run", 260, true),
      of("Sold tickets", "Calls run", 0.48, 0.72, true),
      m("Revenue", 214000),
      of("Parts & equipment", "Revenue", 0.28, 0.4),
    ],
    [
      div("Sold tickets", "Calls run", "Close rate"),
      div("Revenue", "Sold tickets", "Average ticket"),
      mg("Revenue", "Parts & equipment", "Margin after parts %"),
    ],
    ["Parts & equipment"],
  ),
  d(
    "auto-repair-dashboard",
    "Auto Repair Shop Dashboard",
    "Automotive service",
    ["Bay", ["Bay 1", "Bay 2", "Bay 3", "Quick lube"]],
    ["Service", ["Brakes", "Engine", "Tires", "Diagnostics"]],
    [
      m("Repair orders", 340, true),
      m("Billed labor hours", 610, true),
      m("Labor sales", 79000),
      m("Parts sales", 64000),
    ],
    [
      div("Labor sales", "Billed labor hours", "Effective labor rate"),
      {
        label: "Average repair order",
        f: (r) => `(${r["Labor sales"]}+${r["Parts sales"]})/${r["Repair orders"]}`,
      },
      div("Billed labor hours", "Repair orders", "Hours per repair order"),
    ],
  ),
  d(
    "security-services-dashboard",
    "Security Guard Services Dashboard",
    "Security services",
    ["Contract", ["Mall", "Hospital", "Campus", "Logistics hub"]],
    ["Shift", ["Day", "Evening", "Overnight"]],
    [
      m("Billed guard hours", 9200, true),
      m("Contract revenue", 368000),
      of("Guard wages", "Contract revenue", 0.62, 0.74),
      of("Unfilled shifts", "Billed guard hours", 0.002, 0.012, true),
    ],
    [
      div("Contract revenue", "Billed guard hours", "Bill rate"),
      mg("Contract revenue", "Guard wages", "Gross margin %"),
      per1k("Unfilled shifts", "Billed guard hours", "Unfilled shifts per 1,000 hours", true),
    ],
    ["Guard wages", "Unfilled shifts"],
  ),

  // ---------- Technology & media ----------
  d(
    "software-delivery-dashboard",
    "Software Engineering Delivery Dashboard",
    "Software engineering",
    ["Team", ["Payments", "Platform", "Mobile", "Data"]],
    ["Work type", ["Feature", "Bug", "Tech debt"]],
    [
      m("Deployments", 96, true),
      of("Failed deployments", "Deployments", 0.03, 0.12, true),
      m("Story points delivered", 210, true),
      m("Incident minutes", 380, true),
    ],
    [
      div("Failed deployments", "Deployments", "Change failure rate", true),
      div("Story points delivered", "Deployments", "Points per deploy"),
      div("Incident minutes", "Failed deployments", "Mean time to restore (min)", true),
    ],
    ["Failed deployments", "Incident minutes"],
  ),
  d(
    "cybersecurity-soc-dashboard",
    "Security Operations Center Dashboard",
    "Cybersecurity",
    ["Detection source", ["EDR", "SIEM", "Email gateway", "Cloud"]],
    ["Severity", ["Critical", "High", "Medium"]],
    [
      m("Alerts triaged", 9800, true),
      of("Confirmed incidents", "Alerts triaged", 0.004, 0.016, true),
      of("False positives", "Alerts triaged", 0.55, 0.8, true),
      m("Analyst hours", 1150, true),
    ],
    [
      div("Confirmed incidents", "Alerts triaged", "True-positive rate"),
      div("False positives", "Alerts triaged", "False-positive rate", true),
      div("Alerts triaged", "Analyst hours", "Alerts per analyst hour"),
    ],
    ["Confirmed incidents", "False positives"],
  ),
  d(
    "cloud-finops-dashboard",
    "Cloud Cost (FinOps) Dashboard",
    "Cloud infrastructure",
    ["Business unit", ["Product", "Data", "Platform", "Corporate IT"]],
    ["Provider", ["AWS", "Azure", "GCP"]],
    [
      m("Cloud spend", 420000),
      of("Committed-use coverage", "Cloud spend", 0.48, 0.78),
      of("Idle resources", "Cloud spend", 0.04, 0.14),
      m("Customer transactions (000s)", 52000, true),
    ],
    [
      div("Committed-use coverage", "Cloud spend", "Commitment coverage %"),
      div("Idle resources", "Cloud spend", "Waste %", true),
      per1k("Cloud spend", "Customer transactions (000s)", "Cost per million transactions", true),
    ],
    ["Cloud spend", "Idle resources"],
  ),
  d(
    "mobile-app-dashboard",
    "Mobile App Growth Dashboard",
    "Consumer apps",
    ["Platform", ["iOS", "Android", "Web"]],
    ["Acquisition", ["Organic", "Paid", "Referral"]],
    [
      m("Installs", 86000, true),
      of("Day-30 retained users", "Installs", 0.12, 0.28, true),
      m("In-app revenue", 214000),
      m("User acquisition spend", 118000),
    ],
    [
      div("Day-30 retained users", "Installs", "Day-30 retention"),
      div("User acquisition spend", "Installs", "Cost per install", true),
      div("In-app revenue", "User acquisition spend", "Revenue / UA spend (x)"),
    ],
    ["User acquisition spend"],
  ),
  d(
    "gaming-studio-dashboard",
    "Live-service Game Dashboard",
    "Video games",
    ["Title", ["Skyforge", "Pocket Racers", "Neon Tactics"]],
    ["Platform", ["Console", "PC", "Mobile"]],
    [
      m("Monthly active users", 640000, true),
      of("Paying users", "Monthly active users", 0.02, 0.06, true),
      m("Net bookings", 2350000),
      m("Live-ops cost", 610000),
    ],
    [
      div("Paying users", "Monthly active users", "Payer conversion"),
      div("Net bookings", "Monthly active users", "ARPMAU"),
      div("Net bookings", "Paying users", "ARPPU"),
    ],
    ["Live-ops cost"],
  ),
  d(
    "streaming-media-dashboard",
    "Streaming Service Subscriber Dashboard",
    "Streaming media",
    ["Market", ["US & Canada", "LATAM", "EMEA", "APAC"]],
    ["Plan", ["Ad-supported", "Standard", "Premium"]],
    [
      m("Paid subscribers", 2900000, true),
      of("Cancellations", "Paid subscribers", 0.018, 0.04, true),
      m("Subscription revenue", 31000000),
      m("Content amortization", 17500000),
    ],
    [
      div("Cancellations", "Paid subscribers", "Monthly churn", true),
      div("Subscription revenue", "Paid subscribers", "ARPU"),
      div("Content amortization", "Subscription revenue", "Content cost %", true),
    ],
    ["Cancellations", "Content amortization"],
  ),
  d(
    "publishing-dashboard",
    "Digital Publishing Dashboard",
    "News & publishing",
    ["Section", ["News", "Sports", "Business", "Lifestyle"]],
    ["Revenue stream", ["Subscriptions", "Display ads", "Sponsorship"]],
    [
      m("Page views", 9400000, true),
      m("Ad revenue", 186000),
      m("Digital subscribers", 41000, true),
      m("Subscription revenue", 312000),
    ],
    [
      per1k("Ad revenue", "Page views", "Ad RPM"),
      div("Subscription revenue", "Digital subscribers", "Revenue per subscriber"),
      {
        label: "Reader revenue share",
        f: (r) => `${r["Subscription revenue"]}/(${r["Subscription revenue"]}+${r["Ad revenue"]})`,
      },
    ],
  ),
  d(
    "cinema-dashboard",
    "Cinema Chain Dashboard",
    "Movie theaters",
    ["Theater", ["Grand 12", "Riverside 8", "IMAX Plaza"]],
    ["Format", ["Standard", "IMAX", "Premium recliner"]],
    [
      m("Attendance", 64000, true),
      m("Box office", 820000),
      of("Film rent", "Box office", 0.48, 0.58),
      m("Concession sales", 410000),
    ],
    [
      div("Box office", "Attendance", "Average ticket price"),
      div("Concession sales", "Attendance", "Concession per patron"),
      div("Film rent", "Box office", "Film rent %", true),
    ],
    ["Film rent"],
  ),
  d(
    "podcast-network-dashboard",
    "Podcast & Audio Network Dashboard",
    "Audio media",
    ["Show", ["Daily Brief", "True Crime Hour", "Founders", "Game Night"]],
    ["Sales channel", ["Direct", "Programmatic", "Network"]],
    [
      m("Downloads", 2100000, true),
      of("Sold impressions", "Downloads", 0.6, 0.9, true),
      m("Ad revenue", 64000),
      of("Talent share", "Ad revenue", 0.35, 0.5),
    ],
    [
      div("Sold impressions", "Downloads", "Sell-through %"),
      per1k("Ad revenue", "Sold impressions", "Effective CPM"),
      mg("Ad revenue", "Talent share", "Network margin %"),
    ],
    ["Talent share"],
  ),

  // ---------- Leisure, sports & culture ----------
  d(
    "sports-team-dashboard",
    "Pro Sports Team Business Dashboard",
    "Sports franchise",
    ["Revenue line", ["Ticketing", "Sponsorship", "Merchandise", "Hospitality"]],
    ["Opponent tier", ["Rivalry", "Marquee", "Standard"]],
    [
      m("Revenue", 3100000),
      m("Tickets sold", 61000, true),
      of("Arena capacity", "Tickets sold", 1.05, 1.3, true),
      m("Game-day cost", 940000),
    ],
    [
      div("Tickets sold", "Arena capacity", "Attendance %"),
      div("Revenue", "Tickets sold", "Revenue per attendee"),
      mg("Revenue", "Game-day cost", "Game-day margin %"),
    ],
    ["Game-day cost"],
  ),
  d(
    "golf-club-dashboard",
    "Golf & Country Club Dashboard",
    "Private clubs",
    ["Department", ["Golf", "Food & beverage", "Pro shop", "Events"]],
    ["Member type", ["Full", "Social", "Junior"]],
    [
      m("Rounds played", 3600, true),
      m("Department revenue", 312000),
      of("Department payroll", "Department revenue", 0.3, 0.45),
      m("Active members", 540, true),
    ],
    [
      div("Department revenue", "Active members", "Revenue per member"),
      div("Rounds played", "Active members", "Rounds per member"),
      div("Department payroll", "Department revenue", "Payroll %", true),
    ],
    ["Department payroll"],
  ),
  d(
    "ski-resort-dashboard",
    "Ski Resort Season Dashboard",
    "Mountain resorts",
    ["Revenue center", ["Lift tickets", "Ski school", "Rentals", "Lodging"]],
    ["Guest type", ["Season pass", "Day visitor", "Destination"]],
    [
      m("Skier visits", 42000, true),
      m("Revenue", 2600000),
      of("Resort operating cost", "Revenue", 0.55, 0.72),
      m("Snowmaking hours", 520, true),
    ],
    [
      div("Revenue", "Skier visits", "Revenue per skier visit"),
      mg("Revenue", "Resort operating cost", "Resort EBITDA margin %"),
      div("Resort operating cost", "Skier visits", "Cost per visit", true),
    ],
    ["Resort operating cost"],
  ),
  d(
    "theme-park-dashboard",
    "Theme Park Attendance Dashboard",
    "Attractions",
    ["Park zone", ["Adventure", "Waterpark", "Kids land", "Main street"]],
    ["Ticket type", ["Day ticket", "Annual pass", "Group"]],
    [
      m("Attendance", 128000, true),
      m("Admissions revenue", 6100000),
      m("In-park spending", 3300000),
      of("Ride downtime hours", "Attendance", 0.0005, 0.002),
    ],
    [
      div("Admissions revenue", "Attendance", "Per-capita admission"),
      div("In-park spending", "Attendance", "Per-capita in-park spend"),
      per1k("Ride downtime hours", "Attendance", "Downtime hours per 1,000 guests", true),
    ],
    ["Ride downtime hours"],
  ),
  d(
    "museum-dashboard",
    "Museum & Cultural Venue Dashboard",
    "Arts & culture",
    ["Program", ["Permanent collection", "Special exhibition", "Education", "Events"]],
    ["Visitor type", ["Member", "General", "School group"]],
    [
      m("Visitors", 21000, true),
      m("Earned revenue", 214000),
      m("Contributed revenue", 160000),
      m("Operating expense", 330000),
    ],
    [
      div("Earned revenue", "Visitors", "Earned revenue per visitor"),
      { label: "Self-sufficiency %", f: (r) => `${r["Earned revenue"]}/${r["Operating expense"]}` },
      {
        label: "Operating surplus %",
        f: (r) =>
          `(${r["Earned revenue"]}+${r["Contributed revenue"]}-${r["Operating expense"]})/${r["Operating expense"]}`,
      },
    ],
    ["Operating expense"],
  ),

  // ---------- Education & community ----------
  d(
    "school-district-dashboard",
    "K-12 School District Dashboard",
    "Public education",
    ["School", ["Lincoln Elementary", "Roosevelt Middle", "Central High", "Westside High"]],
    ["Program", ["General", "Special education", "English learners"]],
    [
      m("Enrolled students", 640, true),
      of("Average daily attendance", "Enrolled students", 0.9, 0.96, true),
      m("Instructional spending", 610000),
      m("Teachers (FTE)", 42, true),
    ],
    [
      div("Average daily attendance", "Enrolled students", "Attendance rate"),
      div("Instructional spending", "Enrolled students", "Spending per student"),
      div("Enrolled students", "Teachers (FTE)", "Students per teacher", true),
    ],
  ),
  d(
    "online-courses-dashboard",
    "Online Learning Platform Dashboard",
    "EdTech",
    ["Course area", ["Data science", "Design", "Business", "Languages"]],
    ["Learner type", ["Consumer", "Enterprise seat", "Scholarship"]],
    [
      m("Enrollments", 18600, true),
      of("Completions", "Enrollments", 0.18, 0.42, true),
      m("Course revenue", 410000),
      m("Marketing spend", 96000),
    ],
    [
      div("Completions", "Enrollments", "Completion rate"),
      div("Course revenue", "Enrollments", "Revenue per enrollment"),
      div("Marketing spend", "Enrollments", "Acquisition cost per enrollment", true),
    ],
    ["Marketing spend"],
  ),
  d(
    "childcare-center-dashboard",
    "Childcare Center Dashboard",
    "Early education",
    ["Center", ["Maple", "Cedar", "Birch"]],
    ["Age group", ["Infants", "Toddlers", "Pre-K"]],
    [
      m("Licensed capacity", 120, true),
      of("Enrolled children", "Licensed capacity", 0.8, 0.98, true),
      m("Tuition revenue", 168000),
      of("Staff payroll", "Tuition revenue", 0.55, 0.68),
    ],
    [
      div("Enrolled children", "Licensed capacity", "Enrollment utilization"),
      div("Tuition revenue", "Enrolled children", "Tuition per child"),
      div("Staff payroll", "Tuition revenue", "Payroll %", true),
    ],
    ["Staff payroll"],
  ),
  d(
    "city-services-dashboard",
    "City Services Performance Dashboard",
    "Local government",
    ["Department", ["Public works", "Parks", "Permits", "311 center"]],
    ["District", ["District 1", "District 2", "District 3"]],
    [
      m("Service requests", 3100, true),
      of("Closed within target", "Service requests", 0.7, 0.92, true),
      m("Department spending", 840000),
      m("Resident satisfaction responses", 640, true),
    ],
    [
      div("Closed within target", "Service requests", "On-target closure rate"),
      div("Department spending", "Service requests", "Cost per request", true),
      div("Service requests", "Resident satisfaction responses", "Requests per survey response"),
    ],
  ),

  // ---------- Real estate & construction ----------
  d(
    "residential-property-dashboard",
    "Residential Property Management Dashboard",
    "Multifamily",
    ["Community", ["Elm Court", "Harbor Lofts", "Pine Ridge", "Union Flats"]],
    ["Unit type", ["Studio", "1-bed", "2-bed"]],
    [
      m("Units", 240, true),
      of("Occupied units", "Units", 0.9, 0.98, true),
      m("Rent collected", 410000),
      of("Maintenance cost", "Rent collected", 0.08, 0.15),
    ],
    [
      div("Occupied units", "Units", "Physical occupancy"),
      div("Rent collected", "Occupied units", "Effective rent per unit"),
      div("Maintenance cost", "Units", "Maintenance per unit", true),
    ],
    ["Maintenance cost"],
  ),
  d(
    "homebuilder-dashboard",
    "Homebuilder Sales & Closings Dashboard",
    "Residential construction",
    ["Community", ["Sunset Ridge", "Meadowbrook", "Canyon View"]],
    ["Product", ["Townhome", "Single-family", "Luxury"]],
    [
      m("Net orders", 22, true),
      of("Closings", "Net orders", 0.7, 1.05, true),
      m("Home sales revenue", 9800000),
      of("Construction cost", "Home sales revenue", 0.72, 0.8),
    ],
    [
      div("Home sales revenue", "Closings", "Average selling price"),
      mg("Home sales revenue", "Construction cost", "Homebuilding gross margin %"),
      div("Net orders", "Closings", "Orders-to-closings (x)"),
    ],
    ["Construction cost"],
  ),
  d(
    "coworking-dashboard",
    "Coworking Space Dashboard",
    "Flexible workspace",
    ["Location", ["SoHo", "Tech Park", "Midtown"]],
    ["Membership", ["Hot desk", "Dedicated desk", "Private office"]],
    [
      m("Desks available", 620, true),
      of("Desks occupied", "Desks available", 0.62, 0.9, true),
      m("Membership revenue", 286000),
      m("Lease & operating cost", 214000),
    ],
    [
      div("Desks occupied", "Desks available", "Desk occupancy"),
      div("Membership revenue", "Desks occupied", "Revenue per occupied desk"),
      mg("Membership revenue", "Lease & operating cost", "Site margin %"),
    ],
    ["Lease & operating cost"],
  ),
  d(
    "self-storage-dashboard",
    "Self-storage Facility Dashboard",
    "Self-storage",
    ["Facility", ["Route 9", "Lakeside", "Industrial Ave", "Northgate"]],
    ["Unit size", ["5x5", "10x10", "10x20"]],
    [
      m("Rentable sq ft", 72000, true),
      of("Occupied sq ft", "Rentable sq ft", 0.82, 0.95, true),
      m("Rental revenue", 96000),
      of("Operating expenses", "Rental revenue", 0.3, 0.4),
    ],
    [
      div("Occupied sq ft", "Rentable sq ft", "Economic occupancy"),
      div("Rental revenue", "Occupied sq ft", "Revenue per occupied sq ft"),
      mg("Rental revenue", "Operating expenses", "NOI margin %"),
    ],
    ["Operating expenses"],
  ),
  d(
    "parking-operations-dashboard",
    "Parking Operations Dashboard",
    "Parking",
    ["Facility", ["Garage A", "Garage B", "Surface lot", "Stadium lot"]],
    ["Customer", ["Transient", "Monthly", "Event"]],
    [
      m("Spaces", 900, true),
      m("Vehicles parked", 21000, true),
      m("Parking revenue", 168000),
      of("Operating cost", "Parking revenue", 0.36, 0.5),
    ],
    [
      div("Parking revenue", "Spaces", "Revenue per space"),
      div("Parking revenue", "Vehicles parked", "Average ticket"),
      mg("Parking revenue", "Operating cost", "Operating margin %"),
    ],
    ["Operating cost"],
  ),

  // ---------- Logistics & supply chain ----------
  d(
    "warehouse-3pl-dashboard",
    "3PL Warehouse Operations Dashboard",
    "Third-party logistics",
    ["Client", ["Acme Retail", "BrightHome", "FitGear", "PetCo-op"]],
    ["Activity", ["Receiving", "Pick & pack", "Returns"]],
    [
      m("Orders shipped", 38000, true),
      of("Order errors", "Orders shipped", 0.001, 0.006, true),
      m("Labor hours", 6400, true),
      m("Fulfillment revenue", 214000),
    ],
    [
      div("Orders shipped", "Labor hours", "Orders per labor hour"),
      per1k("Order errors", "Orders shipped", "Errors per 1,000 orders", true),
      div("Fulfillment revenue", "Orders shipped", "Revenue per order"),
    ],
    ["Order errors", "Labor hours"],
  ),
  d(
    "freight-forwarding-dashboard",
    "Freight Forwarding Dashboard",
    "Freight forwarding",
    ["Trade lane", ["Asia–US West", "Asia–Europe", "Transatlantic", "Intra-Asia"]],
    ["Mode", ["Ocean FCL", "Ocean LCL", "Air"]],
    [
      m("Shipments", 1250, true),
      m("Revenue", 3900000),
      of("Carrier cost", "Revenue", 0.78, 0.88),
      of("Late arrivals", "Shipments", 0.05, 0.16, true),
    ],
    [
      mg("Revenue", "Carrier cost", "Net revenue margin %"),
      {
        label: "Net revenue per shipment",
        f: (r) => `(${r["Revenue"]}-${r["Carrier cost"]})/${r["Shipments"]}`,
      },
      div("Late arrivals", "Shipments", "Late arrival rate", true),
    ],
    ["Carrier cost", "Late arrivals"],
  ),
  d(
    "port-terminal-dashboard",
    "Container Port Terminal Dashboard",
    "Ports",
    ["Berth", ["Berth 1", "Berth 2", "Berth 3"]],
    ["Service", ["Transpacific", "Feeder", "Coastal"]],
    [
      m("Containers handled (TEU)", 82000, true),
      m("Crane hours", 2100, true),
      m("Terminal revenue", 9400000),
      of("Terminal operating cost", "Terminal revenue", 0.55, 0.68),
    ],
    [
      div("Containers handled (TEU)", "Crane hours", "Moves per crane hour"),
      div("Terminal revenue", "Containers handled (TEU)", "Revenue per TEU"),
      mg("Terminal revenue", "Terminal operating cost", "Terminal margin %"),
    ],
    ["Terminal operating cost"],
  ),
  d(
    "rail-freight-dashboard",
    "Rail Freight Operations Dashboard",
    "Railroads",
    ["Commodity", ["Intermodal", "Coal", "Grain", "Chemicals"]],
    ["Corridor", ["East", "Central", "West"]],
    [
      m("Carloads", 46000, true),
      m("Freight revenue", 118000000),
      of("Operating expenses", "Freight revenue", 0.58, 0.68),
      m("Train miles", 2100000, true),
    ],
    [
      div("Operating expenses", "Freight revenue", "Operating ratio", true),
      div("Freight revenue", "Carloads", "Revenue per carload"),
      div("Carloads", "Train miles", "Carloads per train mile"),
    ],
    ["Operating expenses"],
  ),
  d(
    "courier-last-mile-dashboard",
    "Last-mile Courier Dashboard",
    "Parcel delivery",
    ["Hub", ["North hub", "South hub", "Airport hub", "Downtown"]],
    ["Service", ["Standard", "Express", "Same-day"]],
    [
      m("Parcels delivered", 142000, true),
      of("First-attempt deliveries", "Parcels delivered", 0.88, 0.97, true),
      m("Delivery revenue", 690000),
      m("Route hours", 9800, true),
    ],
    [
      div("First-attempt deliveries", "Parcels delivered", "First-attempt success"),
      div("Parcels delivered", "Route hours", "Stops per route hour"),
      div("Delivery revenue", "Parcels delivered", "Revenue per parcel"),
    ],
  ),
  d(
    "b2b-distributor-dashboard",
    "Wholesale Distributor Dashboard",
    "Wholesale distribution",
    ["Branch", ["Central DC", "East branch", "West branch", "Online"]],
    ["Product group", ["Electrical", "Plumbing", "HVAC"]],
    [
      m("Sales", 1850000),
      of("Cost of sales", "Sales", 0.74, 0.82),
      m("Order lines", 24000, true),
      of("Inventory on hand", "Sales", 1.6, 2.4),
    ],
    [
      mg("Sales", "Cost of sales", "Gross margin %"),
      div("Sales", "Order lines", "Revenue per order line"),
      {
        label: "Inventory turns (annualized)",
        f: (r) => `${r["Cost of sales"]}*12/${r["Inventory on hand"]}`,
      },
    ],
    ["Cost of sales", "Inventory on hand"],
  ),

  // ---------- Energy, resources & industrials ----------
  d(
    "oil-gas-upstream-dashboard",
    "Upstream Oil & Gas Production Dashboard",
    "Oil & gas",
    ["Field", ["Permian A", "Permian B", "Eagle Ford", "Bakken"]],
    ["Product", ["Oil", "Gas", "NGLs"]],
    [
      m("Production (boe)", 210000, true),
      m("Realized revenue", 13200000),
      of("Lease operating expense", "Realized revenue", 0.14, 0.24),
      of("Downtime hours", "Production (boe)", 0.0008, 0.003),
    ],
    [
      div("Realized revenue", "Production (boe)", "Realized price per boe"),
      div("Lease operating expense", "Production (boe)", "LOE per boe", true),
      {
        label: "Cash netback per boe",
        f: (r) =>
          `(${r["Realized revenue"]}-${r["Lease operating expense"]})/${r["Production (boe)"]}`,
      },
    ],
    ["Lease operating expense", "Downtime hours"],
  ),
  d(
    "refinery-dashboard",
    "Refinery Operations Dashboard",
    "Refining",
    ["Unit", ["Crude unit", "FCC", "Hydrocracker", "Reformer"]],
    ["Product slate", ["Gasoline", "Diesel", "Jet fuel"]],
    [
      m("Crude throughput (bbl)", 2900000, true),
      of("Capacity (bbl)", "Crude throughput (bbl)", 1.05, 1.18, true),
      m("Product revenue", 268000000),
      of("Crude & feedstock cost", "Product revenue", 0.84, 0.91),
    ],
    [
      div("Crude throughput (bbl)", "Capacity (bbl)", "Utilization"),
      {
        label: "Gross margin per barrel",
        f: (r) =>
          `(${r["Product revenue"]}-${r["Crude & feedstock cost"]})/${r["Crude throughput (bbl)"]}`,
      },
      mg("Product revenue", "Crude & feedstock cost", "Refining margin %"),
    ],
    ["Crude & feedstock cost"],
  ),
  d(
    "solar-installer-dashboard",
    "Solar Installer Dashboard",
    "Solar installation",
    ["Region", ["Coastal", "Inland", "Desert", "Metro"]],
    ["Customer", ["Residential", "Commercial", "Community solar"]],
    [
      m("kW installed", 1450, true),
      m("Installation revenue", 4100000),
      of("Equipment cost", "Installation revenue", 0.42, 0.54),
      m("Signed contracts", 96, true),
    ],
    [
      div("Installation revenue", "kW installed", "Revenue per kW"),
      mg("Installation revenue", "Equipment cost", "Gross margin %"),
      div("kW installed", "Signed contracts", "Average system size (kW)"),
    ],
    ["Equipment cost"],
  ),
  d(
    "wind-farm-dashboard",
    "Wind Farm Performance Dashboard",
    "Wind power",
    ["Site", ["Ridge North", "Ridge South", "Prairie", "Offshore 1"]],
    ["Turbine model", ["V150", "SG 6.6", "GE 3.x"]],
    [
      m("Net generation (MWh)", 38000, true),
      of("Potential generation (MWh)", "Net generation (MWh)", 1.04, 1.14, true),
      m("Energy revenue", 1850000),
      m("O&M cost", 410000),
    ],
    [
      div("Net generation (MWh)", "Potential generation (MWh)", "Energy-based availability"),
      div("Energy revenue", "Net generation (MWh)", "Realized price per MWh"),
      div("O&M cost", "Net generation (MWh)", "O&M cost per MWh", true),
    ],
    ["O&M cost"],
  ),
  d(
    "water-utility-dashboard",
    "Water Utility Dashboard",
    "Water utilities",
    ["Pressure zone", ["Zone 1", "Zone 2", "Zone 3", "Zone 4"]],
    ["Customer class", ["Residential", "Commercial", "Irrigation"]],
    [
      m("Water produced (kgal)", 210000, true),
      of("Water billed (kgal)", "Water produced (kgal)", 0.82, 0.92, true),
      m("Water revenue", 1450000),
      m("Main breaks", 6, true),
    ],
    [
      {
        label: "Non-revenue water %",
        f: (r) =>
          `(${r["Water produced (kgal)"]}-${r["Water billed (kgal)"]})/${r["Water produced (kgal)"]}`,
        lowerBetter: true,
      },
      div("Water revenue", "Water billed (kgal)", "Revenue per kgal"),
      {
        label: "Main breaks per 100k kgal",
        f: (r) => `${r["Main breaks"]}/${r["Water produced (kgal)"]}*100000`,
        lowerBetter: true,
      },
    ],
    ["Main breaks"],
  ),
  d(
    "waste-management-dashboard",
    "Waste Collection & Recycling Dashboard",
    "Environmental services",
    ["Line of business", ["Residential", "Commercial", "Roll-off", "Recycling"]],
    ["Market", ["North county", "City", "South county"]],
    [
      m("Tons collected", 21000, true),
      of("Tons diverted", "Tons collected", 0.18, 0.4, true),
      m("Collection revenue", 2350000),
      of("Disposal & fleet cost", "Collection revenue", 0.5, 0.64),
    ],
    [
      div("Tons diverted", "Tons collected", "Diversion rate"),
      div("Collection revenue", "Tons collected", "Revenue per ton"),
      mg("Collection revenue", "Disposal & fleet cost", "Operating margin %"),
    ],
    ["Disposal & fleet cost"],
  ),
  d(
    "chemical-plant-dashboard",
    "Specialty Chemicals Plant Dashboard",
    "Chemicals",
    ["Product", ["Resins", "Coatings", "Adhesives", "Solvents"]],
    ["Reactor", ["R-101", "R-102", "R-201"]],
    [
      m("Tons produced", 4200, true),
      of("Off-spec tons", "Tons produced", 0.01, 0.04, true),
      m("Net sales", 9800000),
      of("Raw material cost", "Net sales", 0.5, 0.62),
    ],
    [
      {
        label: "First-pass quality %",
        f: (r) => `(${r["Tons produced"]}-${r["Off-spec tons"]})/${r["Tons produced"]}`,
      },
      mg("Net sales", "Raw material cost", "Variable margin %"),
      div("Net sales", "Tons produced", "Price per ton"),
    ],
    ["Off-spec tons", "Raw material cost"],
  ),
  d(
    "food-processing-dashboard",
    "Food Processing Plant Dashboard",
    "Food manufacturing",
    ["Line", ["Snacks line", "Frozen line", "Sauces line"]],
    ["Customer", ["Retail", "Foodservice", "Private label"]],
    [
      m("Cases produced", 128000, true),
      of("Planned cases", "Cases produced", 1.02, 1.15, true),
      m("Net sales", 2350000),
      of("Ingredient & packaging cost", "Net sales", 0.52, 0.64),
    ],
    [
      div("Cases produced", "Planned cases", "Schedule attainment"),
      div("Ingredient & packaging cost", "Cases produced", "Material cost per case", true),
      mg("Net sales", "Ingredient & packaging cost", "Material margin %"),
    ],
    ["Ingredient & packaging cost"],
  ),
  d(
    "apparel-manufacturing-dashboard",
    "Apparel Factory Dashboard",
    "Apparel manufacturing",
    ["Production line", ["Line A", "Line B", "Line C", "Line D"]],
    ["Style", ["T-shirts", "Denim", "Outerwear"]],
    [
      m("Garments produced", 46000, true),
      of("Defects", "Garments produced", 0.01, 0.04, true),
      m("Standard minutes earned", 410000, true),
      of("Minutes attended", "Standard minutes earned", 1.25, 1.6, true),
    ],
    [
      div("Standard minutes earned", "Minutes attended", "Line efficiency"),
      div("Defects", "Garments produced", "Defect rate", true),
      div("Standard minutes earned", "Garments produced", "Standard minutes per garment"),
    ],
    ["Defects"],
  ),
  d(
    "electronics-ems-dashboard",
    "Electronics Contract Manufacturing Dashboard",
    "EMS manufacturing",
    ["Customer program", ["Medical", "Automotive", "Industrial", "Consumer"]],
    ["Site", ["Guadalajara", "Penang", "Austin"]],
    [
      m("Boards built", 61000, true),
      of("First-pass yield boards", "Boards built", 0.93, 0.99, true),
      m("Revenue", 8400000),
      of("Component cost", "Revenue", 0.68, 0.78),
    ],
    [
      div("First-pass yield boards", "Boards built", "First-pass yield"),
      div("Revenue", "Boards built", "Revenue per board"),
      mg("Revenue", "Component cost", "Value-add margin %"),
    ],
    ["Component cost"],
  ),
  d(
    "printing-packaging-dashboard",
    "Printing & Packaging Plant Dashboard",
    "Commercial printing",
    ["Press", ["Offset 1", "Offset 2", "Digital", "Flexo"]],
    ["Job type", ["Labels", "Cartons", "Brochures"]],
    [
      m("Impressions (000s)", 9200, true),
      m("Jobs completed", 410, true),
      m("Revenue", 610000),
      of("Paper & ink cost", "Revenue", 0.34, 0.46),
    ],
    [
      div("Revenue", "Jobs completed", "Revenue per job"),
      mg("Revenue", "Paper & ink cost", "Margin over materials %"),
      div("Impressions (000s)", "Jobs completed", "Impressions per job (000s)"),
    ],
    ["Paper & ink cost"],
  ),

  // ---------- Agriculture ----------
  d(
    "dairy-farm-dashboard",
    "Dairy Farm Dashboard",
    "Dairy",
    ["Herd group", ["Fresh cows", "High producers", "Late lactation"]],
    ["Barn", ["Barn 1", "Barn 2", "Barn 3"]],
    [
      m("Cows milked", 410, true),
      m("Milk shipped (cwt)", 9200, true),
      m("Milk revenue", 186000),
      of("Feed cost", "Milk revenue", 0.42, 0.56),
    ],
    [
      div("Milk shipped (cwt)", "Cows milked", "Cwt per cow"),
      div("Milk revenue", "Milk shipped (cwt)", "Mailbox price per cwt"),
      {
        label: "Income over feed cost per cow",
        f: (r) => `(${r["Milk revenue"]}-${r["Feed cost"]})/${r["Cows milked"]}`,
      },
    ],
    ["Feed cost"],
  ),
  d(
    "winery-dtc-dashboard",
    "Winery Tasting Room & Club Dashboard",
    "Wine",
    ["Channel", ["Tasting room", "Wine club", "E-commerce", "Wholesale"]],
    ["Varietal", ["Cabernet", "Chardonnay", "Pinot noir"]],
    [
      m("Visitors", 2400, true),
      of("Club sign-ups", "Visitors", 0.03, 0.08, true),
      m("Cases sold", 820, true),
      m("Wine revenue", 214000),
    ],
    [
      div("Club sign-ups", "Visitors", "Club conversion"),
      div("Wine revenue", "Cases sold", "Revenue per case"),
      div("Wine revenue", "Visitors", "Revenue per visitor"),
    ],
  ),
  d(
    "greenhouse-dashboard",
    "Greenhouse Grower Dashboard",
    "Controlled-environment agriculture",
    ["Greenhouse", ["House 1", "House 2", "House 3", "House 4"]],
    ["Crop", ["Tomatoes", "Lettuce", "Herbs"]],
    [
      m("Growing sq ft", 42000, true),
      m("Pounds harvested", 61000, true),
      m("Crop revenue", 118000),
      of("Energy cost", "Crop revenue", 0.12, 0.22),
    ],
    [
      div("Pounds harvested", "Growing sq ft", "Yield per sq ft (lb)"),
      div("Crop revenue", "Pounds harvested", "Price per lb"),
      div("Energy cost", "Pounds harvested", "Energy cost per lb", true),
    ],
    ["Energy cost"],
  ),
];

export const MORE_DASHBOARD_TEMPLATES: FinancialTemplate[] = SPECS.map(kpiDashboard);
