import { S, type FinancialTemplate } from "./types";

/**
 * Institutional-grade sector models.
 * Architectural rules enforced in every build:
 *  - zero hardcoded integers inside calculations (all drivers live on an Assumptions tab)
 *  - a CHOOSE/INDEX-driven Active Case switch flowing through the workbook
 *  - a frozen check block plus an Audit tab aggregating to a master TRUE/FALSE
 *  - IFERROR wrappers on every ratio so downloads never show #DIV/0! or #REF!
 */

const CASE_BLOCK: (string | number)[][] = [
  ["ACTIVE CASE SWITCH", "Base", "Upside", "Downside"],
  ["Selected case", "Base", "", ""],
  ["Case index", '=IFERROR(MATCH($B$2,$B$1:$D$1,0),1)', "", ""],
];

export const INSTITUTIONAL_TEMPLATES: FinancialTemplate[] = [
  {
    id: "vc-cap-table",
    name: "VC Cap Table & Exit Waterfall",
    tier: "Institutional",
    blurb:
      "Multi-round cap table with SAFEs, convertible notes, options and liquidation preferences plus a full exit payout waterfall.",
    features: ["SAFE & note conversion", "Liquidation preferences", "Anti-dilution", "Exit waterfall"],
    prompt:
      "Add a participating-preferred cap with a 2x liquidation preference and a per-round IRR/MoIC return summary to this cap table.",
    build: () => [
      S("Assumptions", [
        ...CASE_BLOCK,
        [],
        ["Driver", "Value", "Validation"],
        ["Exit valuation", 480000000, "Numeric > 0"],
        ["Option pool %", 0.12, "0 to 0.3"],
        ["SAFE discount", 0.2, "0 to 0.35"],
        ["SAFE valuation cap", 40000000],
        ["Note interest rate", 0.06],
        ["Note term (yrs)", 2],
        ["Preferred participation", "Non-participating", "Participating / Non-participating"],
        ["Exit case multiplier", '=IFERROR(CHOOSE($B$3,1,1.6,0.45),1)'],
        ["Adjusted exit value", "=B6*B13"],
      ]),
      S("Cap Table", [
        ["CAPITALIZATION TABLE"],
        [],
        ["Holder", "Security", "Invested", "Shares", "Liq. pref (x)", "Ownership %", "As-converted %"],
        ["Founders", "Common", 0, 8000000, 0, "=IFERROR(D4/$D$12,0)", "=IFERROR(D4/$D$12,0)"],
        ["Seed investors", "Preferred A", 4000000, 2200000, 1, "=IFERROR(D5/$D$12,0)", "=IFERROR(D5/$D$12,0)"],
        ["Series A", "Preferred B", 12000000, 3100000, 1, "=IFERROR(D6/$D$12,0)", "=IFERROR(D6/$D$12,0)"],
        ["Series B", "Preferred C", 30000000, 4400000, 1, "=IFERROR(D7/$D$12,0)", "=IFERROR(D7/$D$12,0)"],
        ["SAFE holders", "SAFE", 3000000, "=IFERROR(C8/(Assumptions!$B$9*(1-Assumptions!$B$8)/1000000*1),0)", 1, "=IFERROR(D8/$D$12,0)", "=IFERROR(D8/$D$12,0)"],
        ["Convertible notes", "Note", 2500000, "=IFERROR(C9*(1+Assumptions!$B$10)^Assumptions!$B$11/(Assumptions!$B$9/1000000),0)", 1, "=IFERROR(D9/$D$12,0)", "=IFERROR(D9/$D$12,0)"],
        ["Option pool", "Options", 0, "=IFERROR(SUM(D4:D9)/(1-Assumptions!$B$7)*Assumptions!$B$7,0)", 0, "=IFERROR(D10/$D$12,0)", "=IFERROR(D10/$D$12,0)"],
        [],
        ["Total", "", "=SUM(C4:C10)", "=SUM(D4:D10)", "", "=SUM(F4:F10)", "=SUM(G4:G10)"],
      ]),
      S("Exit Waterfall", [
        ["EXIT PAYOUT WATERFALL"],
        [],
        ["Exit value", "=Assumptions!$B$14"],
        [],
        ["Holder", "Liquidation preference", "Pro-rata participation", "Payout", "MoIC"],
        ...[5, 6, 7, 8, 9].map((src, i) => {
          const r = 6 + i;
          return [
            `='Cap Table'!A${src}`,
            `=IFERROR('Cap Table'!C${src}*'Cap Table'!E${src},0)`,
            `=IFERROR($B$3*'Cap Table'!G${src},0)`,
            `=IFERROR(IF(Assumptions!$B$12="Participating",B${r}+C${r},MAX(B${r},C${r})),0)`,
            `=IFERROR(D${r}/MAX(1,'Cap Table'!C${src}),0)`,
          ];
        }),
        ["Common & options residual", "", "=IFERROR($B$3-SUM(D6:D10),0)", "=C11", ""],
        ["Total distributed", "", "", "=SUM(D6:D11)", ""],
      ]),
      S("Audit", [
        ["INSTITUTIONAL CHECK BLOCK"],
        [],
        ["Check", "Result"],
        ["Ownership sums to 100%", "=ABS('Cap Table'!$F$12-1)<0.0001"],
        ["Distributions equal exit value", "=ABS('Exit Waterfall'!$D$12-'Exit Waterfall'!$B$3)<1"],
        ["No negative payouts", "=MIN('Exit Waterfall'!D6:D11)>=0"],
        ["Option pool within limit", "=Assumptions!$B$7<=0.3"],
        ["MASTER CHECK", "=AND(B4:B7)"],
      ]),
    ],
  },
  {
    id: "fig-bank-model",
    name: "Bank Operating Model (FIG)",
    tier: "Institutional",
    blurb:
      "Specialised bank 3-statement build with net interest margin, loan-loss provisioning, yield-curve sensitivity and Basel capital ratios.",
    features: ["NIM build", "Loan loss provisions", "RWA & Tier 1", "Yield curve sensitivity"],
    prompt:
      "Add a Basel III adverse stress scenario with VaR and a CET1 depletion path to this bank model.",
    build: () => [
      S("Assumptions", [
        ...CASE_BLOCK,
        [],
        ["Driver", "Value"],
        ["Loan growth", 0.06],
        ["Asset yield", 0.058],
        ["Cost of deposits", 0.021],
        ["Fee income growth", 0.04],
        ["Cost/income target", 0.52],
        ["Provision rate (bps of loans)", 0.0045],
        ["Tax rate", 0.24],
        ["Risk weight (avg)", 0.62],
        ["Tier 1 target ratio", 0.11],
        ["Case yield shock (bps)", '=IFERROR(CHOOSE($B$3,0,0.005,-0.0075),0)'],
        ["Effective asset yield", "=B7+B15"],
      ]),
      S("Bank Model", [
        ["BANK OPERATING MODEL", "FY2026", "FY2027", "FY2028"],
        ["Gross loans", 12500000000, "=B2*(1+Assumptions!$B$6)", "=C2*(1+Assumptions!$B$6)"],
        ["Deposits", "=B2*1.18", "=C2*1.18", "=D2*1.18"],
        ["Interest income", "=B2*Assumptions!$B$16", "=C2*Assumptions!$B$16", "=D2*Assumptions!$B$16"],
        ["Interest expense", "=-B3*Assumptions!$B$8", "=-C3*Assumptions!$B$8", "=-D3*Assumptions!$B$8"],
        ["Net interest income", "=B4+B5", "=C4+C5", "=D4+D5"],
        ["Net interest margin", "=IFERROR(B6/B2,0)", "=IFERROR(C6/C2,0)", "=IFERROR(D6/D2,0)"],
        ["Fee & commission income", "=B2*0.011", "=B8*(1+Assumptions!$B$9)", "=C8*(1+Assumptions!$B$9)"],
        ["Total revenue", "=B6+B8", "=C6+C8", "=D6+D8"],
        ["Operating expenses", "=-B9*Assumptions!$B$10", "=-C9*Assumptions!$B$10", "=-D9*Assumptions!$B$10"],
        ["Pre-provision profit", "=B9+B10", "=C9+C10", "=D9+D10"],
        ["Loan loss provision", "=-B2*Assumptions!$B$11", "=-C2*Assumptions!$B$11", "=-D2*Assumptions!$B$11"],
        ["Pre-tax income", "=B11+B12", "=C11+C12", "=D11+D12"],
        ["Tax", "=-B13*Assumptions!$B$12", "=-C13*Assumptions!$B$12", "=-D13*Assumptions!$B$12"],
        ["Net income", "=B13+B14", "=C13+C14", "=D13+D14"],
        [],
        ["CAPITAL ADEQUACY"],
        ["Risk-weighted assets", "=B2*Assumptions!$B$13", "=C2*Assumptions!$B$13", "=D2*Assumptions!$B$13"],
        ["Tier 1 capital", "=B18*Assumptions!$B$14", "=B19+C15*0.7", "=C19+D15*0.7"],
        ["Tier 1 ratio", "=IFERROR(B19/B18,0)", "=IFERROR(C19/C18,0)", "=IFERROR(D19/D18,0)"],
        ["Capital surplus / (deficit)", "=B19-B18*Assumptions!$B$14", "=C19-C18*Assumptions!$B$14", "=D19-D18*Assumptions!$B$14"],
        ["Return on equity", "=IFERROR(B15/B19,0)", "=IFERROR(C15/C19,0)", "=IFERROR(D15/D19,0)"],
        [],
        ["YIELD CURVE SENSITIVITY (NII impact)"],
        ["Shock (bps)", "-100", "-50", "0", "+50", "+100"],
        ["NII", "=$B$2*(Assumptions!$B$16-0.01)-$B$3*Assumptions!$B$8", "=$B$2*(Assumptions!$B$16-0.005)-$B$3*Assumptions!$B$8", "=$B$6", "=$B$2*(Assumptions!$B$16+0.005)-$B$3*Assumptions!$B$8", "=$B$2*(Assumptions!$B$16+0.01)-$B$3*Assumptions!$B$8"],
      ]),
      S("Audit", [
        ["INSTITUTIONAL CHECK BLOCK"],
        [],
        ["Check", "Result"],
        ["NIM within plausible range", "=AND('Bank Model'!$B$7>0,'Bank Model'!$B$7<0.08)"],
        ["Tier 1 at or above target", "='Bank Model'!$B$20>=Assumptions!$B$14-0.0001"],
        ["Provisions negative (cost)", "='Bank Model'!$B$12<0"],
        ["No hardcodes in revenue line", "=ISFORMULA('Bank Model'!$B$9)"],
        ["MASTER CHECK", "=AND(B4:B7)"],
      ]),
    ],
  },
  {
    id: "cre-property-model",
    name: "Commercial Property Model (Argus-alternative)",
    tier: "Institutional",
    blurb:
      "Monthly office/retail/industrial cash flow with rent roll, lease rollover, NNN reimbursements, TI/LC schedules and exit valuation.",
    features: ["Rent roll", "Lease expiry & absorption", "NNN gross-up", "TI / LC schedule"],
    prompt:
      "Convert this property model to monthly granularity across 120 periods and add a refinance and hold/sell comparison.",
    build: () => [
      S("Assumptions", [
        ...CASE_BLOCK,
        [],
        ["Driver", "Value"],
        ["Purchase price", 42000000],
        ["Going-in cap rate", 0.058],
        ["Exit cap rate", 0.062],
        ["Market rent growth", 0.03],
        ["Vacancy / credit loss", 0.06],
        ["OpEx per sq ft", 9.4],
        ["Reimbursement recovery %", 0.86],
        ["TI per sq ft (new lease)", 45],
        ["LC % of lease value", 0.05],
        ["Hold period (yrs)", 5],
        ["Case rent growth", '=IFERROR(CHOOSE($B$3,B9,B9+0.015,B9-0.02),B9)'],
      ]),
      S("Rent Roll", [
        ["RENT ROLL"],
        [],
        ["Tenant", "Suite", "Sq ft", "Base rent / sf", "Lease start", "Lease expiry", "Recovery type", "Annual base rent"],
        ["Anchor Retail Co", "100", 42000, 24.5, "2022-03-01", "2029-02-28", "NNN", "=C4*D4"],
        ["Nimbus Software", "210", 18500, 38.25, "2023-07-01", "2028-06-30", "NNN", "=C5*D5"],
        ["Harbor Legal", "310", 9800, 41, "2021-01-01", "2026-12-31", "Gross", "=C6*D6"],
        ["Vertex Labs", "410", 14200, 35.75, "2024-05-01", "2031-04-30", "NNN", "=C7*D7"],
        ["Suite 500 (vacant)", "500", 7600, "=Assumptions!$B$7*0", 0, 0, "NNN", "=C8*D8"],
        ["Total / weighted", "", "=SUM(C4:C8)", "=IFERROR(SUMPRODUCT(C4:C8,D4:D8)/C9,0)", "", "", "", "=SUM(H4:H8)"],
      ]),
      S("Cash Flow", [
        ["PROPERTY CASH FLOW", "Yr 1", "Yr 2", "Yr 3", "Yr 4", "Yr 5"],
        ["Gross potential rent", "='Rent Roll'!$H$9", "=B2*(1+Assumptions!$B$15)", "=C2*(1+Assumptions!$B$15)", "=D2*(1+Assumptions!$B$15)", "=E2*(1+Assumptions!$B$15)"],
        ["Vacancy & credit loss", "=-B2*Assumptions!$B$10", "=-C2*Assumptions!$B$10", "=-D2*Assumptions!$B$10", "=-E2*Assumptions!$B$10", "=-F2*Assumptions!$B$10"],
        ["Expense reimbursements", "=('Rent Roll'!$C$9*Assumptions!$B$11)*Assumptions!$B$12", "=B4*(1+Assumptions!$B$15)", "=C4*(1+Assumptions!$B$15)", "=D4*(1+Assumptions!$B$15)", "=E4*(1+Assumptions!$B$15)"],
        ["Effective gross income", "=B2+B3+B4", "=C2+C3+C4", "=D2+D3+D4", "=E2+E3+E4", "=F2+F3+F4"],
        ["Operating expenses", "=-'Rent Roll'!$C$9*Assumptions!$B$11", "=B6*(1+Assumptions!$B$15)", "=C6*(1+Assumptions!$B$15)", "=D6*(1+Assumptions!$B$15)", "=E6*(1+Assumptions!$B$15)"],
        ["Net operating income", "=B5+B6", "=C5+C6", "=D5+D6", "=E5+E6", "=F5+F6"],
        ["Tenant improvements", 0, 0, 0, "=-'Rent Roll'!$C$6*Assumptions!$B$13", 0],
        ["Leasing commissions", 0, 0, 0, "=-'Rent Roll'!$H$6*Assumptions!$B$14", 0],
        ["Capital reserves", "=-'Rent Roll'!$C$9*0.25", "=B10*(1+Assumptions!$B$15)", "=C10*(1+Assumptions!$B$15)", "=D10*(1+Assumptions!$B$15)", "=E10*(1+Assumptions!$B$15)"],
        ["Cash flow before debt", "=B7+B8+B9+B10", "=C7+C8+C9+C10", "=D7+D8+D9+D10", "=E7+E8+E9+E10", "=F7+F8+F9+F10"],
        [],
        ["VALUATION"],
        ["Going-in value (NOI / cap)", "=IFERROR(B7/Assumptions!$B$7,0)"],
        ["Exit value (yr 5 NOI / exit cap)", "=IFERROR(F7*(1+Assumptions!$B$15)/Assumptions!$B$8,0)"],
        ["Unlevered cash flows", "=-Assumptions!$B$6", "=C11", "=D11", "=E11", "=F11", "=B11+$B$15"],
        ["Unlevered IRR", "=IFERROR(IRR(B16:G16),0)"],
        ["Equity multiple", "=IFERROR(SUM(C16:G16)/-B16,0)"],
      ]),
      S("Audit", [
        ["INSTITUTIONAL CHECK BLOCK"],
        [],
        ["Check", "Result"],
        ["Rent roll square footage totals", "=ABS('Rent Roll'!$C$9-SUM('Rent Roll'!C4:C8))<0.01"],
        ["NOI positive in all years", "=MIN('Cash Flow'!B7:F7)>0"],
        ["Exit cap above going-in cap", "=Assumptions!$B$8>=Assumptions!$B$7"],
        ["IRR calculable", "=ISNUMBER('Cash Flow'!$B$17)"],
        ["MASTER CHECK", "=AND(B4:B7)"],
      ]),
    ],
  },
  {
    id: "reit-nav",
    name: "REIT NAV, FFO & AFFO Model",
    tier: "Institutional",
    blurb:
      "Funds-from-operations build-up with AFFO adjustments, implied cap rate valuation and premium/discount to NAV per share.",
    features: ["FFO / AFFO bridge", "Implied cap rate", "NAV per share", "Premium to NAV"],
    prompt: "Add a segment-level NAV build by property type and a dividend coverage sensitivity table.",
    build: () => [
      S("Assumptions", [
        ...CASE_BLOCK,
        [],
        ["Driver", "Value"],
        ["Shares outstanding (m)", 148.5],
        ["Share price", 41.2],
        ["Nominal cap rate", 0.059],
        ["Maintenance capex % of NOI", 0.09],
        ["Straight-line rent adj % of NOI", 0.015],
        ["Dividend per share", 2.44],
        ["Case cap rate", '=IFERROR(CHOOSE($B$3,B8,B8-0.005,B8+0.0075),B8)'],
      ]),
      S("NAV Model", [
        ["FFO / AFFO & NAV BUILD"],
        [],
        ["Net income", 214000000],
        ["Add: real estate depreciation", 386000000],
        ["Less: gains on property sales", -42000000],
        ["FFO", "=B3+B4+B5"],
        ["FFO per share", "=IFERROR(B6/Assumptions!$B$6,0)"],
        [],
        ["Cash NOI", 812000000],
        ["Less: maintenance capex", "=-B9*Assumptions!$B$9"],
        ["Less: straight-line rent", "=-B9*Assumptions!$B$10"],
        ["AFFO", "=B6+B10+B11"],
        ["AFFO per share", "=IFERROR(B12/Assumptions!$B$6,0)"],
        ["Dividend payout of AFFO", "=IFERROR(Assumptions!$B$11/B13,0)"],
        [],
        ["NAV BUILD"],
        ["Gross real estate value", "=IFERROR(B9/Assumptions!$B$12,0)"],
        ["Other assets", 240000000],
        ["Total debt", -4650000000],
        ["Preferred equity", -300000000],
        ["Net asset value", "=B17+B18+B19+B20"],
        ["NAV per share", "=IFERROR(B21/Assumptions!$B$6,0)"],
        ["Premium / (discount) to NAV", "=IFERROR(Assumptions!$B$7/B22-1,0)"],
        ["Implied cap rate at market price", "=IFERROR(B9/(Assumptions!$B$7*Assumptions!$B$6-B18-B19-B20),0)"],
      ]),
      S("Audit", [
        ["INSTITUTIONAL CHECK BLOCK"],
        [],
        ["Check", "Result"],
        ["FFO exceeds net income", "='NAV Model'!$B$6>'NAV Model'!$B$3"],
        ["AFFO below FFO", "='NAV Model'!$B$12<'NAV Model'!$B$6"],
        ["Dividend covered by AFFO", "='NAV Model'!$B$14<=1"],
        ["NAV per share positive", "='NAV Model'!$B$22>0"],
        ["MASTER CHECK", "=AND(B4:B7)"],
      ]),
    ],
  },
  {
    id: "vessel-tce",
    name: "Vessel Voyage Estimation & TCE",
    tier: "Institutional",
    blurb:
      "Time-charter-equivalent calculator with bunker consumption curves, port disbursements, canal tolls and freight-rate sensitivity.",
    features: ["TCE per day", "HFO vs VLSFO", "Canal & port costs", "Freight sensitivity"],
    prompt:
      "Add a ballast-leg optimisation comparison across three trade routes and an FFA hedge overlay to this voyage model.",
    build: () => [
      S("Assumptions", [
        ...CASE_BLOCK,
        [],
        ["Driver", "Value"],
        ["Cargo quantity (mt)", 72000],
        ["Freight rate ($/mt)", 28.5],
        ["Laden distance (nm)", 8400],
        ["Ballast distance (nm)", 3100],
        ["Laden speed (kn)", 13.5],
        ["Ballast speed (kn)", 14],
        ["VLSFO price ($/mt)", 615],
        ["MGO price ($/mt)", 780],
        ["Laden consumption (mt/day)", 32],
        ["Ballast consumption (mt/day)", 27],
        ["Port days", 6],
        ["Port consumption (mt/day)", 4],
        ["Port disbursements", 185000],
        ["Canal tolls", 310000],
        ["Commission %", 0.0375],
        ["Case rate multiplier", '=IFERROR(CHOOSE($B$3,1,1.22,0.78),1)'],
        ["Effective freight rate", "=B7*B21"],
      ]),
      S("Voyage", [
        ["VOYAGE ESTIMATION"],
        [],
        ["Laden days", "=IFERROR(Assumptions!$B$8/(Assumptions!$B$10*24),0)"],
        ["Ballast days", "=IFERROR(Assumptions!$B$9/(Assumptions!$B$11*24),0)"],
        ["Port days", "=Assumptions!$B$17"],
        ["Total voyage days", "=B3+B4+B5"],
        [],
        ["REVENUE"],
        ["Gross freight", "=IFERROR(Assumptions!$B$6*Assumptions!$B$22,0)"],
        ["Commission", "=-B9*Assumptions!$B$20"],
        ["Net freight", "=B9+B10"],
        [],
        ["VOYAGE COSTS"],
        ["Laden bunkers", "=-B3*Assumptions!$B$14*Assumptions!$B$12"],
        ["Ballast bunkers", "=-B4*Assumptions!$B$15*Assumptions!$B$12"],
        ["Port bunkers (MGO)", "=-B5*Assumptions!$B$18*Assumptions!$B$13"],
        ["Port disbursements", "=-Assumptions!$B$19"],
        ["Canal tolls", "=-Assumptions!$B$20*0", "(toll cell links to driver below)"],
        ["Canal toll cost", "=-Assumptions!$B$19*0+-310000*0-Assumptions!$B$19*0"],
        ["Total voyage costs", "=SUM(B14:B17)"],
        [],
        ["RESULT"],
        ["Voyage profit", "=B11+B19"],
        ["TCE ($/day)", "=IFERROR(B21/B6,0)"],
        ["Breakeven freight rate ($/mt)", "=IFERROR(-B19/Assumptions!$B$6/(1-Assumptions!$B$20),0)"],
        [],
        ["FREIGHT RATE SENSITIVITY (TCE $/day)"],
        ["Rate $/mt", 22, 25, 28.5, 32, 36],
        ["TCE", "=IFERROR((Assumptions!$B$6*B26*(1-Assumptions!$B$20)+$B$19)/$B$6,0)", "=IFERROR((Assumptions!$B$6*C26*(1-Assumptions!$B$20)+$B$19)/$B$6,0)", "=IFERROR((Assumptions!$B$6*D26*(1-Assumptions!$B$20)+$B$19)/$B$6,0)", "=IFERROR((Assumptions!$B$6*E26*(1-Assumptions!$B$20)+$B$19)/$B$6,0)", "=IFERROR((Assumptions!$B$6*F26*(1-Assumptions!$B$20)+$B$19)/$B$6,0)"],
      ]),
      S("Audit", [
        ["INSTITUTIONAL CHECK BLOCK"],
        [],
        ["Check", "Result"],
        ["Voyage days positive", "=Voyage!$B$6>0"],
        ["Voyage costs negative", "=Voyage!$B$19<0"],
        ["TCE calculable", "=ISNUMBER(Voyage!$B$22)"],
        ["Breakeven below current rate", "=Voyage!$B$23<Assumptions!$B$22"],
        ["MASTER CHECK", "=AND(B4:B7)"],
      ]),
    ],
  },
  {
    id: "saas-finops",
    name: "SaaS & Cloud FinOps Unit Economics",
    tier: "Institutional",
    blurb:
      "GPU/compute cost-to-serve against cohort retention: ARR roll-forward, gross margin by workload, LTV:CAC and magic number.",
    features: ["ARR roll-forward", "Cohort retention", "GPU cost to serve", "LTV:CAC & magic number"],
    prompt:
      "Add an AI inference token-margin analysis by model tier and a 24-month runway forecast with hiring toggles.",
    build: () => [
      S("Assumptions", [
        ...CASE_BLOCK,
        [],
        ["Driver", "Value"],
        ["Opening ARR", 24000000],
        ["New ARR / quarter", 3400000],
        ["Expansion rate (quarterly)", 0.045],
        ["Contraction rate", 0.012],
        ["Gross churn rate", 0.021],
        ["Sales & marketing / quarter", 4100000],
        ["GPU hours / quarter", 420000],
        ["GPU cost / hour", 2.35],
        ["Other COGS % of revenue", 0.11],
        ["Average contract value", 42000],
        ["CAC payback target (months)", 18],
        ["Case new ARR multiplier", '=IFERROR(CHOOSE($B$3,1,1.35,0.6),1)'],
      ]),
      S("ARR Roll-forward", [
        ["ARR ROLL-FORWARD", "Q1", "Q2", "Q3", "Q4"],
        ["Opening ARR", "=Assumptions!$B$6", "=B8", "=C8", "=D8"],
        ["New ARR", "=Assumptions!$B$7*Assumptions!$B$18", "=B3*1.05", "=C3*1.05", "=D3*1.05"],
        ["Expansion", "=B2*Assumptions!$B$8", "=C2*Assumptions!$B$8", "=D2*Assumptions!$B$8", "=E2*Assumptions!$B$8"],
        ["Contraction", "=-B2*Assumptions!$B$9", "=-C2*Assumptions!$B$9", "=-D2*Assumptions!$B$9", "=-E2*Assumptions!$B$9"],
        ["Churn", "=-B2*Assumptions!$B$10", "=-C2*Assumptions!$B$10", "=-D2*Assumptions!$B$10", "=-E2*Assumptions!$B$10"],
        ["Net new ARR", "=SUM(B3:B6)", "=SUM(C3:C6)", "=SUM(D3:D6)", "=SUM(E3:E6)"],
        ["Closing ARR", "=B2+B7", "=C2+C7", "=D2+D7", "=E2+E7"],
        ["Net revenue retention", "=IFERROR((B2+B4+B5+B6)/B2,0)", "=IFERROR((C2+C4+C5+C6)/C2,0)", "=IFERROR((D2+D4+D5+D6)/D2,0)", "=IFERROR((E2+E4+E5+E6)/E2,0)"],
        [],
        ["UNIT ECONOMICS & FINOPS"],
        ["Quarterly revenue", "=B8/4", "=C8/4", "=D8/4", "=E8/4"],
        ["GPU / compute cost", "=-Assumptions!$B$12*Assumptions!$B$13", "=B13*1.06", "=C13*1.06", "=D13*1.06"],
        ["Other COGS", "=-B12*Assumptions!$B$14", "=-C12*Assumptions!$B$14", "=-D12*Assumptions!$B$14", "=-E12*Assumptions!$B$14"],
        ["Gross profit", "=B12+B13+B14", "=C12+C13+C14", "=D12+D13+D14", "=E12+E13+E14"],
        ["Gross margin", "=IFERROR(B15/B12,0)", "=IFERROR(C15/C12,0)", "=IFERROR(D15/D12,0)", "=IFERROR(E15/E12,0)"],
        ["Cost to serve per GPU hour", "=IFERROR(-B13/Assumptions!$B$12,0)"],
        [],
        ["EFFICIENCY METRICS"],
        ["CAC", "=IFERROR(Assumptions!$B$11/(B3/Assumptions!$B$15),0)"],
        ["LTV", "=IFERROR(Assumptions!$B$15*AVERAGE(B16:E16)/Assumptions!$B$10,0)"],
        ["LTV : CAC", "=IFERROR(B21/B20,0)"],
        ["CAC payback (months)", "=IFERROR(B20/(Assumptions!$B$15*AVERAGE(B16:E16)/12),0)"],
        ["Magic number", "=IFERROR((E8-D8)*4/Assumptions!$B$11,0)"],
        ["Rule of 40", "=IFERROR((E8/B2-1)+AVERAGE(B16:E16),0)"],
      ]),
      S("Audit", [
        ["INSTITUTIONAL CHECK BLOCK"],
        [],
        ["Check", "Result"],
        ["ARR roll-forward ties", "=ABS('ARR Roll-forward'!$E$8-('ARR Roll-forward'!$B$2+SUM('ARR Roll-forward'!B7:E7)))<1"],
        ["Gross margin between 0 and 1", "=AND(MIN('ARR Roll-forward'!B16:E16)>0,MAX('ARR Roll-forward'!B16:E16)<1)"],
        ["LTV:CAC at or above 3x", "='ARR Roll-forward'!$B$22>=3"],
        ["CAC payback within target", "='ARR Roll-forward'!$B$23<=Assumptions!$B$16"],
        ["MASTER CHECK", "=AND(B4:B7)"],
      ]),
    ],
  },
];
