import { S, type FinancialTemplate } from "./types.ts";

export const OPERATIONS_TEMPLATES: FinancialTemplate[] = [
  {
    id: "clinic-capacity",
    name: "Clinic capacity & attendance",
    tier: "Operations",
    blurb:
      "Plan service capacity and track attendance without patient identifiers. Includes labelled example data.",
    features: ["Slot utilization", "Attendance rate", "Capacity checks", "No patient data"],
    prompt:
      "Extend the clinic capacity workbook using my actual departments and volumes. Ask for missing inputs. Do not add patient data or invent operational figures.",
    build: () => [
      S("Clinic capacity", [
        [
          "Department (example)",
          "Available slots",
          "Booked",
          "Attended",
          "Booking utilization",
          "Attendance rate",
          "Unused slots",
          "Input check",
        ],
        [
          "Primary care",
          200,
          180,
          162,
          "=IFERROR(C2/B2,0)",
          "=IFERROR(D2/C2,0)",
          "=B2-C2",
          '=IF(OR(C2>B2,D2>C2,MIN(B2:D2)<0),"CHECK","OK")',
        ],
        [
          "Physiotherapy",
          100,
          85,
          80,
          "=IFERROR(C3/B3,0)",
          "=IFERROR(D3/C3,0)",
          "=B3-C3",
          '=IF(OR(C3>B3,D3>C3,MIN(B3:D3)<0),"CHECK","OK")',
        ],
        [
          "Total",
          "=SUM(B2:B3)",
          "=SUM(C2:C3)",
          "=SUM(D2:D3)",
          "=IFERROR(C4/B4,0)",
          "=IFERROR(D4/C4,0)",
          "=B4-C4",
          '=IF(COUNTIF(H2:H3,"CHECK")>0,"CHECK","OK")',
        ],
      ]),
    ],
  },
  {
    id: "renewable-generation",
    name: "Renewable generation tracker",
    tier: "Operations",
    blurb:
      "Compare actual generation with capacity and budget. Example inputs must be replaced with site measurements.",
    features: [
      "Capacity factor",
      "Energy variance",
      "Revenue at input tariff",
      "Unit-labelled inputs",
    ],
    prompt:
      "Extend the renewable generation tracker for my sites. Keep MW, MWh, hours and tariff units explicit and ask for measured data.",
    build: () => [
      S("Generation", [
        [
          "Period (example)",
          "Capacity MW",
          "Hours in period",
          "Actual MWh",
          "Budget MWh",
          "Tariff per MWh",
          "Capacity factor",
          "Variance MWh",
          "Revenue",
          "Input check",
        ],
        [
          "2026-01",
          10,
          744,
          1450,
          1500,
          60,
          "=IFERROR(D2/(B2*C2),0)",
          "=D2-E2",
          "=D2*F2",
          '=IF(OR(D2>B2*C2,MIN(B2:F2)<0),"CHECK","OK")',
        ],
        [
          "2026-02",
          10,
          672,
          1390,
          1400,
          60,
          "=IFERROR(D3/(B3*C3),0)",
          "=D3-E3",
          "=D3*F3",
          '=IF(OR(D3>B3*C3,MIN(B3:F3)<0),"CHECK","OK")',
        ],
      ]),
    ],
  },
  {
    id: "construction-earned-value",
    name: "Construction earned value",
    tier: "Operations",
    blurb:
      "Track planned value, earned value, cost and forecast using a transparent CPI-based estimate. Includes example work packages.",
    features: ["Cost & schedule variance", "CPI / SPI", "Estimate at completion", "Input checks"],
    prompt:
      "Extend this construction earned value workbook using my work packages, budgets, completion percentages and actual costs. Preserve explicit forecast assumptions.",
    build: () => [
      S("Earned value", [
        [
          "Work package (example)",
          "Budget at completion",
          "Planned fraction",
          "Actual fraction",
          "Actual cost",
          "Planned value",
          "Earned value",
          "Cost variance",
          "Schedule variance",
          "CPI",
          "SPI",
          "EAC at current CPI",
          "Input check",
        ],
        [
          "Foundations",
          100000,
          "60%",
          "50%",
          55000,
          "=B2*C2",
          "=B2*D2",
          "=G2-E2",
          "=G2-F2",
          "=IFERROR(G2/E2,0)",
          "=IFERROR(G2/F2,0)",
          "=IFERROR(B2/J2,0)",
          '=IF(OR(MIN(B2:E2)<0,C2>1,D2>1),"CHECK","OK")',
        ],
        [
          "Structure",
          250000,
          "20%",
          "15%",
          40000,
          "=B3*C3",
          "=B3*D3",
          "=G3-E3",
          "=G3-F3",
          "=IFERROR(G3/E3,0)",
          "=IFERROR(G3/F3,0)",
          "=IFERROR(B3/J3,0)",
          '=IF(OR(MIN(B3:E3)<0,C3>1,D3>1),"CHECK","OK")',
        ],
      ]),
      S("Forecast assumptions", [
        ["Assumption", "Meaning"],
        [
          "EAC",
          "Budget divided by current cost performance index; assumes current efficiency persists.",
        ],
        [
          "Zero CPI",
          "A zero EAC indicates unavailable forecast when no earned value exists; do not treat it as a zero final cost.",
        ],
        [
          "Example inputs",
          "Replace example budgets, progress and costs with verified project data.",
        ],
      ]),
    ],
  },
  {
    id: "bid-costing",
    name: "Proposal & bid costing",
    tier: "Operations",
    blurb:
      "Build a quote from quantities, rates, contingency and target margin. Margin is applied to sales price, not as markup.",
    features: ["Line costs", "Contingency", "Margin-based price", "Input checks"],
    prompt:
      "Extend the bid costing workbook for my proposal. Ask for missing scope, rates, contingency and target margin. Do not invent supplier quotes.",
    build: () => [
      S("Bid costing", [
        ["Item (example)", "Quantity", "Unit cost", "Extended cost"],
        ["Engineering hours", 120, 75, "=B2*C2"],
        ["Equipment", 2, 5000, "=B3*C3"],
        ["Direct cost", "", "", "=SUM(D2:D3)"],
        ["Contingency fraction", "10%", "", "=D4*B5"],
        ["Total cost", "", "", "=D4+D5"],
        ["Target gross margin", "20%", "", ""],
        ["Quoted price", "", "", "=IF(OR(B7<0,B7>=1),0,D6/(1-B7))"],
        ["Gross profit", "", "", "=D8-D6"],
        ["Input check", '=IF(OR(MIN(B2:C3)<0,B5<0,B7<0,B7>=1),"CHECK","OK")'],
      ]),
    ],
  },
];
