import { S, type FinancialTemplate } from "./types";

/**
 * Ultra-advanced quantitative templates.
 * All calculations use modern Microsoft 365 dynamic-array / LET / LAMBDA architecture
 * and every volatile block is wrapped in IFERROR so downloads never show error cascades.
 */
export const QUANT_TEMPLATES: FinancialTemplate[] = [
  {
    id: "monte-carlo",
    name: "Monte Carlo Simulation Engine",
    tier: "Quantitative",
    blurb:
      "Probabilistic forecasting with RANDARRAY + NORM.INV geometric Brownian motion, 10,000 spilled iterations and percentile fan charts.",
    features: ["RANDARRAY", "NORM.INV / NORM.S.DIST", "LET + MAP", "Percentile bands"],
    prompt:
      "Extend this Monte Carlo engine to simulate project NPV risk as well as price paths, and add a VaR / CVaR summary block.",
    build: () => [
      S("Assumptions", [
        ["MONTE CARLO — DRIVERS & DASHBOARD"],
        [],
        ["Driver", "Value", "Validation"],
        ["Spot price", 100, "Numeric > 0"],
        ["Annual drift (mu)", 0.08, "-1 to 1"],
        ["Annual volatility (sigma)", 0.28, "0 to 3"],
        ["Horizon (years)", 1, "0.1 to 10"],
        ["Steps per path", 252, "Integer"],
        ["Iterations", 10000, "1000 to 100000"],
        ["Confidence level", 0.95, "0.5 to 0.999"],
        [],
        ["DERIVED (LET-based, no hardcoding)"],
        ["dt", "=IFERROR(B7/B8,0)"],
        ["Drift per step", "=IFERROR((B5-0.5*B6^2)*B14,0)"],
        ["Diffusion per step", "=IFERROR(B6*SQRT(B14),0)"],
        ["z at confidence", "=IFERROR(NORM.S.INV(B10),0)"],
        [],
        ["RESULTS (spill from Simulation tab)"],
        ["Mean terminal price", "=IFERROR(AVERAGE(Simulation!$D$4#),0)"],
        ["Median terminal price", "=IFERROR(MEDIAN(Simulation!$D$4#),0)"],
        ["P5 terminal price", "=IFERROR(PERCENTILE.INC(Simulation!$D$4#,0.05),0)"],
        ["P95 terminal price", "=IFERROR(PERCENTILE.INC(Simulation!$D$4#,0.95),0)"],
        ["Prob. of loss", "=IFERROR(AVERAGE(--(Simulation!$D$4#<B4)),0)"],
        ["Value at Risk (1 - conf.)", "=IFERROR(B4-PERCENTILE.INC(Simulation!$D$4#,1-B10),0)"],
        [
          "Expected shortfall (CVaR)",
          "=IFERROR(B4-AVERAGEIF(Simulation!$D$4#,\"<\"&PERCENTILE.INC(Simulation!$D$4#,1-B10)),0)",
        ],
      ]),
      S("Simulation", [
        ["SIMULATION ENGINE — single-formula spill (recalculate with F9)"],
        [],
        ["Iteration", "Random draws", "Log return sum", "Terminal price"],
        [
          "=IFERROR(SEQUENCE(Assumptions!$B$9),\"\")",
          "=IFERROR(RANDARRAY(Assumptions!$B$9,1),\"\")",
          "=IFERROR(LET(n,Assumptions!$B$9,s,Assumptions!$B$8,mu,Assumptions!$B$15,sd,Assumptions!$B$16,MAP(SEQUENCE(n),LAMBDA(i,SUM(mu+sd*NORM.S.INV(RANDARRAY(s,1)))))),\"\")",
          "=IFERROR(Assumptions!$B$4*EXP(C4#),\"\")",
        ],
        [],
        ["NOTE"],
        [
          "Columns A:D are dynamic arrays. Do not type below row 4 — the spill range expands with the iteration count.",
        ],
      ]),
      S("Audit", [
        ["MODEL INTEGRITY CHECKS"],
        [],
        ["Check", "Result", "Status"],
        ["Iterations spilled correctly", "=IFERROR(ROWS(Simulation!$D$4#)=Assumptions!$B$9,FALSE)", '=IF(B4,"TRUE","FALSE")'],
        ["Volatility within bounds", "=AND(Assumptions!$B$6>0,Assumptions!$B$6<3)", '=IF(B5,"TRUE","FALSE")'],
        ["No error values in spill", "=IFERROR(SUM(--ISERROR(Simulation!$D$4#))=0,FALSE)", '=IF(B6,"TRUE","FALSE")'],
        ["MASTER CHECK", "=AND(B4:B6)", '=IF(B7,"MODEL OK","REVIEW REQUIRED")'],
      ]),
    ],
  },
  {
    id: "black-scholes",
    name: "Options Pricing & Greeks (Black-Scholes)",
    tier: "Quantitative",
    blurb:
      "Call/put pricing with full Greeks (Delta, Gamma, Theta, Vega, Rho), implied-volatility smile grid and payoff diagram data.",
    features: ["EXP / LN math", "All five Greeks", "Volatility smile", "Payoff table"],
    prompt:
      "Add American-style binomial pricing and a straddle/strangle strategy payoff comparison to this options model.",
    build: () => [
      S("Pricing", [
        ["BLACK-SCHOLES OPTION PRICER"],
        [],
        ["Input", "Value"],
        ["Spot (S)", 100],
        ["Strike (K)", 105],
        ["Time to expiry (T, yrs)", 0.5],
        ["Risk-free rate (r)", 0.045],
        ["Dividend yield (q)", 0.01],
        ["Volatility (sigma)", 0.3],
        [],
        ["INTERMEDIATE"],
        ["d1", "=IFERROR((LN(B4/B5)+(B7-B8+0.5*B9^2)*B6)/(B9*SQRT(B6)),0)"],
        ["d2", "=IFERROR(B12-B9*SQRT(B6),0)"],
        ["N(d1)", "=NORM.S.DIST(B12,TRUE)"],
        ["N(d2)", "=NORM.S.DIST(B13,TRUE)"],
        ["n(d1) density", "=NORM.S.DIST(B12,FALSE)"],
        [],
        ["PRICES", "Call", "Put"],
        [
          "Option value",
          "=IFERROR(B4*EXP(-B8*B6)*B14-B5*EXP(-B7*B6)*B15,0)",
          "=IFERROR(B5*EXP(-B7*B6)*(1-B15)-B4*EXP(-B8*B6)*(1-B14),0)",
        ],
        [],
        ["GREEKS", "Call", "Put"],
        ["Delta", "=EXP(-B8*B6)*B14", "=EXP(-B8*B6)*(B14-1)"],
        ["Gamma", "=IFERROR(EXP(-B8*B6)*B16/(B4*B9*SQRT(B6)),0)", "=B22"],
        [
          "Theta (per year)",
          "=IFERROR(-B4*B16*B9*EXP(-B8*B6)/(2*SQRT(B6))-B7*B5*EXP(-B7*B6)*B15+B8*B4*EXP(-B8*B6)*B14,0)",
          "=IFERROR(-B4*B16*B9*EXP(-B8*B6)/(2*SQRT(B6))+B7*B5*EXP(-B7*B6)*(1-B15)-B8*B4*EXP(-B8*B6)*(1-B14),0)",
        ],
        ["Vega", "=IFERROR(B4*EXP(-B8*B6)*B16*SQRT(B6),0)", "=B24"],
        ["Rho", "=IFERROR(B5*B6*EXP(-B7*B6)*B15,0)", "=IFERROR(-B5*B6*EXP(-B7*B6)*(1-B15),0)"],
        ["Put-call parity check", "=IFERROR(B19-C19-(B4*EXP(-B8*B6)-B5*EXP(-B7*B6)),0)", "Must be 0"],
      ]),
      S("Smile & Payoff", [
        ["VOLATILITY SMILE (strike vs implied vol) & PAYOFF DIAGRAM DATA"],
        [],
        ["Strike", "Implied vol", "Call value", "Payoff at expiry (long call)"],
        ...[80, 90, 100, 105, 110, 120, 130].map((k, i) => {
          const r = 4 + i;
          return [
            k,
            `=IFERROR(Pricing!$B$9*(1+0.35*((A${r}/Pricing!$B$4)-1)^2),0)`,
            `=IFERROR(LET(s,Pricing!$B$4,t,Pricing!$B$6,rr,Pricing!$B$7,q,Pricing!$B$8,v,B${r},d1,(LN(s/A${r})+(rr-q+0.5*v^2)*t)/(v*SQRT(t)),d2,d1-v*SQRT(t),s*EXP(-q*t)*NORM.S.DIST(d1,TRUE)-A${r}*EXP(-rr*t)*NORM.S.DIST(d2,TRUE)),0)`,
            `=MAX(0,Pricing!$B$4-A${r})-Pricing!$B$19`,
          ];
        }),
        [],
        ["ATM vol", "=IFERROR(XLOOKUP(Pricing!$B$4,A4:A10,B4:B10,Pricing!$B$9,1),0)"],
      ]),
      S("Audit", [
        ["OPTIONS MODEL CHECKS"],
        [],
        ["Check", "Result"],
        ["Put-call parity within tolerance", "=ABS(Pricing!$B$26)<0.01"],
        ["Volatility positive", "=Pricing!$B$9>0"],
        ["Time to expiry positive", "=Pricing!$B$6>0"],
        ["MASTER CHECK", "=AND(B4:B6)"],
      ]),
    ],
  },
  {
    id: "markowitz",
    name: "Portfolio Optimization — Efficient Frontier",
    tier: "Quantitative",
    blurb:
      "Markowitz mean-variance optimiser using MMULT / MINVERSE / TRANSPOSE on a covariance matrix, with Sharpe-maximising weights.",
    features: ["MMULT & MINVERSE", "Covariance matrix", "Efficient frontier", "Sharpe optimisation"],
    prompt:
      "Add a Solver-ready constrained frontier (no shorting, max 40% per asset) and a risk-parity comparison to this portfolio model.",
    build: () => [
      S("Inputs", [
        ["PORTFOLIO OPTIMISATION — ASSUMPTIONS"],
        [],
        ["Asset", "Expected return", "Volatility", "Weight (input)"],
        ["Equities", 0.09, 0.17, 0.4],
        ["Bonds", 0.04, 0.06, 0.3],
        ["Real estate", 0.075, 0.14, 0.2],
        ["Commodities", 0.055, 0.21, 0.1],
        ["Total weight", "", "", "=SUM(D4:D7)"],
        [],
        ["Risk-free rate", 0.042],
        [],
        ["CORRELATION MATRIX", "Equities", "Bonds", "Real estate", "Commodities"],
        ["Equities", 1, 0.15, 0.55, 0.3],
        ["Bonds", 0.15, 1, 0.2, 0.05],
        ["Real estate", 0.55, 0.2, 1, 0.25],
        ["Commodities", 0.3, 0.05, 0.25, 1],
      ]),
      S("Optimiser", [
        ["MATRIX ENGINE — COVARIANCE, VARIANCE & OPTIMAL WEIGHTS"],
        [],
        ["Covariance matrix (spilled)", "", "", ""],
        [
          "=IFERROR(MAKEARRAY(4,4,LAMBDA(i,j,INDEX(Inputs!$C$4:$C$7,i)*INDEX(Inputs!$C$4:$C$7,j)*INDEX(Inputs!$B$13:$E$16,i,j))),\"\")",
        ],
        [],
        [],
        [],
        [],
        ["PORTFOLIO STATISTICS (current weights)"],
        ["Expected return", "=IFERROR(SUMPRODUCT(Inputs!$B$4:$B$7,Inputs!$D$4:$D$7),0)"],
        [
          "Variance",
          "=IFERROR(MMULT(MMULT(TRANSPOSE(Inputs!$D$4:$D$7),$A$4#),Inputs!$D$4:$D$7),0)",
        ],
        ["Volatility", "=IFERROR(SQRT(B11),0)"],
        ["Sharpe ratio", "=IFERROR((B10-Inputs!$B$10)/B12,0)"],
        [],
        ["TANGENCY (MAX SHARPE) WEIGHTS — closed form via MINVERSE"],
        [
          "Raw weights",
          "=IFERROR(MMULT(MINVERSE($A$4#),Inputs!$B$4:$B$7-Inputs!$B$10),\"\")",
        ],
        ["Normalised weights", "=IFERROR(B16#/SUM(B16#),\"\")"],
        [],
        ["EFFICIENT FRONTIER (target return sweep)"],
        ["Target return", "Frontier volatility"],
        ...[0.05, 0.06, 0.07, 0.08, 0.09].map((t, i) => {
          const r = 21 + i;
          return [
            t,
            `=IFERROR(SQRT(MAX(0,$B$11+((A${r}-$B$10)^2)/MAX(0.0001,$B$13^2))),0)`,
          ];
        }),
      ]),
      S("Audit", [
        ["PORTFOLIO CHECKS"],
        [],
        ["Check", "Result"],
        ["Weights sum to 100%", "=ABS(Inputs!$D$8-1)<0.0001"],
        ["Covariance matrix is symmetric", "=IFERROR(SUM(--(Optimiser!$A$4#<>TRANSPOSE(Optimiser!$A$4#)))=0,FALSE)"],
        ["Variance non-negative", "=Optimiser!$B$11>=0"],
        ["MASTER CHECK", "=AND(B4:B6)"],
      ]),
    ],
  },
  {
    id: "cre-waterfall",
    name: "CRE Equity Waterfall (European & American)",
    tier: "Quantitative",
    blurb:
      "Multi-tier GP/LP promote waterfall with IRR hurdles, catch-up provisions, clawback and a European vs American distribution toggle.",
    features: ["IRR hurdles", "GP catch-up", "Promote splits", "Distribution reconciliation"],
    prompt:
      "Add a fourth promote tier at a 20% IRR hurdle and a full clawback true-up schedule to this waterfall.",
    build: () => [
      S("Deal Terms", [
        ["JOINT VENTURE WATERFALL — TERMS"],
        [],
        ["Term", "Value", "Validation"],
        ["Distribution style", "European", "European / American"],
        ["Total equity", 10000000],
        ["LP share of equity", 0.9],
        ["GP share of equity", "=1-B6"],
        ["Tier 1 hurdle (pref IRR)", 0.08],
        ["Tier 2 hurdle", 0.12],
        ["Tier 3 hurdle", 0.15],
        ["GP catch-up %", 0.5],
        ["Tier 2 promote to GP", 0.2],
        ["Tier 3 promote to GP", 0.3],
        ["Above tier 3 promote to GP", 0.4],
        ["Hold period (yrs)", 5],
      ]),
      S("Waterfall", [
        ["EQUITY WATERFALL — PROJECT CASH FLOW & TIER SPLITS"],
        [],
        ["Line", "Yr 0", "Yr 1", "Yr 2", "Yr 3", "Yr 4", "Yr 5"],
        ["Project cash flow", -10000000, 450000, 620000, 780000, 900000, 13500000],
        ["LP capital contributed", "=-B4*'Deal Terms'!$B$6", 0, 0, 0, 0, 0],
        ["GP capital contributed", "=-B4*'Deal Terms'!$B$7", 0, 0, 0, 0, 0],
        [],
        ["TIER 1 — RETURN OF CAPITAL + PREF"],
        ["Distributable cash", 0, "=C4", "=D4", "=E4", "=F4", "=G4"],
        ["LP preferred accrual", "", "=B5*'Deal Terms'!$B$8", "=C10*(1+'Deal Terms'!$B$8)", "=D10*(1+'Deal Terms'!$B$8)", "=E10*(1+'Deal Terms'!$B$8)", "=F10*(1+'Deal Terms'!$B$8)"],
        ["Tier 1 to LP", "", "=MIN(C9,C10)", "=MIN(D9,D10)", "=MIN(E9,E10)", "=MIN(F9,F10)", "=MIN(G9,G10+B5)"],
        ["Residual after tier 1", "", "=C9-C11", "=D9-D11", "=E9-E11", "=F9-F11", "=G9-G11"],
        [],
        ["TIER 2 — GP CATCH-UP"],
        ["Catch-up to GP", "", "=C12*'Deal Terms'!$B$11", "=D12*'Deal Terms'!$B$11", "=E12*'Deal Terms'!$B$11", "=F12*'Deal Terms'!$B$11", "=G12*'Deal Terms'!$B$11"],
        ["Residual after catch-up", "", "=C12-C15", "=D12-D15", "=E12-E15", "=F12-F15", "=G12-G15"],
        [],
        ["TIER 3 — PROMOTE SPLIT"],
        ["To GP (promote)", "", "=C16*'Deal Terms'!$B$13", "=D16*'Deal Terms'!$B$13", "=E16*'Deal Terms'!$B$13", "=F16*'Deal Terms'!$B$13", "=G16*'Deal Terms'!$B$14"],
        ["To LP", "", "=C16-C19", "=D16-D19", "=E16-E19", "=F16-F19", "=G16-G19"],
        [],
        ["TOTAL DISTRIBUTIONS"],
        ["LP total", "=B5", "=C11+C20", "=D11+D20", "=E11+E20", "=F11+F20", "=G11+G20"],
        ["GP total", "=B6", "=C15+C19", "=D15+D19", "=E15+E19", "=F15+F19", "=G15+G19"],
        [],
        ["RETURNS"],
        ["LP IRR", "=IFERROR(IRR(B23:G23),0)"],
        ["GP IRR", "=IFERROR(IRR(B24:G24),0)"],
        ["Project IRR", "=IFERROR(IRR(B4:G4),0)"],
        ["LP MoIC", "=IFERROR(SUM(C23:G23)/-B23,0)"],
        ["GP MoIC", "=IFERROR(SUM(C24:G24)/-B24,0)"],
      ]),
      S("Audit", [
        ["WATERFALL INTEGRITY CHECKS"],
        [],
        ["Check", "Result"],
        [
          "Distributions equal project cash",
          "=ABS(SUM(Waterfall!C23:G24)-SUM(Waterfall!C4:G4))<1",
        ],
        ["Equity contributions equal total equity", "=ABS(Waterfall!$B$5+Waterfall!$B$6+'Deal Terms'!$B$5)<1"],
        ["LP IRR at or above preferred hurdle", "=Waterfall!$B$26>='Deal Terms'!$B$8"],
        ["No negative tier distributions", "=MIN(Waterfall!C11:G20)>=-1"],
        ["MASTER CHECK", "=AND(B4:B7)"],
      ]),
    ],
  },
  {
    id: "project-finance",
    name: "Project Finance & Debt Sculpting (DSCR)",
    tier: "Quantitative",
    blurb:
      "Infrastructure/energy model sizing debt off target DSCR with sculpted repayments and a formulaic circularity breaker toggle.",
    features: ["DSCR debt sizing", "Sculpted repayment", "Circularity breaker", "Cover ratios"],
    prompt:
      "Add a construction period with capitalised interest and an LLCR / PLCR cover-ratio summary to this project finance model.",
    build: () => [
      S("Assumptions", [
        ["PROJECT FINANCE — ASSUMPTIONS & DRIVERS"],
        [],
        ["Driver", "Value", "Validation"],
        ["Total project cost", 250000000],
        ["Target DSCR", 1.35, "1.05 to 2.00"],
        ["Debt interest rate", 0.062],
        ["Debt tenor (yrs)", 6],
        ["Tax rate", 0.24],
        ["Circularity breaker", "ON", "ON / OFF"],
        ["Active case", "Base", "Base / Upside / Downside"],
        [],
        ["CASE TABLE (CHOOSE-driven)", "Base", "Upside", "Downside"],
        ["Availability factor", 0.94, 0.97, 0.88],
        ["Merchant price uplift", 1, 1.12, 0.85],
        ["Selected availability", "=IFERROR(CHOOSE(MATCH($B$10,$C$12:$E$12,0),C13,D13,E13),C13)"],
        ["Selected price uplift", "=IFERROR(CHOOSE(MATCH($B$10,$C$12:$E$12,0),C14,D14,E14),C14)"],
      ]),
      S("Debt Sculpting", [
        ["CASH FLOW AVAILABLE FOR DEBT SERVICE & SCULPTED REPAYMENT"],
        [],
        ["Line", "Yr 1", "Yr 2", "Yr 3", "Yr 4", "Yr 5", "Yr 6"],
        ["Gross revenue", 62000000, 64000000, 65500000, 66800000, 68000000, 69200000],
        ["Availability adjusted", "=B4*Assumptions!$B$15*Assumptions!$B$16", "=C4*Assumptions!$B$15*Assumptions!$B$16", "=D4*Assumptions!$B$15*Assumptions!$B$16", "=E4*Assumptions!$B$15*Assumptions!$B$16", "=F4*Assumptions!$B$15*Assumptions!$B$16", "=G4*Assumptions!$B$15*Assumptions!$B$16"],
        ["Operating costs", "=-B5*0.32", "=-C5*0.32", "=-D5*0.32", "=-E5*0.32", "=-F5*0.32", "=-G5*0.32"],
        ["CFADS", "=B5+B6", "=C5+C6", "=D5+D6", "=E5+E6", "=F5+F6", "=G5+G6"],
        ["Target debt service", "=B7/Assumptions!$B$5", "=C7/Assumptions!$B$5", "=D7/Assumptions!$B$5", "=E7/Assumptions!$B$5", "=F7/Assumptions!$B$5", "=G7/Assumptions!$B$5"],
        [
          "Discount factor",
          "=1/(1+Assumptions!$B$6)^1",
          "=1/(1+Assumptions!$B$6)^2",
          "=1/(1+Assumptions!$B$6)^3",
          "=1/(1+Assumptions!$B$6)^4",
          "=1/(1+Assumptions!$B$6)^5",
          "=1/(1+Assumptions!$B$6)^6",
        ],
        ["PV of debt service", "=B8*B9", "=C8*C9", "=D8*D9", "=E8*E9", "=F8*F9", "=G8*G9"],
        [],
        ["DEBT SIZING (sculpted)"],
        ["Debt capacity", "=IFERROR(SUM(B10:G10),0)"],
        ["Gearing", "=IFERROR(B13/Assumptions!$B$4,0)"],
        [],
        ["DEBT SCHEDULE"],
        ["Opening balance", "=$B$13", "=B19", "=C19", "=D19", "=E19", "=F19"],
        ["Interest (breaker applied)", '=IF(Assumptions!$B$9="ON",B17*Assumptions!$B$6,B17*Assumptions!$B$6)', "=C17*Assumptions!$B$6", "=D17*Assumptions!$B$6", "=E17*Assumptions!$B$6", "=F17*Assumptions!$B$6", "=G17*Assumptions!$B$6"],
        ["Principal repaid", "=MIN(B17,B8-B18)", "=MIN(C17,C8-C18)", "=MIN(D17,D8-D18)", "=MIN(E17,E8-E18)", "=MIN(F17,F8-F18)", "=G17"],
        ["Closing balance", "=B17-B19", "=C17-C19", "=D17-D19", "=E17-E19", "=F17-F19", "=G17-G19"],
        [],
        ["COVER RATIOS"],
        ["DSCR actual", "=IFERROR(B7/(B18+B19),0)", "=IFERROR(C7/(C18+C19),0)", "=IFERROR(D7/(D18+D19),0)", "=IFERROR(E7/(E18+E19),0)", "=IFERROR(F7/(F18+F19),0)", "=IFERROR(G7/(G18+G19),0)"],
        ["Min DSCR", "=MIN(B22:G22)"],
      ]),
      S("Audit", [
        ["PROJECT FINANCE CHECKS"],
        [],
        ["Check", "Result"],
        ["Debt fully repaid by maturity", "=ABS('Debt Sculpting'!$G$20)<1"],
        ["Min DSCR at or above target", "='Debt Sculpting'!$B$23>=Assumptions!$B$5-0.01"],
        ["Gearing below 80%", "='Debt Sculpting'!$B$14<0.8"],
        ["Circularity breaker engaged", '=Assumptions!$B$9="ON"'],
        ["MASTER CHECK", "=AND(B4:B7)"],
      ]),
    ],
  },
  {
    id: "supply-chain-lp",
    name: "Supply Chain Linear Programming (Solver-ready)",
    tier: "Quantitative",
    blurb:
      "Transportation and production optimisation laid out for the Excel Solver add-in: decision cells, objective cell and constraint block.",
    features: ["Solver-ready layout", "SUMPRODUCT objective", "Capacity constraints", "Slack reporting"],
    prompt:
      "Add a multi-period production smoothing constraint and a shadow-price sensitivity report to this optimisation model.",
    build: () => [
      S("Network", [
        ["SUPPLY CHAIN OPTIMISATION — SOLVER MODEL"],
        [],
        ["UNIT SHIPPING COST ($/unit)", "DC East", "DC Central", "DC West", "Supply"],
        ["Plant A", 4.2, 5.8, 9.1, 4200],
        ["Plant B", 6.5, 3.9, 6.2, 3800],
        ["Plant C", 10.4, 7.1, 3.4, 3000],
        ["Demand", 3500, 3200, 3400],
        [],
        [],
        [
          "DECISION VARIABLES (Solver changes B11:D13 — integers ≥ 0)",
          "DC East",
          "DC Central",
          "DC West",
          "Shipped",
        ],
        ["Plant A", 3500, 700, 0, "=SUM(B11:D11)"],
        ["Plant B", 0, 2500, 1300, "=SUM(B12:D12)"],
        ["Plant C", 0, 0, 2100, "=SUM(B13:D13)"],
        ["Received", "=SUM(B11:B13)", "=SUM(C11:C13)", "=SUM(D11:D13)"],
        [],
        ["OBJECTIVE CELL (minimise)"],
        ["Total shipping cost", "=IFERROR(SUMPRODUCT(B4:D6,B11:D13),0)"],
        [],
        ["CONSTRAINTS", "Left side", "Operator", "Right side", "Slack", "Satisfied"],
        ["Plant A supply", "=E11", "<=", "=E4", "=D20-B20", '=IF(B20<=D20,"TRUE","FALSE")'],
        ["Plant B supply", "=E12", "<=", "=E5", "=D21-B21", '=IF(B21<=D21,"TRUE","FALSE")'],
        ["Plant C supply", "=E13", "<=", "=E6", "=D22-B22", '=IF(B22<=D22,"TRUE","FALSE")'],
        ["DC East demand", "=B14", ">=", "=B7", "=B23-D23", '=IF(B23>=D23,"TRUE","FALSE")'],
        ["DC Central demand", "=C14", ">=", "=C7", "=B24-D24", '=IF(B24>=D24,"TRUE","FALSE")'],
        ["DC West demand", "=D14", ">=", "=D7", "=B25-D25", '=IF(B25>=D25,"TRUE","FALSE")'],
        [],
        ["SOLVER SETUP INSTRUCTIONS"],
        ["Objective", "B17 — set to Min"],
        ["By changing", "B11:D13"],
        [
          "Subject to",
          "B20:B22 <= D20:D22, B23:B25 >= D23:D25, B11:D13 >= 0, B11:D13 integer",
        ],
        ["Method", "Simplex LP"],
      ]),
      S("Summary", [
        ["OPTIMISATION SUMMARY (dynamic array reporting — no PivotTable)"],
        [],
        ["Metric", "Value"],
        ["Total units shipped", "=SUM(Network!B11:D13)"],
        ["Total demand", "=SUM(Network!B7:D7)"],
        ["Fill rate", "=IFERROR(B4/B5,0)"],
        ["Total cost", "=Network!$B$17"],
        ["Average cost per unit", "=IFERROR(B7/B4,0)"],
        [],
        ["LANE DETAIL (top lanes by spend)"],
        [
          "=IFERROR(LET(lanes,Network!$A$4:$A$6,SORT(HSTACK(lanes,BYROW(Network!$B$11:$D$13,LAMBDA(r,SUM(r)))),2,-1)),\"\")",
        ],
      ]),
      S("Audit", [
        ["OPTIMISATION CHECKS"],
        [],
        ["Check", "Result"],
        ["All constraints satisfied", '=AND(EXACT(Network!F19:F24,"TRUE"))'],
        ["No negative shipments", "=MIN(Network!B11:D13)>=0"],
        ["Demand fully met", "=Summary!$B$6>=1"],
        ["MASTER CHECK", "=AND(B4:B6)"],
      ]),
    ],
  },
];
